### ISSUE TITLE
Feature request: zoom function

### ISSUE THREAD

**Issue by uribo** [GuangchuangYu/ggtree#1]
`ggtree` is a cool package.

I want to expand the phylogenetic tree.
I'm glad and if there is a function, such as the `zoom` function of the `ape` package

**Comment by GuangchuangYu** [comment]
It's now supported. Please try the following example:

```r
require(ape)
data(chiroptera)
require(ggtree)
gzoom(chiroptera, grep("Plecotus", chiroptera$tip.label))
```

**Comment by GuangchuangYu** [comment]
for your information, the `gzoom` function was removed in current devel branch, since it can be easily done by `treeio::tree_subset`. 

see <https://yulab-smu.github.io/treedata-book/chapter2.html#subsetting-tree-with-data>.
