### ISSUE TITLE
Error in read.beast() (related to #84)

### ISSUE THREAD

**Issue by pclangat** [GuangchuangYu/ggtree#100]
Hi there, I still get an error when opening example or my own beast files using ggtree v1.6.4

x <- read.beast("/Software_downloaded/FigTree_v1.4.2/influenza.tree")
Error in 1:nnode : argument of length 0

Many thanks
PL

**Comment by GuangchuangYu** [comment]
will comment on <https://github.com/GuangchuangYu/ggtree/issues/84>
