### ISSUE TITLE
rotate seems to be broken

### ISSUE THREAD

**Issue by wheelern** [GuangchuangYu/ggtree#104]
The example code from the docs does not work:

`nwk <- system.file("extdata", "sample.nwk", package="ggtree")`
`tree <- read.tree(nwk)`
`ggtree(tree) + geom_text2(aes(subset=!isTip, label=node), hjust=-.3) + geom_tiplab()`
`p <- ggtree(tree, aes(color=group)) + scale_color_manual(values=c("black", "firebrick", "steelblue"))`
`p2 <- rotate(p, 21)`

Error reads: Error in rotate(p, 21) : object "phy" is not of class "phylo"

I get the same error for my own tree as well.

**Comment by GuangchuangYu** [comment]
follow the [guide](https://guangchuangyu.github.io/ggtree/#feedback) and provide a reproducible example pls.

**Comment by wheelern** [comment]
Got it. For posterity, the problem was that the rotate() function was defaulting to ape::rotate instead of ggtree::rotate. Explicit calls to ggtree::rotate didn't work either. I had to detach ape.

**Comment by GuangchuangYu** [comment]
good catch and thanks for your feedback.
