### ISSUE TITLE
Problem with label in "fan" plots

### ISSUE THREAD

**Issue by AEgit** [GuangchuangYu/ggtree#106]
Hi,

I've a problem with the label parameter when using "fan" plots. Consider the following minimum example:

```
myplot <- ggtree(mytree, branch.length="none")
myplot <- myplot %<+% edge +
  geom_tiplab(size=3, label = sub("_", " ", myplot$data$label[which(myplot$data$isTip == TRUE)]), fontface="italic")
myplot
```

This gives a nice normal phylogram. Note, that I replace underscores in my tips with space.

Now let's use the exact same code, but adapted for a tree with "fan" layout.

```
myfanplot <- ggtree(mytree, layout="fan", branch.length="none")
myfanplot <- myfanplot %<+% edge +
  geom_tiplab2(size=3, label = sub("_", " ", myfanplot$data$label[which(myfanplot$data$isTip == TRUE)]), fontface="italic")
myfanplot
```

This results in the following error:
**Error: Aesthetics must be either length 1 or the same as the data (75): label, size, hjust, fontface**

If I use the same "fan" code without the label parameter everything works fine:

```
myfanplot <- ggtree(mytree, layout="fan", branch.length="none")
myfanplot <- myfanplot %<+% edge +
  geom_tiplab2(size=3, fontface="italic")
myfanplot
```

Can you confirm this issue? I'm using version 1.6.4 of ggtree.

**Comment by GuangchuangYu** [comment]
see <https://guangchuangyu.github.io/ggtree/faq/#use-in-aes>.

**Comment by AEgit** [comment]
Thank you very much - I didn't realize this issue because using "$" did work in the phylogram plot. But I guess I was just lucky that ggtree didn't change the order of the rows for the phylogram plot. Thanks again!

I'll close this.

**Comment by JakoboEU** [comment]
Hi @GuangchuangYu , those links are now dead. Could you please update them?
