### ISSUE TITLE
convert data.frame to tree format?

### ISSUE THREAD

**Issue by duleise** [GuangchuangYu/ggtree#108]
is there a function from within this package or somewhere else, that can convert a data.frame into a tree format? ie. the opposite of fortify?
thanks.

**Comment by GuangchuangYu** [comment]
The opposite of fortify is currently not available, but you can convert the data.frame back to a phylo object by using `get.tree` method (currently only available in github version).

**Comment by GuangchuangYu** [comment]
this method will eventually goes to <https://github.com/GuangchuangYu/treeio> and maybe convert data.frame back to a tree object that can store annotation information will be added in future.

**Comment by GuangchuangYu** [comment]
`as.phylo.data.frame` was implemented in `treeio`, <https://github.com/GuangchuangYu/treeio/blob/master/R/method-as-phylo.R>.
