### ISSUE TITLE
feature request: ggrepel aware of tree structure

### ISSUE THREAD

**Issue by andzandz11** [GuangchuangYu/ggtree#110]
Is there a way to make geom_text_repel aware of tip labels and tree structure? Because right now it is looking a bit chaotic. 
![ggrepel](https://cloud.githubusercontent.com/assets/19622117/21581688/0eda970c-d03d-11e6-9926-d0f7b4e6947e.png)

for comparison: geom_text2 
![geom_text](https://cloud.githubusercontent.com/assets/19622117/21581694/2f288bcc-d03d-11e6-87fc-51fb817ad9c2.png)

**Comment by GuangchuangYu** [comment]
This is due to they are labeling it two different layers.

If your `bootstrap` values is stored as node label, you can use `geom_text_repel(aes(label=label)`. Otherwise, IMO it can't be solved. 

Maybe @slowkow can give some comments.

**Comment by slowkow** [comment]
@andzandz11 

I'm not sure if it is possible to make `geom_text_repel` aware of the tree and node labels. Sorry, but I'm not available to work on this right now. I recommend that you use `geom_text` in this case.

**Comment by andzandz11** [comment]
Thank you for answering my idea 👍
