### ISSUE TITLE
ggtree branch.length parameter has no affect on unrooted tree.

### ISSUE THREAD

**Issue by JustGitting** [GuangchuangYu/ggtree#114]
Hi,

I'm playing around with plotting of phylogenetic trees using the APE package and now GGTREE. In particular I want to create unrooted phylogenetic trees. 

ape::plot seems straight forward to use, but ggtree looks like it has a more powerful range of options, such as tree annotation. However, I've found a problem with branch length in ggtree.

For readability, I wanted to ignore branch length. 

For example in APE it can be achieved using the "use.edge.length" switch. 

Whilst, I would have expected the branch.length="none" option to work in ggplot(). However, it does not have any affect on the branch lengths for unrooted trees.

Note: version of ggtree is v1.6.9

**Example**

```
library(ape)
library(ggtree)

# Create a tree, example copied from @RaSieb (https://github.com/GuangchuangYu/ggtree/issues/95)
set.seed(6464); 
t <- rtree(60);

# Create unrooted and fan (circular) trees using APE.
layout(matrix(1:4, 2, 2))
ape::plot.phylo(t, type = "unrooted")
ape::plot.phylo(t, type = "unrooted", use.edge.length = FALSE)
ape::plot.phylo(t, type = "fan")
ape::plot.phylo(t, type = "fan", use.edge.length = FALSE)
layout(matrix(1))

# Create unrooted and fan (circular) trees using GGTREE.
p1 <- ggtree(t, layout="unrooted")
p2 <- ggtree(t, layout="unrooted", branch.length="none")
p3 <- ggtree(t, layout="circular")
p4 <- ggtree(t, layout="circular", branch.length="none")

multiplot(p1, p2, p3, p4, ncol = 2)
```
Please see attached png files for the output. As you can see, only the unrooted tree from ggtree does not change when using the branch.length="none" option.

Is this a bug or there another option for unrooted trees?

Thanks for your help.

**Ape plots**
![ape_unrooted](https://cloud.githubusercontent.com/assets/6530017/23448822/5f14ccb8-fea7-11e6-8021-ae20b546a573.png)

**ggplot plots**
![ggtree_unrooted](https://cloud.githubusercontent.com/assets/6530017/23448823/5f18587e-fea7-11e6-9996-e8b3dd74d7a0.png)

**Comment by GuangchuangYu** [comment]
although I fixed this issue, I personally don't recommend you using unrooted layout in ggtree, since (currently) it only implemented the equal-angle algorithm and didn't use most of the space as `ape` did.

**Comment by JustGitting** [comment]
Thanks for the fast fix @GuangchuangYu
