### ISSUE TITLE
geom_tiplab fails with geom='label'

### ISSUE THREAD

**Issue by brj1** [GuangchuangYu/ggtree#115]
I recently tried using geom_tiplab with geom='label', but it produced the following error:
"Error: Specify either `position` or `nudge_x`/`nudge_y`"

Below is a minimal reproducible example using the latest version of ggtree (v1.7.8) from GitHub, ape v4.0, ggplot2 v2.2.1, treeio v0.99.9 and R v3.3.2.

library(ape)
library(ggtree)

set.seed(1984)

tree <- rtree(5)
dat <- data.frame(node=1:9, good=as.character(1:9))

ggtree(tree) %<+% dat + geom_tiplab(aes(label=good, subset=!isTip)) # works
ggtree(tree) %<+% dat + geom_tiplab(aes(label=good, subset=!isTip), geom='label') # does not work

**Comment by brj1** [comment]
I figured this out. I should have used geom_label2 instead of geom_tiplab.

**Comment by GuangchuangYu** [comment]
```
## now it works 
ggtree(tree) %<+% dat + geom_tiplab(aes(label=good, subset=!isTip), geom='label') 
```
