### ISSUE TITLE
Size of each plot when multiplotting

### ISSUE THREAD

**Issue by nilsrudqvist** [GuangchuangYu/ggtree#116]
Hi, 

First, thanks for an amazing package!

Second, I want do adjust the scale of each of my plots in multiplot. Is this possible? Now, the margins of each plot is very large.

Thanks,
Nils

**Comment by nilsrudqvist** [comment]
[Rplot.pdf](https://github.com/GuangchuangYu/ggtree/files/812065/Rplot.pdf)

**Comment by GuangchuangYu** [comment]
this is a famous issue of `ggplot2::coord_polar` (see also <https://stackoverflow.com/questions/38034560/reduce-margins-around-ggplot2-pie-chart>), I also don't know have to solve it.

**Comment by nilsrudqvist** [comment]
Thank you!

**Comment by valentinitnelav** [comment]
Hi,

Is there any way around fixing this bug? I have only one circular tree and 
`theme(plot.margin = unit(c(t = -2, r = 0, b = -2, l = 1), "cm"))` does not seem to have any kind of effect. I get a significant amount of margin space that I want to eliminate somehow. I guess I could solve it in Inkscape, but would be really handy to have a solution compatible with ggplot.

Thank you so much for your work!
Valentin

**Comment by cliffbueno** [comment]
I think playing with xlim() can help in this case too, as Dr. Yu has commented elsewhere (https://support.bioconductor.org/p/72398/). Note that you'll have to play around with the values some based on your own tree.

**Comment by GuangchuangYu** [comment]
The `ggplotify::as.ggplot()` function has a `scale` parameter, that allows user to zoom in the figure. I think this is the trick to remove plot margin.

**Comment by gavinmdouglas** [comment]
I found that playing around with `plot.margin` values was useful for cropping the margin from around trees.

For example: `+  theme(plot.margin=unit(c(-45,-20,-25,-35), "mm"))`
