### ISSUE TITLE
Unrooted tree annotations don't work as expected.

### ISSUE THREAD

**Issue by JustGitting** [GuangchuangYu/ggtree#118]
Hi,

I'm trying to annotate an unrooted tree, but it's not behaving as expected. For example, adding a clade label and hilighting works nicely for a "Fan" tree layout, but not for the unrooted tree layout.

```
library(ggtree)

set.seed(6464);
t <- rtree(60);

# Create a fan and unrooted tree. 
# Use the geom_text2() to get a suitable node numbers for clade labeling later.
tree_fan <- ggtree(t, layout="fan" ) + 
#geom_text2( aes(subset=!isTip, label=node), hjust=-1) + 
ggtitle("Fan tree, with clade highlighting");

tree_unrooted <- ggtree(t, layout="unrooted" ) + 
#geom_text2( aes(subset=!isTip, label=node), hjust=-1) + 
ggtitle("Unrooted tree, with clade highlighting");

# add clade label and hilighting.
# Pick node from the node labels created by geom_text2. Left out for clarity of image.
tree_fan <- tree_fan + 
geom_cladelabel(node=114, label="Label 1", align=TRUE, offset=4, color='red') + 
geom_hilight(node=114, fill="steelblue", alpha=.6);

tree_unrooted <- tree_unrooted + 
geom_cladelabel(node=114, label="Label 1", align=TRUE, offset=.5, color='red') + 
geom_hilight(node=114, fill="steelblue", alpha=.6);

multiplot(tree_fan, tree_unrooted, ncol = 2)
```

I understand the algorithms for handling annotations of different tree layouts are different (and non-trivial). However, the annotations should work for each tree layout type.

Cheers

![unrooted_annotation_problem](https://cloud.githubusercontent.com/assets/6530017/23592326/213c20ee-0253-11e7-8488-70bc3b9248d4.png)

**Comment by JustGitting** [comment]
Hi Guang Chuang Yu,

Thanks for your quick reply. Do you plan to add this feature? As it would be very handy to have. So a user can change the layout and all annotations work transparently.

Cheers

**Comment by GuangchuangYu** [comment]
currently not. I prefer to implement a better unrooted layout first if I have some free times.

**Comment by JustGitting** [comment]
Mmm, seems there are not many options for unrooted tree visualization. Python ETE doesn't seem to have support, R's own ape is basic.

Do you have a reference(s) for unrooted tree layout and annotations?

**Comment by GuangchuangYu** [comment]
chapter 14 of `Inferring Phylogenies` might be helpful.

**Comment by JustGitting** [comment]
Thanks, I found the reference. "Drawing Trees" is in chapter 34.

What algorithm do you use currently? Equal angle?

**Comment by GuangchuangYu** [comment]
yes, it is chapter 34 and I only implemented equal angle algorithm in ggtree.

**Comment by JustGitting** [comment]
Useful reference:

Graph drawing: unrooted undirected tree graphs with specified edge lengths.
http://mathoverflow.net/questions/79315/graph-drawing-unrooted-undirected-tree-graphs-with-specified-edge-lengths

**Comment by JustGitting** [comment]
I'll try to do a push-request (PR) with another layout algorithm ("equal-daylight" from Felsenstein, p582) in the next week or so.

**Comment by JustGitting** [comment]
Not sure where to ask this, but in layout.unrooted() function (tidytree.r file). 

What does the following equation mean?
df[child, "angle"] <- -90 - 180 * beta * sign(beta - 1)

Seems to be the orthogonal angle to to the line from the parent node to the child node. Where beta is the angle from the "start" angle.

**Comment by GuangchuangYu** [comment]
yes, the `angle` is for labeling.

**Comment by JustGitting** [comment]
Following on from this topic. I wish to update the geom_hilight() and geom_cladelabel() functions to correctly handle unrooted tree topologies (regardless of layout method). 

It's a little opaque how these functions work. Whats the sequence/workflow of these functions? So I can update the geometry and labeling code to handle different tree structures correctly.

Thanks for your help.

**Comment by GuangchuangYu** [comment]
It may not possible to access parameters (e.g. `layout`) in `geom` layers. This is why I implement `geom_tiplab` for `rectangular` and `geom_tiplab2` for `circular` layout. As `unrooted` has different layout methods, thing will be complicated. 

Maybe something like <https://github.com/hrbrmstr/ggalt#encircling-points-automagically> can be employed to highlight clade of unrooted tree.

**Comment by JustGitting** [comment]
Thanks for the link.

To clarify. Are you suggesting we use the ggalt::geom_encircle() function within ggtree (creating an extra dependency) or re-implement the geom_encircle() functionality within ggtree (creating duplication...)?

What do you suggest be the most suitable approach?

**Comment by GuangchuangYu** [comment]
I would recommend to implement it independently as `ggalt`'s dependency is huge.

For `geom_hilight` layer, I think we need to introduce `layout` parameter in order to make it support `unrooted` tree.

**Comment by JustGitting** [comment]
Do you mean the geom_hilight() parameters would look like the example below?

`ggtree(tree, layout="unrooted") + geom_hilight(node=21, fill="steelblue", alpha=.6, layout="unrooted")`

**Comment by GuangchuangYu** [comment]
for `unrooted`, user should specify the actual `layout method` instead of just `unrooted`.

**Comment by JustGitting** [comment]
Like this then:

ggtree(tree, layout="unrooted", layout.method="daylight") + geom_hilight(node=21, fill="steelblue", alpha=.6, layout="unrooted", layout.method="daylight")

**Comment by GuangchuangYu** [comment]
Actually, I would like to remove `layout.method` and only use `layout`. User can specify different layout method for `unrooted` tree by e.g. `layout = "daylight"`. 

If user pass `layout="unrooted"`, we just need to convert it to `layout = "daylight"` as default method for `unrooted` and giving msg in console like `"daylight" method was used as default layout of unrooted tree.`.

Then we can make everything consistent and don't need to introduce 2 parameters in `geom_hilight`.

**Comment by GuangchuangYu** [comment]
I really appreciate your contributions.

Please edit <https://github.com/GuangchuangYu/ggtree/blob/master/DESCRIPTION> and <https://github.com/GuangchuangYu/ggtree/blob/master/CONTRIBUTORS.md> to acknowledge your contributions.

**Comment by JustGitting** [comment]
Thanks for your kind words. I also appreciate your hard work creating ggtree in the first place, during your PhD studies, which is a very big task. 

I hope all the other researchers and organisations that benefit from ggtree can contribute and help in some way as well. :-)

**Comment by JustGitting** [comment]
Okay, I'll remove the `layout.method` parameter in ggtree and use the `layout` parameter in the `geom_hilight()` function.

**Comment by GuangchuangYu** [comment]
@JustGitting FYI, I have removed the `layout.method` parameter as it [introduced bug](https://github.com/GuangchuangYu/ggtree/issues/125) in `fortify` method.

**Comment by JustGitting** [comment]
It might be a longer term goal, but are you able to introduce unit testing? 
This would help to catch regressions, like but #125.
I can have a go at introducing unit testing (using `runit`). However, you know this project inside out and would be much faster at doing a few examples.

**Comment by GuangchuangYu** [comment]
I did use `testthat` for unit testing. Unit testing especially for new feature is highly recommended.

Sorry, I just too busy recently to work on `ggtree`. 

Now all tree parsers are move to `treeio` package. For long term goal, I will also split fortify methods and functions works with data frame to `tidytree` package which will provide users easy to use data frame/tibble for tree structure and functions to operate/manipulate it. Then `ggtree` will only focus on visualization.

**Comment by JustGitting** [comment]
Great, I'll try to add some tests to the tests directory then.

**Comment by GuangchuangYu** [comment]
![geom_hilight_encircle](https://user-images.githubusercontent.com/626539/30324781-ceb7d93e-97f4-11e7-8ded-04c66e8a6d88.jpeg)

Thanks to @JustGitting, now we have `geom_hilight_encircle` and `geom_cladelabel2`.
