### ISSUE TITLE
Could not find function "read.raxml"

### ISSUE THREAD

**Issue by FluFighterBK** [GuangchuangYu/ggtree#12]
Hello,

I am trying to read and annotate a raxl tree with bootstrap in ggtree and i get the following error:

> raxml_file <- system.file("extdata/RAxML", "/Desktop/standard-RAxML-master/RAxML_bipartitionsBrachLabels_18K_H3.tree", package="ggtree")
> raxml <- read.raxml(raxml_file)
Error: could not find function "read.raxml"

Please let me know if there is a solution to this problem.

Thanks

**Comment by GuangchuangYu** [comment]
you need to update [ggtree](http://bioconductor.org/packages/release/bioc/html/ggtree.html).

**Comment by sapuizait** [comment]
same problem on a fresh install of ggtree from Bioconductor! I am using latest R version 4.0.5, Bioconductor version 3.12 (BiocManager 1.30.12) and ggtree v2.4.1

**Comment by Jubina09** [comment]
I am facing the same issue,

R version is 4.3.3
ggtree is 3.10.1

> read.raxml(raxml_file)
Error in read.raxml(raxml_file) : could not find function "read.raxml"
