### ISSUE TITLE
font size and angle for heat map not used with time scaled tree

### ISSUE THREAD

**Issue by davideyre** [GuangchuangYu/ggtree#121]
The font.size and colnames_angle options in gheatmap() are not used when using the time-scaled tree work around. E.g.

```
beast_file <- system.file("examples/MCC_FluA_H3.tree", package="ggtree")
beast_tree <- read.beast(beast_file)

genotype_file <- system.file("examples/Genotype.txt", package="ggtree")
genotype <- read.table(genotype_file, sep="\t", stringsAsFactor=F)
colnames(genotype) <- sub("\\.$", "", colnames(genotype))

p <- ggtree(beast_tree, mrsd="2013-01-01") + geom_tiplab(size=2, align=TRUE, linesize=.5) + theme_tree2()
pp <- (p + scale_y_continuous(expand=c(0, 0.3))) %>%
   gheatmap(genotype, offset=8, width=0.6, font.size=6, colnames_angle=-45, hjust=1, colnames=FALSE) %>%
   scale_x_ggtree()
pp + theme(legend.position="right")
```

This generates the same tree as without specifying the options and the warning:

```
Warning message:
The plyr::rename operation has created duplicates for the following name(s): (`size`) 
```

**Comment by GuangchuangYu** [comment]
It is expected in this scenario, as `scale_x_ggtree` only works to break the `x-axis`.

There is no dual x-axis in ggplot2.

**Comment by GuangchuangYu** [comment]
see also <https://github.com/tidyverse/ggplot2/issues/1588>

**Comment by davideyre** [comment]
okay, so perhaps this is more of a feature request and would have to be achieved using https://github.com/baptiste/gridextra or similar?

might also be worth mentioning the current limitation in the gheatmap() documentation?

**Comment by GuangchuangYu** [comment]
yes, should add more description in man file.

see also <https://github.com/GuangchuangYu/ggtree/issues/26>.
