### ISSUE TITLE
bug in fortify.phylo4d

### ISSUE THREAD

**Issue by brj1** [GuangchuangYu/ggtree#125]
The current version of ggtree fails to fortify phylo4d objects:

```R
library(ggtree)
library(phylobase)
set.seed(1)
ptree <- phylo4d(rtree(3), data.frame(value=c(1,2,3)))
fortify(ptree)
```
produces the following error:

> Error in match.arg(branch.length, cn) :
 'arg' must be NULL or a character vector

The problem is the addition of the layout.method parameter to the fortify.phylo4d function. I fixed this in my fork by adding the parameter to the fortify.treedata function. I'm not sure about the consequences, so I made this issue instead of a pull request.

**Comment by GuangchuangYu** [comment]
The `layout.method` was removed as I mentioned [here](https://github.com/GuangchuangYu/ggtree/issues/118#issuecomment-295130818), and the bug had been fixed.
