### ISSUE TITLE
Cannot download the Package Archives

### ISSUE THREAD

**Issue by nicolawongwaiyee** [GuangchuangYu/ggtree#126]
I installed ggtree follwing the guideline and checked the version:

```
source("https://bioconductor.org/biocLite.R")
biocLite("ggtree")
packageVersion("ggtree")
[1] ‘1.2.17’
```

Seems it is not the newest version suggested, I met a problem when using the main function `ggtree()`
```
Error: StatTreeHorizontal was built with an incompatible version of ggproto.
Please reinstall the package that provides this extension.
```
I also tried `biocLite("ggtree", type = "source")`, but still cannot get the newest version.
So I try to install it from the archives from ggtree Bioconductor page but in vain, it directed me to a page not found.
Would like to know is there any other way to install the newest version of ggtree?

**Comment by GuangchuangYu** [comment]
you need to upgrade R to 3.4.0 .
