### ISSUE TITLE
Problems with groupOTU

### ISSUE THREAD

**Issue by zh3ngq1n** [GuangchuangYu/ggtree#127]
HI,the ggtree is very useful,but i have one problem about groupOUT. Can you help me?
This is my tree.
(((((Cellvibrionales:0.04156,(Oceanospirillales:0.0667,Pseudomonadales:0.05336)0.803:0.02998)0.678:0.0191,((Rhodocyclales:0.02498,((Methylophilales:0.05002,Hydrogenophilales:0.02355)0.791:0.02679,Burkholderiales:0.0422)0.771:0.02181)0.997:0.06006,(Thiotrichales:0.08194,Xanthomonadales:0.06225)0.956:0.03567)0.864:0.02081)0.980:0.05021,((Rickettsiales:0.09424,(Rhizobiales:0.0651,(Rhodobacterales:0.06939,Sphingomonadales:0.09076)0.939:0.03673)0.987:0.05721)0.813:0.02507,(Chlorobiales:0.12829,(Lactobacillales:0.102,Clostridiales:0.07873)0.304:0.01879)0.846:0.02178)0.927:0.03351)0.216:0.0107,(Bdellovibrionales:0.1062,(Desulfovibrionales:0.07195,(Myxococcales:0.11545,Campylobacterales:0.16984)0.785:0.02124)0.848:0.02539)0.859:0.02292)0.123:0.00767,(Verrucomicrobiales:0.10834,Opitutales:0.10406)0.984:0.04628,((Cytophagales:0.05898,((Bacteroidia_Incertae_Sedis:0.10306,(Flavobacteriales:0.05501,Sphingobacteriales:0.09569)0.086:0.00133)0.968:0.05065,Bacteroidales:0.08653)0.705:0.03065)1.000:0.15843,Gemmatimonadales:0.11834)0.889:0.03426);

and this is my cls:
$Proteobacteria
 [1] "Bdellovibrionales"  "Oceanospirillales"  "Xanthomonadales"   
 [4] "Burkholderiales"    "Methylophilales"    "Rhodobacterales"   
 [7] "Rickettsiales"      "Rhizobiales"        "Myxococcales"      
[10] "Pseudomonadales"    "Campylobacterales"  "Thiotrichales"     
[13] "Hydrogenophilales"  "Rhodocyclales"      "Cellvibrionales"   
[16] "Desulfovibrionales" "Sphingomonadales"  

$Gemmatimonadetes
[1] "Gemmatimonadales"

$Bacteroidetes
[1] "Bacteroidia_Incertae_Sedis" "Flavobacteriales"          
[3] "Cytophagales"               "Bacteroidales"             
[5] "Sphingobacteriales"        

$Chlorobi
[1] "Chlorobiales"

$Firmicutes
[1] "Lactobacillales" "Clostridiales"  

$Verrucomicrobia
[1] "Opitutales"         "Verrucomicrobiales"

I used code : tree<-groupOTU(tree,cls)
The picture show "0" legend . why this happened,and how can i solve it.

![image](https://cloud.githubusercontent.com/assets/27850240/25791526/9f2d23fa-33f3-11e7-8f70-cf4a6d072d10.png)

and this is my code : 
ggtree(tree,layout='circular',branch.length='none',aes(color=group))+ geom_tiplab2(show.legend = FALSE,size=3)+geom_treescale()+scale_color_manual(values=mycol[1:length(unique(fortify(tree)$group))])+theme(legend.position="right",legend.title=element_blank(),plot.margin=unit(x=c(0,0.5,0,1),"cm"))+xlim(0,18)

**Comment by GuangchuangYu** [comment]
`0` is for those didn't belong to any group. You can use `+scale_color_manual(breaks=c(...))` to customize the legend.

**Comment by osoyer** [comment]
Hi Guangchuang,
I'm having the exact same problem as above. All the tips are assigned to a group, but I still get a "0" in the legend. Any ideas?

**Comment by GuangchuangYu** [comment]
the root node is not belong to any of your group and it was assigned to group 0. 

In next release, it will be set to NA instead of 0, so that you can disable it on legend easily.

**Comment by osoyer** [comment]
Do you have an immediate solution? It is weird, as this is not happening on another tree I have.

**Comment by xiekunwhy** [comment]
> the root node is not belong to any of your group and it was assigned to group 0.
> 
> In next release, it will be set to NA instead of 0, so that you can disable it on legend easily.

Hi,
Which version solved this problem?

**Comment by mluerig** [comment]
is there an update on this issue? doesn't seem to be solved in 3.10.1
