### ISSUE TITLE
'NJ' is not in the namespace of ggtree

### ISSUE THREAD

**Issue by bioinformatist** [GuangchuangYu/ggtree#129]
Dear Y,

To make a tree for one of my friends from a distance matrix, I try use `ggtree::NJ` to create a `phylo` object, then draw it.
I have installed `ggtree` through *Bioconductor* correctly, but I got this error when calling `NJ`:

```pre
Error in NJ(X) : could not find function "NJ"
```

I also try `ggtree::NJ`:

```pre
Error: 'NJ' is not an exported object from 'namespace:ggtree'
```

Below is my code:
```R
# No error or warning occurred in this step
source("https://bioconductor.org/biocLite.R")
biocLite('ggtree')

# No error again
library(ggtree)

# Example in help(NJ)
X <- matrix(c(0,5,4,7,6,8,
	5,0,7,10,9,11,
	4,7,0,7,6,8,
	7,10,7,0,5,9,
	6,9,6,5,0,8,
	8,11,8,9,8,0), ncol=6)
rownames(X) <- colnames(X) <- LETTERS[1:6]
tree <- NJ(X)
print(tree)
```

I've checked the NAMESPACE statement in both source and binary packages. It seems `NJ` has not been covered here. Also I try to `source` the [script](https://github.com/GuangchuangYu/ggtree/blob/master/R/NJ.R) contains this function in source directly and it works.

**Comment by GuangchuangYu** [comment]
The function was never exported. You can use `ape::nj`.
