### ISSUE TITLE
read.tree：The tree has apparently singleton node(s)

### ISSUE THREAD

**Issue by zh3ngq1n** [GuangchuangYu/ggtree#133]
hi，Guangchuang：
   
    My tree file has apparently singleton node(s) ,how can i read tree into R.
    my tree file such like this : (((((Gemmatimonas)Gemmatimonadaceae)Gemmatimonadales)Gemmatimonadetes)Gemmatimonadetes,Firmicutes)Bacteria;

**Comment by GuangchuangYu** [comment]
tree that contains singleton is not supported.
