### ISSUE TITLE
error adding associated matrix to collapsed tree

### ISSUE THREAD

**Issue by Ekie22** [GuangchuangYu/ggtree#137]
Hi,

when I try to add an associated matrix to a tree after a node was collapsed, I get an error.  

Example ggtree version 1.9.1:

`library(ggtree)` 
`beast_file <- system.file("examples/MCC_FluA_H3.tree", package="ggtree")`
`beast_tree <- read.beast(beast_file)`
`genotype_file <- system.file("examples/Genotype.txt", package="ggtree")`
`genotype <- read.table(genotype_file, sep="\t", stringsAsFactor=F)`
`colnames(genotype) <- sub("\\.$", "", colnames(genotype))`
`p <- ggtree(beast_tree, mrsd="2013-01-01") + geom_treescale(x=2008, y=1, offset=2)`
`p <- p + geom_tiplab(size=2)`

collapse node 123
`p1 <- p %>% collapse(node = 123)`
`p1`

add matrix results in error: replacement and data have different row length
`gheatmap(p1, genotype)`

Even if I subset the genotype table to the condensed tip labels, the error occurs:
`genotype_p1 <- genotype[!rownames(genotype) %in% 
                          p1$data[p1$data$node %in% 
                                    c(73, 67, 74, 64, 52, 63, 62, 65, 60, 51, 71, 70, 59, 76, 58, 57, 53, 72, 68), "label"],]`
`gheatmap(p1, genotype_p1)`

Is their a possibility to annotate collapsed trees? 
Thanks

**Comment by GuangchuangYu** [comment]
now supported in version >= 1.9.2.
