### ISSUE TITLE
Tip Labels cut off in facet_plot

### ISSUE THREAD

**Issue by mattbawn** [GuangchuangYu/ggtree#138]
![phages_tree](https://user-images.githubusercontent.com/7945506/27856522-581485d0-6166-11e7-806f-b44bb3267db9.png)

I have used `facet_plot` to make a figure with a tree and a `GRangesList` object using the following code-snippet:

    p1 <- ggtree(tree) + geom_tiplab() + theme_tree() 
    p2 <- facet_plot(p1, 'alignment', t2, geom_alignment, inherit.aes=FALSE, mapping=aes(fill=phage, color=phage))

As you can see the tip labels are not fully shown. How may I rectify this?

**Comment by GuangchuangYu** [comment]
see <https://guangchuangyu.github.io/2016/10/xlim_tree-set-x-axis-limits-for-only-tree-panel/>.

Remember to checkout the [document](https://guangchuangyu.github.io/ggtree/documentation/) page before posting question.

**Comment by mattbawn** [comment]
Thank you. Sorry for that. This does improve the spacing but moves the tree to the left panel.

**Comment by david-priest** [comment]
This is not really a robust solution when one has many different trees to plot with different lengths.  Is there a better solution by now?

**Comment by tallnuttrbgv** [comment]
This is still a problem. I tried the +xlim_tree(n) solution and it appeared to do nothing at all. Only getting about 9 characters of space for the tip labels.
