### ISSUE TITLE
collapse and geom_tiplab are incompatible

### ISSUE THREAD

**Issue by andersgs** [GuangchuangYu/ggtree#14]
Here is some example code:

>tree <- read.tree(system.file("extdata", "sample.nwk", package="ggtree"))
>cp <- ggtree(tree) + geom_tiplab()
>cp
>cp <- cp %>% collapse(node=21)
>cp

It leads to the following errors:

>Error in unit(x, default.units) : 'x' and 'units' must have length > 0
>In addition: Warning messages:
>1: Removed 4 rows containing missing values (geom_segment). 
>2: Removed 4 rows containing missing values (geom_segment). 
>3: Removed 14 rows containing missing values (geom_text). 

And, no tree is printed. I think that by default the behaviour should be to print out the remaining labels, attached to uncollapsed tips.

I am using ggtree version 1.0.20.

Thank you.

Anders.

**Comment by GuangchuangYu** [comment]
thanks for reporting this issue and it has been fixed, see [https://github.com/GuangchuangYu/ggtree/commit/ea9d66164c93c639ea6989a4bc693760059cfdae](https://github.com/GuangchuangYu/ggtree/commit/ea9d66164c93c639ea6989a4bc693760059cfdae).

**Comment by andersgs** [comment]
Thank you. Much appreciated. Anders.
