### ISSUE TITLE
Feature requests allow rotation of an open tree

### ISSUE THREAD

**Issue by ferroao** [GuangchuangYu/ggtree#141]
allow rotation of an open tree, for example:
set.seed(123)
tr = rtree(50)
p <- ggtree(tr, layout='circular') + geom_tiplab2()
  open_tree(p, angle=180) + ggtitle(paste("open angle:", 180))#+ rotate_tree(p,-90)

Be able to see p in a "vertical" orientation, which is, 90 degrees in relation to the current p.

**Comment by GuangchuangYu** [comment]
```r
p <- open_tree(p, angle=180) + ggtitle(paste("open angle:", 180))
rotate_tree(p,-90)
```

**Comment by ferroao** [comment]
As you saw, I already "knew" how to do it. so i read yes. the problem was that all in all my previous experience with ggplot, parameters were added with + always... so in this case this is not possible, which is very unusual for someone expecting a ggplot behaviour:
"Error: Don't know how to add o to a plot"

**Comment by GuangchuangYu** [comment]
`+` is used to add a layer, but functions like `open_tree` and `rotate_tree` are not used to **add** layer but manipulating the tree visually. You should use function call for these functions.

Always refer to documents.
