### ISSUE TITLE
Error labeling by tip ID when adding additional data to tree

### ISSUE THREAD

**Issue by nickp60** [GuangchuangYu/ggtree#143]
### Prerequisites

+ [X] Have you read [Feedback](https://guangchuangyu.github.io/ggtree/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [X] make sure your are using the latest release version
	* [X] read the [documents](https://guangchuangyu.github.io/ggtree/documentation/)
	* [X] google your quesion/issue

### Describe you issue

* [X] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [X] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [X] for bugs or feature requests, post here (github issue)
* [ ] for questions, please post to [google group](https://groups.google.com/forum/#!forum/bioc-ggtree)

Hi, 
I am attempting to add new annotation data to a tree using the `%<+%` operator.  It appears that I cant use the first column (the one matching the tip labels, as per the documentation) as labels after chaining.  

Some sample data

    set.seed(27)
    tree <- rtree(n = 20)
    labdf <- data.frame(
        name=tree$tip.label, value=runif(n = 20, min = 1, max = 100), id=gsub("t", "T_", tree$tip.label))

This call works:

    ggtree(tree) %<+% labdf + geom_tiplab(aes(label=id))

But the one below does not, giving me a `Error in eval(expr, envir, enclos) : object 'name' not found` error

    ggtree(tree) %<+% labdf + geom_tiplab(aes(label=name))

So, the error can be avoided by just duplicating the labeling column. Is this behavior intended? This very well could be by design; if so, could you tell me the most idiomatic way to add labels (ie, before attaching new data or after)?  

I'm using ggtree 1.6.11.

Thanks in advance!

**Comment by GuangchuangYu** [comment]
Did you really check prerequisites?

+ [X] Have you read [Feedback](https://guangchuangyu.github.io/ggtree/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [X] make sure your are using the latest release version

You are using out-dated version and I can't reproduce your issue using current release version.

**Comment by nickp60** [comment]
Sorry about that!  `biocLite("ggtree")` kept grabbing version 1.6.11 for me - I need to update my index! Thanks for your reply, and again, apologies!
