### ISSUE TITLE
Feature request: ancestral states in edges and singleton support

### ISSUE THREAD

**Issue by ferroao** [GuangchuangYu/ggtree#147]
Hi, I would like to request support for ancestral continuous states, that is, plotted in edges, as in:
http://www.phytools.org/eqg2015/asr.html  #Second plot:
   require(phytools)
   anole.tree<-read.tree("http://www.phytools.org/eqg2015/data/anole.tre")
   svl<-read.csv("http://www.phytools.org/eqg2015/data/svl.csv",       row.names=1)
   svl<-as.matrix(svl)[,1]
   obj<-contMap(anole.tree,svl,plot=FALSE)
   plot(obj,type="fan",legend=0.7*max(nodeHeights(anole.tree)),  fsize=c(0.7,0.9))

I was not sure if I should open a new feature request or add this here, but I decide to add it here:
When you are plotting ancestral states, there are cases in which singletons are necessary, see for ex:
http://blog.phytools.org/2013/09/convert-tree-with-mapped-character-to.html

  tree<-pbtree(n=40,scale=1)
  Q<-matrix(c(-2,1,1,1,-2,1,1,1,-2),3,3)
  colnames(Q)<-rownames(Q)<-letters[1:3]
  tree<-sim.history(tree,Q,anc="a")
  plotSimmap(tree,lwd=2,pts=TRUE) 
  singles<-map.to.singleton(tree)
  plotTree.singletons(singles) # like this

So I would like to make something similar in ggtree. thx

**Comment by brj1** [comment]
This would be solved with the addition of #122

**Comment by sdwfrost** [comment]
+1 on this!

**Comment by KlausVigo** [comment]
Hi @ferroao and @GuangchuangYu, 
the singleton support is now possible as @emmanuelparadis and I included this in ape 5.0:   
```
library(ape)  # requires ape 5.0
library(ggtree)
tree <- rtree(20)
tree <- drop.tip(tree, sample(20, 10), collapse.singles = FALSE)
ggtree(tree) + geom_nodepoint()
```

**Comment by GuangchuangYu** [comment]
thanks @KlausVigo

**Comment by orlinst** [comment]
Is this feature available now? Can I plot the ancestral estimates with ggtree as a gradient (using, say the object from contMap?)

**Comment by GuangchuangYu** [comment]
@orlinst @sdwfrost @ferroao @KlausVigo Thanks for keep reminding me on this. 

It is now supported in `github` version of `ggtree`, see example on <https://yulab-smu.github.io/treedata-book/chapter4.html#color-tree>.

**Comment by orlinst** [comment]
Still getting an error when reaching the dplyr::full_join

Error in UseMethod("full_join") :   no applicable method for 'full_join' applied to an object of class "phylo"

Also, the node numbers in 'phylo' are stored in 'node.label' and not in 'node' as you mention throughtout the example.

**Comment by GuangchuangYu** [comment]
github version of `treeio` is wanted.

**Comment by lfaino** [comment]
Dear @GuangchuangYu ,
i have the https://github.com/YuLab-SMU/ggtree/issues/147#issuecomment-505673339 error. 
how can i solve it?

cheers
Luigi

**Comment by brj1** [comment]
@lfaino Try updating to the latest version of ggtree.

```R
update.packages(ask=FALSE)
BiocManager::install("ggtree")
```

**Comment by KlausVigo** [comment]
@lfaino you may also want to check that you have a recent version of R installed.

**Comment by lfaino** [comment]
@KlausVigo  I tried but it is not working

here some additional info

`R version 3.6.2 (2019-12-12)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3          rstudioapi_0.10     magrittr_1.5        tidyselect_0.2.5    munsell_0.5.0       colorspace_1.4-1    ape_5.3             lattice_0.20-38    
 [9] R6_2.4.1            rlang_0.4.2         dplyr_0.8.3         tools_3.6.2         parallel_3.6.2      grid_3.6.2          ggtree_1.16.6       gtable_0.3.0       
[17] nlme_3.1-143        lazyeval_0.2.2      assertthat_0.2.1    tibble_2.1.3        lifecycle_0.1.0     crayon_1.3.4        treeio_1.8.2        tidyr_1.0.0        
[25] BiocManager_1.30.10 purrr_0.3.3         ggplot2_3.2.1       vctrs_0.2.1         zeallot_0.1.0       tidytree_0.3.1      glue_1.3.1          compiler_3.6.2     
[33] pillar_1.4.3        backports_1.1.5     rvcheck_0.1.7       scales_1.1.0        jsonlite_1.6        pkgconfig_2.0.3`

**Comment by brj1** [comment]
Your ggtree and treeio packages are both out of date. The current release version of ggtree is 2.0.1 and your version is 1.16.6. The current release version of treeio is 1.10.0 and your version is 1.8.2.

```R
BiocManager::install("treeio")
BiocManager::install("ggtree")
```
