### ISSUE TITLE
Midpoint rooting tree causes ggtree to fail, reporting multiple roots

### ISSUE THREAD

**Issue by davidhwyllie** [GuangchuangYu/ggtree#15]
After midpoint rooting a tree, ggtree fails, with the getRoot function (called from inside ggtree()) reporting 'multiple roots founded'.  

When called on the same tree from outside ggtree, getRoot only returns one root passed the same tree given to ggtree:

require(ape)
require(phangorn)
require(ggtree)

x<-rtree(10)  # a random tree; this  is handled correctly
getRoot(x) # correctly returns the root
ggtree(x) # succeeds

y<-midpoint(x)  #  midpoint root x, generating a new tree y using the phangorn midpoint rooting function
getRoot(y) # succeeds, returning one root
ggtree(y) # fails, reporting 'error in getRoot(tr) multiple roots founded (I think this should read 'found')

Is this a bug?

Thank you
David

**Comment by GuangchuangYu** [comment]
This should be a bug.

After my testing, it's not a bug of `ggtree`.

You can plot the tree successfully using `ggtree(y, ladderize=FALSE)`.

The issue is due to ggtree call `ape::ladderize()` and the output tree from `phangorn::midpoint()` is not compatible with `ape::ladderize()`.

```r
> y

Phylogenetic tree with 10 tips and 9 internal nodes.

Tip labels:
	t8, t1, t4, t6, t10, t3, ...

Rooted; includes branch lengths.
> y$edge
      [,1] [,2]
 [1,]   15    3
 [2,]   15    4
 [3,]   14    2
 [4,]   14   15
 [5,]   13   14
 [6,]   13    5
 [7,]   12   13
 [8,]   12    6
 [9,]   18    1
[10,]   18   12
[11,]   19    8
[12,]   19    9
[13,]   17   10
[14,]   17   19
[15,]   16    7
[16,]   16   17
[17,]   11   16
[18,]   11   18
> ladderize(y)

Phylogenetic tree with 10 tips and 9 internal nodes.

Tip labels:
	t8, t1, t4, t6, t10, t3, ...

Rooted; includes branch lengths.
> ladderize(y)$edge
      [,1] [,2]
 [1,]   11   18
 [2,]   18   12
 [3,]   16   17
 [4,]   17   19
 [5,]   19    8
 [6,]   19    9
 [7,]   15    4
 [8,]   17   10
 [9,]   18    1
```

The output from `ape::ladderize()` is not correct. We need to report this issue to the author of `ape` and `phangorn`.

**Comment by davidhwyllie** [comment]
Thank you very much for your reply.
Do you wish me to report this issue, or will you do so?
With all best wishes
David

**Comment by KlausVigo** [comment]
Dear Guangchuang & Emmanuel,

it seems ladderize assumes that trees are in "cladewise" order, but midpoint returns a tree in "postorder".

x<-rtree(10)
x2 <- reorder(x, "postorder")
plot(ladderize(x2))  # error message

y<-phangorn::midpoint(x)
y <- reorder(y)
plot(ladderize(y)) # works!!!

Just add 
tree <- reorder(tree)
before running ladderize.

Cheers,
Klaus

**Comment by GuangchuangYu** [comment]
Dear Klaus,

Thank you for your reply.

It's very clear. We just need to `reorder()` the tree before using `ggtree()`.

Thanks,
Guangchuang

**Comment by GuangchuangYu** [comment]
@davidhwyllie FYI, In r-sig-phylo mailing list, Emmanuel mentioned he will include `phy <- reorder(phy)` in `ladderize()`, so we don't need to call reorder explicitly in future release of `ape`.
