### ISSUE TITLE
Freshbird for help

### ISSUE THREAD

**Issue by y842739756** [GuangchuangYu/ggtree#153]
Mr.Y 
I got the RAxML outfile with format"NC" named "RAxML_bipartitionsBranchLabels.NC" ,and try to print a tree.
my code :  
> library(ggtree)
> raxml_file <- system.file("/data/yanxu_workfile/orthomcl/RAxML", "RAxML_bipartitionsBranchLabels.NC",package = "ggtree")
> read.raxml(raxml_file)

And report 
Error in UseMethod("as.phylo") : 
  no applicable method for 'as.phylo' applied to an object of class "NULL"
In addition: Warning messages:
1: In file(con, "r") :
  file("") only supports open = "w+" and open = "w+b": using the former
2: In read.tree(text = tree_text) : empty character string.

how to figure out this problem
please help me 
thanks

**Comment by GuangchuangYu** [comment]
DO NOT USE `system.file` for your own file.

**Comment by Echosusi2020** [comment]
Mr.Y,
I am a junior for learning ggtree.  I have a basic QA which need your help.

During reading your maniscript，you read the newick tree like
![image](https://user-images.githubusercontent.com/63213886/78513142-31309780-77dc-11ea-85c8-57bc51b5fd84.png)

so, what is system.file ? What is "extdata"? 


Thank you so much!
Best wishes. @GuangchuangYu
