### ISSUE TITLE
geom_text2 does not use the right environment when inside a function

### ISSUE THREAD

**Issue by brj1** [GuangchuangYu/ggtree#155]
Hello, I've been trying to the `geom_text2` method within another function in order to parametrize the subsetting. However, the subset method does not seem to be able to see the variables within the parent function. See the following example:

```R
library(ggtree)

my.function <- function(tree, tip) {
  ggtree(tree) + geom_text2(aes(subset=isTip & label %in% tip, label=label))
}

tree <- read.tree(text="((A, B),(C, D));")

my.function(tree, 'A')
```

which gives:
> Error in match(x, table, nomatch = 0L) : object 'tip' not found

I have found a work around for my particular issue by subsetting my data itself, but it seems to me that this is a bug in `geom_text2`. If this behaviour is expected feel free to close this issue.

**Comment by GuangchuangYu** [comment]
see the `use $ in aes` session in <https://guangchuangyu.github.io/ggtree/faq/>.
