### ISSUE TITLE
Add geom_rect() layer to ggtree()

### ISSUE THREAD

**Issue by radwaraed** [GuangchuangYu/ggtree#161]
I am trying to add a geom_rect() layer of aligned sequences to my ggtree but I am receiving an error that
    Error: Don't know how to add o to a plot

I have tried to match the order of the data in the two files and superimpose the two figures next to each other but since the height of the tree is different than the height of the geom_rect() layer, it didn't work well. Below I have provided some sample data.

![pid5_tree](https://user-images.githubusercontent.com/29765113/34502047-bf6e401a-efdf-11e7-94c4-06b840b5fa85.png)
![pid5_aligned](https://user-images.githubusercontent.com/29765113/34502049-c0f63596-efdf-11e7-8037-5c6f22075407.png)

> dput(tree)
structure(list(edge = structure(c(74L, 75L, 76L, 77L, 78L, 79L, 
80L, 81L, 82L, 83L, 84L, 85L, 86L, 87L, 87L, 86L, 85L, 84L, 83L, 
82L, 81L, 80L, 79L, 88L, 89L, 90L, 91L, 92L, 93L, 94L, 95L, 96L, 
97L, 97L, 96L, 95L, 94L, 93L, 92L, 91L, 90L, 89L, 88L, 78L, 77L, 
98L, 99L, 100L, 101L, 102L, 103L, 104L, 104L, 103L, 102L, 105L, 
106L, 107L, 108L, 109L, 110L, 111L, 112L, 113L, 113L, 112L, 111L, 
110L, 114L, 115L, 115L, 114L, 109L, 108L, 116L, 116L, 107L, 117L, 
118L, 118L, 117L, 119L, 119L, 106L, 105L, 120L, 120L, 121L, 121L, 
101L, 100L, 122L, 123L, 124L, 125L, 126L, 126L, 127L, 127L, 125L, 
124L, 123L, 128L, 128L, 122L, 99L, 98L, 129L, 130L, 131L, 131L, 
130L, 129L, 132L, 132L, 76L, 133L, 134L, 135L, 135L, 136L, 137L, 
137L, 136L, 134L, 133L, 138L, 138L, 75L, 139L, 140L, 141L, 141L, 
142L, 142L, 140L, 143L, 143L, 139L, 144L, 145L, 145L, 144L, 74L, 
75L, 76L, 77L, 78L, 79L, 80L, 81L, 82L, 83L, 84L, 85L, 86L, 87L, 
1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 88L, 89L, 90L, 91L, 92L, 
93L, 94L, 95L, 96L, 97L, 10L, 11L, 12L, 13L, 14L, 15L, 16L, 17L, 
18L, 19L, 20L, 21L, 98L, 99L, 100L, 101L, 102L, 103L, 104L, 22L, 
23L, 24L, 105L, 106L, 107L, 108L, 109L, 110L, 111L, 112L, 113L, 
25L, 26L, 27L, 28L, 114L, 115L, 29L, 30L, 31L, 32L, 116L, 33L, 
34L, 117L, 118L, 35L, 36L, 119L, 37L, 38L, 39L, 120L, 40L, 121L, 
41L, 42L, 43L, 122L, 123L, 124L, 125L, 126L, 44L, 127L, 45L, 
46L, 47L, 48L, 128L, 49L, 50L, 51L, 52L, 129L, 130L, 131L, 53L, 
54L, 55L, 132L, 56L, 57L, 133L, 134L, 135L, 58L, 136L, 137L, 
59L, 60L, 61L, 62L, 138L, 63L, 64L, 139L, 140L, 141L, 65L, 142L, 
66L, 67L, 143L, 68L, 69L, 144L, 145L, 70L, 71L, 72L, 73L), .Dim = c(144L, 
2L)), edge.length = c(0.201402, 0.185763, 0.0857018, 0.0278477, 
0.000353577, 0.000277316, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0.000277316, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0.000353577, 0.0278477, 0.0266469, 0.0248536, 
0.0212055, 0.0166212, 0.0107618, 0.00815391, 0.0044843, 0.0044843, 
0.00815391, 0.0107618, 0.0104357, 0.00922906, 0.00718061, 0.00548857, 
0.00220303, 0.0016746, 5.78704e-05, 0, 0, 0, 0, 5.78704e-05, 
0.0016746, 0, 0, 0, 0, 0.00220303, 0.00548857, 0, 0, 0.00718061, 
0.00649059, 0.00521477, 0.00521477, 0.00649059, 0.00409417, 0.00409417, 
0.00922906, 0.0104357, 0.00824256, 0.00824256, 0.0075393, 0.0075393, 
0.0166212, 0.0212055, 0.017578, 0.0165722, 0.015633, 0.0135457, 
0.0131126, 0.0131126, 0.00921187, 0.00921187, 0.0135457, 0.015633, 
0.0165722, 0, 0, 0.017578, 0.0248536, 0.0266469, 0.0107894, 0.00624355, 
0, 0, 0.00624355, 0.0107894, 0.00200218, 0.00200218, 0.0857018, 
0.0414419, 0.0099278, 0.000906618, 0.000906618, 0, 0, 0, 0, 0.0099278, 
0.0414419, 0.0151515, 0.0151515, 0.185763, 0.159774, 0.0413872, 
0.000135648, 0.000135648, 0, 0, 0.0413872, 0.0214286, 0.0214286, 
0.159774, 0, 0, 0, 0, 0.201402), Nnode = 72L, tip.label = c("deletionandhypermutR0080_HIV_AG8_CONTIG_1202_p1", 
"deletionandhypermutR0251_HIV_BE12_CONTIG_1202_p1", "deletionandhypermutR0252_HIV_BF1_CONTIG_1202_p1", 
"deletionandhypermutR0253_HIV_BF2_CONTIG_1202_p1", "deletionandhypermutR0254_HIV_BF3_CONTIG_1202_p1", 
"deletionandhypermutR0258_HIV_BF7_CONTIG_1202_p1", "deletionandhypermutR0105_HIV_AA9_CONTIG_1201_p1", 
"deletionandhypermutR0268_HIV_BG5_CONTIG_1201_p1", "deletionandhypermutR0273_HIV_BG10_CONTIG_1201_p1", 
"deletionandhypermutR0130_HIV_AC10_CONTIG_1202_p1", "deletionandhypermutR0231_HIV_BD4_CONTIG_1202_p1", 
"deletionandhypermutR0233_HIV_BD6_CONTIG_1202_p1", "deletionandhypermutR0234_HIV_BD7_CONTIG_1202_p1", 
"deletionandhypermutR0235_HIV_BD8_CONTIG_1202_p1", "deletionandhypermutR0236_HIV_BD9_CONTIG_1202_p1", 
"deletionandhypermutR0242_HIV_BE3_CONTIG_1202_p1", "deletionandhypermutR0244_HIV_BE5_CONTIG_1202_p1", 
"deletionandhypermutR0257_HIV_BF6_CONTIG_1202_p1", "deletionandhypermutR0265_HIV_BG2_CONTIG_1202_p1", 
"deletionandhypermutR0276_HIV_BH1_CONTIG_1202_p1", "deletionandhypermutR0239_HIV_BD12_CONTIG_1202_p1", 
"LargedeletionR0247_HIV_BE8_CONTIG_794_p1", "deletionandhypermutR0116_HIV_AB8_CONTIG_4375_p1", 
"LargedeletionR0129_HIV_AC9_CONTIG_888_p1", "LargedeletionR0272_HIV_BG9_CONTIG_303_p1", 
"LargedeletionB11_Cp35pt5_1sampleC9_CB11_CONTIG_4324_p1", "LargedeletionR0256_HIV_BF5_CONTIG_1153_p1", 
"LargedeletionR0246_HIV_BE7_CONTIG_2881_p1", "LargedeletionR0275_HIV_BG12_CONTIG_350_p1", 
"LargedeletionR0243_HIV_BE4_CONTIG_1371_p1", "LargedeletionF3_Cp34pt5_1sampleB4_CF3_CONTIG_1042_p1", 
"LargedeletionR0241_HIV_BE2_CONTIG_1086_p1", "deletionandinversionR0175_HIV_AG7_CONTIG_1888_p1", 
"LargedeletionR0271_HIV_BG8_CONTIG_1486_p1", "LargedeletionB9_Cp35pt5_1sampleC6_CB9_CONTIG_7287_p1", 
"IntactR0176_HIV_AG8_CONTIG_9004_p1", "LargedeletionR0101_HIV_AA5_CONTIG_2639_p1", 
"LargedeletionR0269_HIV_BG6_CONTIG_978_p1", "LargedeletionR0267_HIV_BG4_CONTIG_351_p1", 
"deletionandhypermutR0102_HIV_AA6_CONTIG_3034_p1", "LargedeletionR0100_HIV_AA4_CONTIG_5077_p1", 
"LargedeletionR0260_HIV_BF9_CONTIG_3119_p1", "HypermutB7_Cp35pt5_1sampleC2_AE11_CONTIG_9004_p1", 
"HypermutR0201_HIV_BA10_CONTIG_9020_p1", "HypermutB5_Cp35pt5_1sampleA10_CB5_CONTIG_9019_p1", 
"deletionandhypermutR0248_HIV_BE9_CONTIG_1956_p1", "HypermutB12_Cp35pt5_1sampleE2_CB12_CONTIG_9019_p1", 
"HypermutC3_Cp35pt5_1sampleF5_CC3_CONTIG_9010_p1", "HypermutR0126_HIV_AC6_CONTIG_9019_p1", 
"HypermutR0135_HIV_AD3_CONTIG_9019_p1", "HypermutB10_Cp35pt5_1sampleC8_CB10_CONTIG_9019_p1", 
"deletionandhypermutR0240_HIV_BE1_CONTIG_1151_p1", "LargedeletionR0099_HIV_AA3_CONTIG_775_p1", 
"LargedeletionR0106_HIV_AA10_CONTIG_5882_p1", "LargedeletionR0127_HIV_AC7_CONTIG_6333_p1", 
"LargedeletionR0103_HIV_AA7_CONTIG_6233_p1", "LargedeletionR0274_HIV_BG11_CONTIG_2748_p1", 
"deletionandinversionR0177_HIV_AG9_CONTIG_1103_p1", "deletionandinversionR0259_HIV_BF8_CONTIG_1103_p1", 
"deletionandinversionR0261_HIV_BF10_CONTIG_1103_p1", "deletionandinversionR0270_HIV_BG7_CONTIG_1103_p1", 
"LargedeletionC4_Cp35pt5_1sampleG8_CC4_CONTIG_277_p1", "LargedeletionR0266_HIV_BG3_CONTIG_437_p1", 
"deletionandinversionR0255_HIV_BF4_CONTIG_1124_p1", "deletionandinversionR0232_HIV_BD5_CONTIG_3686_p1", 
"deletionandinversionR0238_HIV_BD11_CONTIG_3686_p1", "deletionandinversionR0262_HIV_BF11_CONTIG_3686_p1", 
"deletionandinversionR0263_HIV_BF12_CONTIG_1124_p1", "deletionandinversionR0104_HIV_AA8_CONTIG_1155_p1", 
"deletionandinversionB6_Cp35pt5_1sampleB8_CB6_CONTIG_1103_p1", 
"deletionandinversionR0245_HIV_BE6_CONTIG_1103_p1", "deletionandinversionR0079_HIV_AG7_CONTIG_1117_p1", 
"deletionandinversionB8_Cp35pt5_1sampleC5_CB8_CONTIG_6627_p1"
), root.edge = 0.201402), .Names = c("edge", "edge.length", "Nnode", 
"tip.label", "root.edge"), class = "phylo", order = "cladewise")

> dput(sequences)
structure(list(Seqname = structure(c(1L, 1L, 1L, 1L, 1L, 2L, 
3L, 4L, 4L, 4L, 4L, 4L, 5L, 5L, 6L, 7L, 7L, 7L, 8L, 8L, 9L, 10L, 
10L, 11L, 11L, 12L, 12L, 12L, 12L, 12L, 12L, 13L, 13L, 13L, 13L, 
13L, 13L, 13L, 13L, 14L, 14L, 14L, 14L, 14L, 14L, 14L, 14L, 14L, 
14L, 15L, 15L, 15L, 16L, 17L, 18L, 18L, 19L, 19L, 20L, 21L, 21L, 
21L, 21L, 21L, 21L, 22L, 22L, 22L, 22L, 22L, 22L, 22L, 22L, 22L, 
22L, 23L, 23L, 23L, 23L, 23L, 23L, 23L, 23L, 23L, 23L, 24L, 24L, 
24L, 24L, 24L, 24L, 24L, 24L, 24L, 24L, 25L, 25L, 26L, 26L, 26L, 
26L, 26L, 26L, 26L, 26L, 26L, 26L, 27L, 27L, 27L, 27L, 27L, 27L, 
27L, 27L, 27L, 27L, 28L, 28L, 28L, 28L, 28L, 28L, 28L, 28L, 28L, 
28L, 29L, 29L, 29L, 29L, 29L, 29L, 29L, 29L, 29L, 29L, 30L, 30L, 
30L, 30L, 30L, 30L, 30L, 30L, 30L, 30L, 31L, 31L, 32L, 32L, 33L, 
33L, 34L, 34L, 35L, 35L, 36L, 36L, 37L, 37L, 38L, 38L, 39L, 39L, 
40L, 40L, 41L, 41L, 42L, 42L, 43L, 43L, 44L, 44L, 45L, 45L, 46L, 
46L, 47L, 47L, 48L, 48L, 49L, 49L, 50L, 50L, 51L, 51L, 52L, 52L, 
53L, 53L, 53L, 53L, 53L, 53L, 53L, 54L, 54L, 54L, 55L, 55L, 55L, 
55L, 55L, 55L, 55L, 56L, 56L, 56L, 56L, 57L, 57L, 57L, 57L, 58L, 
58L, 59L, 59L, 60L, 60L, 61L, 61L, 62L, 63L, 64L, 64L, 65L, 65L, 
66L, 66L, 67L, 67L, 67L, 67L, 68L, 68L, 68L, 68L, 69L, 69L, 69L, 
69L, 70L, 70L, 71L, 71L, 72L, 72L, 73L, 73L, 73L, 73L, 73L, 73L, 
73L), .Label = c("deletionandhypermutR0116_HIV_AB8_CONTIG_4375_p1", 
"LargedeletionR0247_HIV_BE8_CONTIG_794_p1", "LargedeletionR0129_HIV_AC9_CONTIG_888_p1", 
"LargedeletionB11_Cp35pt5_1sampleC9_CB11_CONTIG_4324_p1", "LargedeletionR0256_HIV_BF5_CONTIG_1153_p1", 
"LargedeletionR0272_HIV_BG9_CONTIG_303_p1", "LargedeletionR0246_HIV_BE7_CONTIG_2881_p1", 
"LargedeletionR0243_HIV_BE4_CONTIG_1371_p1", "LargedeletionR0275_HIV_BG12_CONTIG_350_p1", 
"LargedeletionF3_Cp34pt5_1sampleB4_CF3_CONTIG_1042_p1", "LargedeletionR0241_HIV_BE2_CONTIG_1086_p1", 
"LargedeletionR0100_HIV_AA4_CONTIG_5077_p1", "LargedeletionB9_Cp35pt5_1sampleC6_CB9_CONTIG_7287_p1", 
"IntactR0176_HIV_AG8_CONTIG_9004_p1", "LargedeletionR0101_HIV_AA5_CONTIG_2639_p1", 
"LargedeletionR0269_HIV_BG6_CONTIG_978_p1", "LargedeletionR0267_HIV_BG4_CONTIG_351_p1", 
"deletionandinversionR0175_HIV_AG7_CONTIG_1888_p1", "LargedeletionR0271_HIV_BG8_CONTIG_1486_p1", 
"LargedeletionR0099_HIV_AA3_CONTIG_775_p1", "LargedeletionR0106_HIV_AA10_CONTIG_5882_p1", 
"HypermutB7_Cp35pt5_1sampleC2_AE11_CONTIG_9004_p1", "HypermutR0201_HIV_BA10_CONTIG_9020_p1", 
"HypermutB5_Cp35pt5_1sampleA10_CB5_CONTIG_9019_p1", "deletionandhypermutR0248_HIV_BE9_CONTIG_1956_p1", 
"HypermutB12_Cp35pt5_1sampleE2_CB12_CONTIG_9019_p1", "HypermutC3_Cp35pt5_1sampleF5_CC3_CONTIG_9010_p1", 
"HypermutR0126_HIV_AC6_CONTIG_9019_p1", "HypermutR0135_HIV_AD3_CONTIG_9019_p1", 
"HypermutB10_Cp35pt5_1sampleC8_CB10_CONTIG_9019_p1", "deletionandhypermutR0240_HIV_BE1_CONTIG_1151_p1", 
"deletionandhypermutR0080_HIV_AG8_CONTIG_1202_p1", "deletionandhypermutR0251_HIV_BE12_CONTIG_1202_p1", 
"deletionandhypermutR0252_HIV_BF1_CONTIG_1202_p1", "deletionandhypermutR0253_HIV_BF2_CONTIG_1202_p1", 
"deletionandhypermutR0254_HIV_BF3_CONTIG_1202_p1", "deletionandhypermutR0258_HIV_BF7_CONTIG_1202_p1", 
"deletionandhypermutR0105_HIV_AA9_CONTIG_1201_p1", "deletionandhypermutR0268_HIV_BG5_CONTIG_1201_p1", 
"deletionandhypermutR0273_HIV_BG10_CONTIG_1201_p1", "deletionandhypermutR0130_HIV_AC10_CONTIG_1202_p1", 
"deletionandhypermutR0231_HIV_BD4_CONTIG_1202_p1", "deletionandhypermutR0233_HIV_BD6_CONTIG_1202_p1", 
"deletionandhypermutR0234_HIV_BD7_CONTIG_1202_p1", "deletionandhypermutR0235_HIV_BD8_CONTIG_1202_p1", 
"deletionandhypermutR0236_HIV_BD9_CONTIG_1202_p1", "deletionandhypermutR0242_HIV_BE3_CONTIG_1202_p1", 
"deletionandhypermutR0244_HIV_BE5_CONTIG_1202_p1", "deletionandhypermutR0257_HIV_BF6_CONTIG_1202_p1", 
"deletionandhypermutR0265_HIV_BG2_CONTIG_1202_p1", "deletionandhypermutR0276_HIV_BH1_CONTIG_1202_p1", 
"deletionandhypermutR0239_HIV_BD12_CONTIG_1202_p1", "LargedeletionR0103_HIV_AA7_CONTIG_6233_p1", 
"LargedeletionR0274_HIV_BG11_CONTIG_2748_p1", "LargedeletionR0127_HIV_AC7_CONTIG_6333_p1", 
"deletionandhypermutR0102_HIV_AA6_CONTIG_3034_p1", "LargedeletionR0260_HIV_BF9_CONTIG_3119_p1", 
"deletionandinversionR0177_HIV_AG9_CONTIG_1103_p1", "deletionandinversionR0259_HIV_BF8_CONTIG_1103_p1", 
"deletionandinversionR0261_HIV_BF10_CONTIG_1103_p1", "deletionandinversionR0270_HIV_BG7_CONTIG_1103_p1", 
"LargedeletionC4_Cp35pt5_1sampleG8_CC4_CONTIG_277_p1", "LargedeletionR0266_HIV_BG3_CONTIG_437_p1", 
"deletionandinversionR0255_HIV_BF4_CONTIG_1124_p1", "deletionandinversionR0104_HIV_AA8_CONTIG_1155_p1", 
"deletionandinversionR0263_HIV_BF12_CONTIG_1124_p1", "deletionandinversionR0232_HIV_BD5_CONTIG_3686_p1", 
"deletionandinversionR0238_HIV_BD11_CONTIG_3686_p1", "deletionandinversionR0262_HIV_BF11_CONTIG_3686_p1", 
"deletionandinversionB6_Cp35pt5_1sampleB8_CB6_CONTIG_1103_p1", 
"deletionandinversionR0245_HIV_BE6_CONTIG_1103_p1", "deletionandinversionR0079_HIV_AG7_CONTIG_1117_p1", 
"deletionandinversionB8_Cp35pt5_1sampleC5_CB8_CONTIG_6627_p1"
), class = "factor"), Start = c(638L, 1638L, 2638L, 3638L, 4638L, 
8845L, 637L, 638L, 1638L, 2638L, 3638L, 4638L, 637L, 9483L, 9316L, 
637L, 1637L, 2637L, 637L, 1637L, 9290L, 8615L, 9592L, 8567L, 
9548L, 638L, 1638L, 2638L, 3638L, 4638L, 9556L, 638L, 1638L, 
2638L, 3638L, 6359L, 7353L, 8359L, 9347L, 638L, 1638L, 2638L, 
3638L, 4638L, 5638L, 6627L, 7639L, 8642L, 9219L, 637L, 8021L, 
8995L, 637L, 637L, 637L, 7010L, 8166L, 9149L, 8858L, 3759L, 4761L, 
5761L, 6759L, 7765L, 8765L, 638L, 1638L, 2638L, 3638L, 4638L, 
5638L, 6630L, 7639L, 8642L, 9219L, 638L, 1638L, 2638L, 3638L, 
4638L, 5638L, 6618L, 7624L, 8627L, 9614L, 638L, 1638L, 2638L, 
3638L, 4638L, 5638L, 6618L, 7624L, 8627L, 9614L, 637L, 9086L, 
638L, 1638L, 2638L, 3638L, 4638L, 5638L, 6618L, 7624L, 8627L, 
9614L, 638L, 1638L, 2638L, 3638L, 4638L, 5638L, 6627L, 7633L, 
8636L, 9623L, 638L, 1638L, 2638L, 3638L, 4638L, 5638L, 6618L, 
7624L, 8627L, 9614L, 638L, 1638L, 2638L, 3638L, 4638L, 5638L, 
6618L, 7624L, 8627L, 9614L, 638L, 1638L, 2638L, 3638L, 4638L, 
5638L, 6618L, 7624L, 8627L, 9614L, 8506L, 9483L, 637L, 9433L, 
637L, 9433L, 637L, 9433L, 637L, 9433L, 637L, 9433L, 637L, 9433L, 
637L, 9433L, 637L, 9433L, 637L, 9433L, 637L, 9433L, 637L, 9433L, 
637L, 9433L, 637L, 9433L, 637L, 9433L, 637L, 9433L, 637L, 9433L, 
637L, 9433L, 637L, 9433L, 637L, 9433L, 637L, 9433L, 637L, 9433L, 
1620L, 4424L, 5424L, 6431L, 7422L, 8413L, 9401L, 6904L, 7898L, 
8886L, 3312L, 4308L, 5308L, 6315L, 7309L, 8315L, 9303L, 637L, 
1637L, 2637L, 9599L, 637L, 1637L, 2637L, 9521L, 1L, 9531L, 1L, 
9531L, 1L, 9531L, 1L, 9531L, 637L, 637L, 5116L, 4993L, 1242L, 
3982L, 4993L, 637L, 3313L, 4308L, 5308L, 637L, 3308L, 4308L, 
5308L, 637L, 3308L, 4308L, 5308L, 637L, 1L, 637L, 1L, 637L, 1L, 
623L, 8646L, 7643L, 6637L, 5657L, 4657L, 3657L, 9086L), End = c(1637L, 
2637L, 3637L, 4637L, 5005L, 9633L, 1542L, 1637L, 2637L, 3637L, 
4637L, 4964L, 1636L, 9633L, 9633L, 1636L, 2636L, 3511L, 1636L, 
2000L, 9633L, 9591L, 9633L, 9547L, 9633L, 1637L, 2637L, 3637L, 
4637L, 5629L, 9632L, 1637L, 2637L, 3637L, 4622L, 7352L, 8358L, 
9346L, 9632L, 1637L, 2637L, 3637L, 4637L, 5637L, 6644L, 7638L, 
8641L, 9628L, 9222L, 1636L, 8994L, 9632L, 1605L, 980L, 1636L, 
7898L, 9148L, 9633L, 9633L, 4760L, 5760L, 6758L, 7761L, 8764L, 
9633L, 1637L, 2637L, 3637L, 4637L, 5637L, 6644L, 7638L, 8641L, 
9628L, 9222L, 1637L, 2637L, 3637L, 4637L, 5637L, 6644L, 7637L, 
8626L, 9613L, 9633L, 1637L, 2637L, 3637L, 4637L, 5637L, 6644L, 
7637L, 8626L, 9613L, 9632L, 1636L, 9633L, 1637L, 2637L, 3637L, 
4637L, 5637L, 6644L, 7637L, 8626L, 9613L, 9632L, 1637L, 2637L, 
3637L, 4637L, 5637L, 6644L, 7632L, 8635L, 9622L, 9632L, 1637L, 
2637L, 3637L, 4637L, 5637L, 6644L, 7637L, 8626L, 9613L, 9632L, 
1637L, 2637L, 3637L, 4637L, 5637L, 6644L, 7637L, 8626L, 9613L, 
9632L, 1637L, 2637L, 3637L, 4637L, 5637L, 6644L, 7637L, 8626L, 
9613L, 9632L, 9482L, 9633L, 1639L, 9633L, 1639L, 9633L, 1639L, 
9633L, 1639L, 9633L, 1639L, 9633L, 1639L, 9633L, 1639L, 9632L, 
1639L, 9632L, 1639L, 9632L, 1639L, 9633L, 1639L, 9633L, 1639L, 
9633L, 1639L, 9633L, 1639L, 9633L, 1639L, 9633L, 1639L, 9633L, 
1639L, 9633L, 1639L, 9633L, 1639L, 9633L, 1639L, 9633L, 1639L, 
9633L, 2631L, 5423L, 6430L, 7412L, 8412L, 9400L, 9632L, 7897L, 
8885L, 9632L, 4307L, 5307L, 6314L, 7308L, 8314L, 9302L, 9633L, 
1636L, 2636L, 3649L, 9632L, 1636L, 2636L, 3636L, 9633L, 798L, 
9633L, 798L, 9633L, 798L, 9633L, 798L, 9633L, 900L, 1077L, 6132L, 
5115L, 2218L, 4126L, 6011L, 760L, 4307L, 5307L, 6265L, 1322L, 
4307L, 5307L, 6265L, 1322L, 4307L, 5307L, 6265L, 1322L, 698L, 
739L, 698L, 739L, 698L, 739L, 9632L, 8645L, 7642L, 6668L, 5656L, 
4656L, 9632L), Type = structure(c(1L, 1L, 1L, 1L, 1L, 5L, 5L, 
5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 5L, 5L, 5L, 5L, 5L, 2L, 
2L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 3L, 3L, 3L, 3L, 3L, 3L, 
3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 1L, 1L, 3L, 3L, 3L, 3L, 3L, 3L, 
3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 1L, 1L, 1L, 1L, 5L, 5L, 5L, 
5L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 5L, 5L, 2L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L), .Label = c("Deletion and hypermut", 
"Deletion and inversion", "Hypermut", "Intact", "Large deletion"
), class = "factor")), class = "data.frame", .Names = c("Seqname", 
"Start", "End", "Type"), row.names = c(NA, -257L))

Would love to hear your insight! Many thanks :)

**Comment by GuangchuangYu** [comment]
any source code to [reproduce the issue](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?

**Comment by radwaraed** [comment]
Sure. 

For the alignment:
library(forcats)
df %>% mutate(Seqname=forcats::fct_inorder(Seqname)) %>% ggplot()+geom_rect(aes(ymin = 0, ymax = 1, xmin = Start, xmax = End, fill = Type))+facet_grid(Seqname ~ .)+theme(axis.text.y = element_blank(),axis.ticks.y = element_blank(),strip.text.y = element_text())

For the tree:
tree<-read.tree("tree.tre")
ggtree(tree)

Many thanks for looking into this!

**Comment by GuangchuangYu** [comment]
The following code will generate a taxa name vector in the order of tree view from top to bottom.

```r
p <- ggtree(tree)
get_taxa_name(p)
```

You can then set the `Seqname` level according to it to visualize the alignment.

**Comment by radwaraed** [comment]
Thanks Guangchuang. That worked very well. I exported both images separately (the tree and the alignment) then superimposed them onto each other. It looks good, but I wonder if there is a way to visualize both on the same plot without manually adjusting the images. Is there perhaps a functionality to do that? Thank you!

 
![pid5](https://user-images.githubusercontent.com/29765113/34527014-17c8ca18-f072-11e7-8ce4-703f2eb7f87f.png)

**Comment by GuangchuangYu** [comment]
take a look at [cowplot](https://cran.r-project.org/web/packages/cowplot/) or [patchwork](https://github.com/thomasp85/patchwork) packages.
