### ISSUE TITLE
Non-standard mrsd dating

### ISSUE THREAD

**Issue by rifebd88** [GuangchuangYu/ggtree#164]
This is not so much an issue but a question. When specifying the mrsd, what do I do if my data are in non-standard date format, for example - days post-infection? I know that I could specify the origin instead, but is there an easier way of bypassing the standard date format for mrsd without knowing the height of the tree to specify the origin? In other words, if I know my mrsd is 463 days post-infection and that my origin is -100 days (and I'm looking at 50 different trees), I'd rather specify the known mrsd of 463. I just wasn't sure how to inform the package that I am not specifying a date.

**Comment by GuangchuangYu** [comment]
maybe you can look into <https://bioconductor.org/packages/devel/bioc/vignettes/ggtree/inst/doc/treeVisualization.html#rescale-tree>.

**Comment by rifebd88** [comment]
This still wouldn’t be what I am looking for because even if you scale branch.length to ‘length’ it is the same as specifying an origin of 0, but my origin is not zero due to the pre-transmission interval. Is there another way to specify a numeric argument instead of a date as the mrsd?

--
Brittany Rife Magalis, PhD
Postdoctoral Fellow, Temple University
Email: Brittany.magalis@temple.edu<mailto:Brittany.magalis@temple.edu>
Phone: +1 (540) 383-1395

**Comment by GuangchuangYu** [comment]
```r
p = ggtree(x)
p$data$x = p$data$x - max(p$data$x) + 463
p + theme_tree2()
```

**Comment by rifebd88** [comment]
That worked wonderfully. I was trying to do something very similar, but I just couldn’t figure out where to find those values. Thank you so much for all your help!
--
Brittany Rife Magalis, PhD
Postdoctoral Fellow, Temple University
Email: Brittany.magalis@temple.edu<mailto:Brittany.magalis@temple.edu>
Phone: +1 (540) 383-1395

**Comment by rifebd88** [comment]
Dr. Yu,

I also have a bit of a complicated question for you now that I’ve discovered your fantastic package. Say I have a tree with a mix of sequences from different locations, and I wanted to show a mirrored tree in the same figure of just sequences from a single one of those locations with lines connecting the taxa from the two trees (see my crude attached illustration). Is this possible in ggtree?

Thank you for your time?

--
Brittany Rife Magalis, PhD
Postdoctoral Fellow, Temple University
Email: Brittany.magalis@temple.edu<mailto:Brittany.magalis@temple.edu>
Phone: +1 (540) 383-1395

**Comment by GuangchuangYu** [comment]
[tanglegram](https://www.rdocumentation.org/packages/dendextend/versions/1.6.0/topics/tanglegram) is currently not supported. You may take a look at `dendextend` package.

BTW: you can subscribe to [ggtree mailing list](https://groups.google.com/forum/#!forum/bioc-ggtree) and post your question on the mailing list if you have any in future.
