### ISSUE TITLE
ggtree - circular Tree

### ISSUE THREAD

**Issue by KarlaJS** [GuangchuangYu/ggtree#17]
I am having trouble formatting the names in the circular tree. The names are in the default position.
I need the names remain in the radial position (each name in front of your branch, the radial position).

Script used:
ggtree(tree,layout="circular",branch.length="none",aes(color=group))+ geom_text(aes(label=label, angle=angle), size=2,vjust=-0.3, hjust=1) +scale_color_manual(values=c("slateblue4","firebrick"))

Thanks.

**Comment by GuangchuangYu** [comment]
can u send the tree file to gcyu AT hku.hk for testing?

**Comment by GuangchuangYu** [comment]
![screenshot from 2015-10-21 23 58 02](https://cloud.githubusercontent.com/assets/626539/10642374/f9099fae-784f-11e5-8b49-8a2ff994f040.png)

use `aes(angle=angle)` should be fine.

**Comment by xiaofeiyangyang** [comment]
Hi
   I have the same problem  about I want view the "label names remain in the radial position" I use aes(angle=angle) but it doesn't work,there is another way "ggtree" can do this?

**Comment by GuangchuangYu** [comment]
show me your script that I CAN reproduce your issue.

PS: pls make sure you are using the latest release version of [ggtree](http://bioconductor.org/packages/release/bioc/html/ggtree.html).

**Comment by xiaofeiyangyang** [comment]
I draw a tree as you example  p<- ggtree(tree,layout ="circular")
                                               p + geom_text(aes(label=label, angle=angle), vjust =-.2, na.rm = T)
but I want get names asradial position example in Figtree view as follow
![snapshot2](https://cloud.githubusercontent.com/assets/10369795/10655086/10a948c2-78a4-11e5-9eb3-6f7fadfd158c.png)
I draw the tree in "ggtree" is
![snapshot1](https://cloud.githubusercontent.com/assets/10369795/10655145/a02025ac-78a4-11e5-9e11-f9e280a14d5d.png)

there is a way to get label name as radial position in  ggtree?

**Comment by GuangchuangYu** [comment]
```r
p + geom_text(aes(label=label, angle=angle+90),  hjust=-.2, na.rm = T)
```

![screenshot 2015-10-22 10 15 17](https://cloud.githubusercontent.com/assets/626539/10655271/d0e2d62a-78a5-11e5-82c8-3f0d687a8353.png)

**Comment by xiaofeiyangyang** [comment]
yeser it's so cool, My trouble has been solved perfectly.
thank you very much!

**Comment by GuangchuangYu** [comment]
![screenshot 2015-10-22 11 40 13](https://cloud.githubusercontent.com/assets/626539/10656479/b3a71240-78b1-11e5-9d5d-7dbb21b750f2.png)

Someone already figure this out, see the figure and script in [http://a.bioon.com.cn/bioonzl/article.do?artno=240](http://a.bioon.com.cn/bioonzl/article.do?artno=240).

**Comment by xiaofeiyangyang** [comment]
I just saw your message，I already figure my tree be the same as you post too! the "ggtree " package is very cool and useful,Thanks again！

**Comment by KarlaJS** [comment]
Hi,
My trouble has been solved perfectly.
Thank you very much!

**Comment by KarlaJS** [comment]
Hi,

Would have put the distance values in the circular tree?

Take the example of the figure
![example](https://cloud.githubusercontent.com/assets/14805123/10716192/c98b5a2c-7b17-11e5-9c52-d23951cdbac5.jpg)

Thank you!
