### ISSUE TITLE
could not find function "discrete_colours"

### ISSUE THREAD

**Issue by Nekochef** [GuangchuangYu/ggtree#173]
Repex:

```
library(tidyverse)
library(picante)
library(ggtree)

data(phylocom)

groupInfo <- split(phylocom$phylo$tip.label, gsub("_\\w+", "", phylocom$phylo$tip.label))
phylocom$phylo <- groupOTU(phylocom$phylo, groupInfo)
ggtree(phylocom$phylo, aes(color=group), layout='circular') + geom_tiplab(size=1, aes(angle=angle))
```
Then I get an error:

> Error in discrete_colours(colours) : 
>   could not find function "discrete_colours"

I'm using ggtree 1.11.6 and ggplot 2.2.1.9000, which I installed directly from github just now, under R 3.4.2.

**Comment by GuangchuangYu** [comment]
```
> packageVersion("ggtree")
[1] ‘1.11.6’
> packageVersion("ggplot2")
[1] ‘2.2.1’
```

Have no problem using the above versions.

**Comment by Nekochef** [comment]
My library must be broken. No problem running code with my brand new library. Sorry about this.
