### ISSUE TITLE
geom_hilight() does not work for my data

### ISSUE THREAD

**Issue by zhanxw** [GuangchuangYu/ggtree#174]
### Prerequisites

+ [x] Have you read [Feedback](https://guangchuangyu.github.io/ggtree/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [x] make sure your are using the latest release version
	* [x] read the [documents](https://guangchuangyu.github.io/ggtree/documentation/)
	* [x] google your quesion/issue

### Describe you issue

I tried to visualize a tree and highlight a node and its children nodes using geom_hilight, but the code in gist did not work:
https://gist.github.com/zhanxw/53535761516c0641d734707733518e96

However, ggtree examples (https://www.bioconductor.org/packages/3.7/bioc/vignettes/ggtree/inst/doc/treeAnnotation.html#highlight-clades) worked. I don't know why geom_hilight worked for the example data but not my data.

* [x] Make a reproducible example (*e.g.* [https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb])
* [x] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [x] for bugs or feature requests, post here (github issue)
* [x] for questions, please post to [google group](https://groups.google.com/forum/#!forum/bioc-ggtree)

**Comment by GuangchuangYu** [comment]
because node 16 is a singleton.

**Comment by zhanxw** [comment]
Does singleton refer to that node 16 has only one child node?
In this case, is there a way to highlight this branch?

**Comment by GuangchuangYu** [comment]
yes and currently not supported.
