### ISSUE TITLE
could not find function "read.mrbayes" error

### ISSUE THREAD

**Issue by Sunyp-IM** [GuangchuangYu/ggtree#179]
Dear Prof. Yu,

When I try the codes at the website of ggtree introduction document (http://bioconductor.org/packages/devel/bioc/vignettes/treeio/inst/doc/Importer.html#introduction), the codes for "Parsing MrBayes output" gives error:

> library(ggtree)
> file <- system.file("extdata/MrBayes", "Gq_nxs.tre", package="treeio")
> read.mrbayes(file)
Error in read.mrbayes(file) : could not find function "read.mrbayes"

Is it caused by the missing of  "read.mrbayes" function? And how to fix it?

Thank you!

**Comment by GuangchuangYu** [comment]
follow the [msg](https://github.com/GuangchuangYu/ggtree/issues/new) and you will find the answer.

**Comment by Sunyp-IM** [comment]
Sorry Prof. Gu, but what is msg?
