### ISSUE TITLE
flag to control ladderize

### ISSUE THREAD

**Issue by michaelalfaro** [GuangchuangYu/ggtree#18]
Is it possible to ladderize in the other direction (increasing or decreasing order)?

Thanks!

**Comment by GuangchuangYu** [comment]
Hi, you can use the `right` parameter, by default `right=TRUE` and the direction is increasing.
If you want decreasing order, use `right=FALSE`.

An example can be found in [http://ygc.name/2015/04/01/an-example-of-drawing-beast-tree-using-ggtree/](http://ygc.name/2015/04/01/an-example-of-drawing-beast-tree-using-ggtree/).

**Comment by michaelalfaro** [comment]
Hi Yu,

Thanks for making ggtree!  I spent most of the day with it and am very impressed. I was wondering if you could answer two questions for me?

1) Is it possible to reverse the timescale in theme_tree2 so that the oldest ages are at the root and 0 is at the present?

2) is there a way to control the size of the tree relative to the size available for tip names and image annotations? I would like to have control of the x axis of the tree figure so I could shrink it a bit and leave more room to taxon names etc.

Thanks for any help!

Mike

**Comment by GuangchuangYu** [comment]
### Q1
```r
p <- ggtree(rtree(30))
p$data$x <- p$data$x - max(p$data$x)
p
```

### Q2
[annotating with image](http://ygc.name/2015/08/01/ggtree-annotate-phylogenetic-tree-with-local-images/) is always relative to the drawing canvas, so the answer is yes.

But for tip names, we can't control their size relative to the tree or vice verse, see [my answer to the question](https://support.bioconductor.org/p/72398/).

If you just want to allocate more space for tip names, just use `xlim` to get more space.

**Comment by michaelalfaro** [comment]
thanks very much!!!

**Comment by michaelalfaro** [comment]
Hi Guanchuang,

Is there a way to adjust the position of geom_nodepoints? I tried something like this but I don’t think the points are moving….


ggtree(beast) + geom_nodepoint(aes(label = bootstrap), vjust=.1, hjust=-10, size = 2)

thanks very much!

**Comment by GuangchuangYu** [comment]
you can't move the `point`. 

It seems you want to label `bootstrap` value, try using `geom_text`.

**Comment by michaelalfaro** [comment]
ok thanks. I wanted to use a symbol for the bootstrap values and another symbol for the posteriors….
