### ISSUE TITLE
Bug in gheatmap (not exact match to tip names)

### ISSUE THREAD

**Issue by vmikk** [GuangchuangYu/ggtree#182]
### Prerequisites

+ [x] Have you read [Feedback](https://guangchuangyu.github.io/ggtree/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [x] make sure your are using the latest release version
	* [x] read the [documents](https://guangchuangyu.github.io/ggtree/documentation/)
	* [x] google your quesion/issue

### Describe you issue

* [x] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [x] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [x] for bugs or feature requests, post here (github issue)
* [ ] for questions, please post to [google group](https://groups.google.com/forum/#!forum/bioc-ggtree)

Hello!
First of all, I would like to thank you for this wonderful and very powerful package!

I have tried to plot a phylogenetic tree with heatmap of associated matrix (with `gheatmap`).
I found that the row names of matrix doesn't exactly match to the tip names of tree in case if there is missing data in associated matrix.
In other words, if we have two species (e.g., Species**198** and Species**1981**), but only one of them is represented in the associated matrix, we will have colored cells for both species in the heatmap.

Here is a reproducible example:
```
library(ggtree)

set.seed(111)

# Prepare a species list
tipss <- c("Fomes", "Rozella", "Saitoella", "Entorrhiza", "Cryptococcus", "Tremella", "Puccinia", "Amoeboaphelidium")
tipss <- c(tipss, "Species198", "Species1981")

# Generate random tree
trr <- ape::rtree(n = length(tipss), rooted = TRUE, tip.label = tipss)

# Generate associated data matrix for each species
abunds <- matrix(data = sample(1:100, size = 4*length(tipss)), nrow = length(tipss))
rownames(abunds) <- tipss
colnames(abunds) <- paste("Samp", 1:ncol(abunds), sep="")

# Remove data for some species
abunds <- abunds[-which(rownames(abunds) == "Species198"), ]     # !! no information for this species
abunds <- abunds[-which(rownames(abunds) == "Cryptococcus"), ]

tt <- ggtree(trr) + geom_tiplab()
gheatmap(tt, abunds)
```

Here is the resulting picture:
![example](https://user-images.githubusercontent.com/7162120/40344814-f8a03256-5daf-11e8-8762-6ecd4f5cad65.png)

You may see that heatmap cells are blank for Cryptococcus (as expected).
However, cells corresponding to Species198 are colored with Species1981 data (marked with red arrow).

With best regards,
Vladimir

**Comment by GuangchuangYu** [comment]
good catch and this is an unexpected surprise from `R`.

```r
> dd
                 Samp1 Samp2 Samp3 Samp4
Fomes               47    58     3    13
Rozella            100    83    27    18
Saitoella           36    51    78    63
Entorrhiza          70    32    43    16
Tremella            75    73    35    20
Puccinia            61    53     8    72
Amoeboaphelidium    95    66    92    19
Species1981         30    48    34    41
> dd['Species198',]
            Samp1 Samp2 Samp3 Samp4
Species1981    30    48    34    41
```

bug fixed.

**Comment by vmikk** [comment]
Great, It's working now!
Thank you.
