### ISSUE TITLE
Feature request: show root edge

### ISSUE THREAD

**Issue by richelbilderbeek** [GuangchuangYu/ggtree#183]
### Prerequisites

+ [x] Have you read [Feedback](https://guangchuangyu.github.io/ggtree/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [x] make sure your are using the latest release version
	* [ ] read the [documents](https://GuangchuangYu.github.io/ggtree/documentation/)
	* [x] google your quesion/issue

I did not read the [documents](https://GuangchuangYu.github.io/ggtree/documentation/), as the page is not found. I did read the [documents at the present location](https://guangchuangyu.github.io/software/ggtree/documentation/)

### Describe you issue

* [x] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [x] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

I would like to plot a phylogeny, including its root edge or stem.

```
# A phylogeny with a long stem
phylo <- ape::read.tree(text = "(A:1,B:1):20;")
```

This can easily be done in `ape`:

```
# Plot the phylogeny with the long stem with its stem visible
ape::plot.phylo(phylo, root.edge = TRUE); ape::add.scale.bar()
```

resulting in:

![ape_stem](https://user-images.githubusercontent.com/2098230/41223631-a2f86344-6d6a-11e8-853a-37d28c696aa2.png)

I was unable to find how achieve the same with `ggtree`. 
As the question how to do so remains unanswered in [the google group](https://groups.google.com/forum/#!searchin/bioc-ggtree/root$20edge%7Csort:date/bioc-ggtree/qX_maKDdQ2I/GpsB9MjxBgAJ), I assume it cannot yet be done. 
I could get an accent on the root:  

```
# Plot the phylogeny with the long stem with its root node shown, 
# instead of drawing the root edge
ggtree::ggtree(phylo) + ggtree::geom_treescale() + ggtree::geom_rootpoint()
```

Now I have a workaround by using white edges, but I think `ggtree` is able to do better. 

This Issue is similar to #95, except that I want to draw the root edge, instead of adding space at the center of a fan phylogeny. 

Note that [FigTree, as mentioned in the documentation](http://guangchuangyu.github.io/2015/04/an-example-of-drawing-beast-tree-using-ggtree/) does provide to display a stem

### Ask in right place

* [x] for bugs or feature requests, post here (github issue)
* [x] for questions, please post to [google group](https://groups.google.com/forum/#!forum/bioc-ggtree)

As the same question has not been answered in [the google group](https://groups.google.com/forum/#!searchin/bioc-ggtree/root$20edge%7Csort:date/bioc-ggtree/qX_maKDdQ2I/GpsB9MjxBgAJ), I mark this as a feature request

**Comment by GuangchuangYu** [comment]
`geom_rootedge` was introduced in v >= 1.13.0.006.

```r
## by default, use phylo$root.edge
ggtree(phylo) + geom_rootedge() + geom_treescale(-15, 1, offset=0.01, width=.5)

## you can also specify rootedge directly in geom_rootedge
ggtree(phylo) + geom_rootedge(3) + geom_treescale(-2, 1, offset=0.01, width=.5)
```
