### ISSUE TITLE
ndigits is unknown

### ISSUE THREAD

**Issue by carollia** [GuangchuangYu/ggtree#184]
Hi,

Thanks for making such a nice package!

I tried to plot a tree using ggtree and when I do so I get the error "Warning: Ignoring unknown parameter: ndigits". I am using the most recent version of R (Joy in Playing) and ggplot version 1.12.0 which is the most recent I can find. This was working last month before I updated my R so maybe it's an incompatibility thing?

I'm using it to plot the output of a BEAST tree so I'm not sure how to make a reproducible example short of sending you the tree I'm working on. 

This is the code I was using that was working before: 
p <-ggtree(Thing, ndigits=2) + geom_tiplab() + geom_text(aes(x=branch, label=posterior),cex=3, nudge_y=0.5)
q <- p %<+% SmallMetadata + geom_tiplab(aes(color=EctoHost)) + geom_tippoint(aes(shape=Region), alpha=1, cex=3 )
q +theme(legend.position="right")

Thanks for your help!

Hannah

**Comment by GuangchuangYu** [comment]
the `ndigits` parameter was removed.

**Comment by ypchan** [comment]
> the `ndigits` parameter was removed.

Are there other methods to limit the number of digits?
`
library(treeio)
library(ggtree)
file <- system.file("extdata/BEAST", "beast_mcc.tree", package="treeio")
beast <- read.beast(file)
beast

get.fields(beast)
ggtree(beast, branch.length = 'none') + geom_text(aes(x = branch, label =length_0.95_HPD), vjust = -.5, color = 'firebrick')
`
