### ISSUE TITLE
getSubtree?

### ISSUE THREAD

**Issue by matiasirazoqui** [GuangchuangYu/ggtree#186]
Hi,
I'm using ggtree to plot a very big tree (>10.000 leaves) and I wanted to extract all tips that originate from a particular node. My first thought was to extract a subtree and use the "tip.label" variable. Going through the documentation I found a function called "getSubtree", which seems to be exactly what I need, but I couldn't find it in ggtree 1.12.4 nor 1.13.1. Is there any other way to do what I want? Thanks!

**Comment by tbradley1013** [comment]
You can use the [`tree_subset`](https://rdrr.io/github/GuangchuangYu/treeio/man/tree_subset.html) function which is in the development version of `treeio` and can be installed by running:

```
devtools::install_github("GuangchuangYu/treeio")
```

This function works very similar to what you are describing. You can subset the tree by specifying the desired node and how many levels back in the tree (from the specified node) that you wish to include. It works for both `phylo` and `treedata` classes. 

I recently wrote [a blog post](https://tbradley1013.github.io/2018/06/19/subsetting-phylogenetic-trees/) about it and created [a shiny app](https://github.com/tbradley1013/tree-subset-shiny) around its functionality.
