### ISSUE TITLE
viewClade behaving oddly since update to ggtree_1.12.6

### ISSUE THREAD

**Issue by matbeale** [GuangchuangYu/ggtree#188]
Hi,
I've just updated to the latest version of R and ggtree, and viewClade has stopped working (presumably something to do with scaling).  In the example below, the tree basically rescales to a single branch. I've never noticed this behaviour before, and I'm using trees I've plotted before with the same code. Please see my example:

```{r}
nwk <- system.file("extdata", "sample.nwk", package="treeio")
tree <- read.tree(nwk)
ggtree(tree) + geom_text2(aes(subset=!isTip, label=node), hjust=-.3)
```

Full Tree
![image](https://user-images.githubusercontent.com/16351605/43772273-728337b0-9a39-11e8-8f87-68c3861fe3bc.png)

```{r}
viewClade(ggtree(tree),17)
```
zoomed clade 17
![image](https://user-images.githubusercontent.com/16351605/43772238-5d01c69a-9a39-11e8-8763-579386d7a1b1.png)

R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] grid stats graphics grDevices utils datasets methods base

other attached packages:
[1] treeio_1.4.2 BiocInstaller_1.30.0 bindrcpp_0.2.2 rPinecone_0.1.0 randomcoloR_1.1.0 gridExtra_2.3
[7] reshape2_1.4.3 dplyr_0.7.6 plyr_1.8.4 phytools_0.6-44 maps_3.3.0 ggtree_1.12.6
[13] ape_5.1 ggplot2_3.0.0

**Comment by GuangchuangYu** [comment]
duplicated, <https://github.com/GuangchuangYu/ggtree/issues/187#issuecomment-411013857>.
