### ISSUE TITLE
Repeated calling geom_point2() has different results

### ISSUE THREAD

**Issue by zhanxw** [GuangchuangYu/ggtree#190]
### Prerequisites

+ [x] Have you read [Feedback](https://guangchuangyu.github.io/ggtree/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [x] make sure your are using the latest release version
	* [X] read the [documents](https://guangchuangyu.github.io/ggtree/documentation/)
	* [x] google your quesion/issue

### Describe you issue

* [x] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [x] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [x] for bugs or feature requests, post here (github issue)
* [x] for questions, please post to [google group](https://groups.google.com/forum/#!forum/bioc-ggtree)

When I use geom_point2 in a for loop, only the last call is effective (Figure 1, attached).
If I manually unroll the loop, all calls are effective (Figure 2, attached).
Can you explain why the outputs of the two examples are different? 
There seems to be a bug in my point of view.

```
#Figure 1
library(ggtree)
set.seed(42)
tree <- rtree(5)
p <- ggtree(tree)
data <- data.frame(taxa = sprintf("t%d", seq(5)))
p <- p %<+% data
for (i in 1:5) {
  p <- p + 
    geom_point2(aes(subset = (node %in% i), col = i))
}
print(p)
```

![figure1](https://user-images.githubusercontent.com/157832/44570691-45796b00-a744-11e8-8748-8e14c9f67b56.png)

```
#Figure 2
library(ggtree)
set.seed(42)
tree <- rtree(5)
p <- ggtree(tree)
data <- data.frame(taxa = sprintf("t%d", seq(5)))
p <- p %<+% data
p <- p + 
  geom_point2(aes(subset = (node %in% 1), col = 1)) + 
  geom_point2(aes(subset = (node %in% 2), col = 2)) + 
  geom_point2(aes(subset = (node %in% 3), col = 3)) + 
  geom_point2(aes(subset = (node %in% 4), col = 4)) + 
  geom_point2(aes(subset = (node %in% 5), col = 5)) +
  scale_color_identity()
p
```

![figure2](https://user-images.githubusercontent.com/157832/44570690-45796b00-a744-11e8-99db-42856b5020d9.png)

**Comment by brj1** [comment]
This is due to how ggplot2 works. `ggplot` does not resolve variables until it plots so when `geom_point2(aes(subset = (node %in% i), col = i))` is plotted all five instances of have `i=5` and thus only the one point will be plotted. To overcome this problem, you colour try defining the colour in one swoop. Say: `geom_point2(aes(col = factor(node)))`.

**Comment by zhanxw** [comment]
@brj1 Thanks for the explanation.
