### ISSUE TITLE
Different output files for RAxML, but same tree view format

### ISSUE THREAD

**Issue by AJ211** [GuangchuangYu/ggtree#194]
Hello, Yu:
   I have a question about ggtree for showing bootstrap value with different output files by RAxML. 
   I got two files  (bipartition and  bipartitionBranchLabels) with bootstrap value after RaxML. When I uploaded these two files into ggtree, I found that the bootstrap value for two files all showed in the node.
  I think the bootstrap value of bipartitionBranchLabels file should show in the branches, isn't it?

 Looking forward to your reply,
 Thanks a lot.

**Comment by GuangchuangYu** [comment]
`aes(x = branch)` will display the values to the middle of edges.
