### ISSUE TITLE
"Error in seq.default" while annotating tree tip_color 

### ISSUE THREAD

**Issue by Adri1CIRAD** [GuangchuangYu/ggtree#199]
Hi there,
I'm struggling to understand the following error I'm having while using a very simple code aiming to color tip according to a qualitative factor. Any help/advice welcome !

=> read the tree 
tree <- read.tree("Xf_tree")
=> read the medatata in df format
meta=read.table("metadata.txt", header=T, stringsAsFactors = FALSE)
=> order rows in metadata to match with tree tip names 
tipOrder <- match( tree$tip.label , meta$names_in_tree )
meta <- meta[ tipOrder , ]
=> label row names as tip labels
row.names(meta) <- tree$tip.label
=> plot
p <- ggtree(tree,layout = "fan") + geom_rootpoint()
p %<+% meta + geom_tippoint(aes(fill=country),shape = 21,colour = "black", size = 4)

# Error in seq.default(h[1], h[2], length.out = n) :   'to' ne peut être NA, NaN ou infini**

I've attached both the metadata and the tree files

[Archive.zip](https://github.com/GuangchuangYu/ggtree/files/2456366/Archive.zip)

**Comment by GuangchuangYu** [comment]
for `%<+%` operator, the first column should be node/tip labels.

the following code works:

```
meta = meta[, c(2, 1, 3:5)]
p %<+% meta + geom_tippoint(aes(fill=country),shape = 21,colour = "black", size = 4)
```
