### ISSUE TITLE
Install in R 3.1.0 fails

### ISSUE THREAD

**Issue by alexhbnr** [GuangchuangYu/ggtree#2]
The install in R 3.1.0 fails because of a *namespace* error.

> \*installing *source* package ‘ggtree’ ...
> **R
> **inst
> **tests
> **preparing package for lazy loading
> Error : object ‘%<>%’ is not exported by 'namespace:magrittr'
> ERROR: lazy loading failed for package ‘ggtree’

The installation process fails for both installing directly from github or using a tar-ball. Are there any dependencies that can cause this?

**Comment by GuangchuangYu** [comment]
You should update magrittr.
