### ISSUE TITLE
"Scale for 'fill' is already present" error when annotating circular trees

### ISSUE THREAD

**Issue by Adri1CIRAD** [GuangchuangYu/ggtree#205]
Hi there,

First, I want to say that my issue seems to be closely related to another one recently published (https://github.com/GuangchuangYu/ggtree/issues/78). I've tried to sort my issue out using those comments but I haven't been successful.

I'm trying to add two independently coloured heatmaps with separate legends with gheatmap to a circular tree. Contrary to the situation in issue 78, the two heatmaps are based on different values (here country and time of sample isolation).

I'm getting the following error: "Scale for 'fill' is already present. Adding another scale for 'fill', which will replace the existing scale."

Below my code and attached my data.

Thanks very much for your help, I've been stuck on this error several days.

```r
library(ape)
library(ggplot2)
library(ggtree)
require(phytools)
require(phangorn)
require(RColorBrewer)

# read the tree 
tree <- read.tree("Xf_tree.txt")
# read metadata - for %<+% operator, the first column should be node/tip labels.
meta=read.table("metadata.txt", header=T, stringsAsFactors = T)
# order the metadata file to match with tip_names order in the tree
tipOrder <- match( tree$tip.label , meta$taxa )
meta <- meta[ tipOrder , ]
row.names(meta) <- tree$tip.label
sapply(meta, class)
# change the class of date column to be "factor"
meta[,4] <- as.factor(meta[,4])
# make two different color palettes
# for country
L=length(table(meta$country))
bu <- colorRampPalette(brewer.pal(L,"Accent"))
display.brewer.pal(L,"Accent")
country.cols <- setNames(object=bu(L),nm=(unique(meta$country)))
# for dates
L1=length(table(meta$date))
bu <- colorRampPalette(brewer.pal(L1,"Blues"))
display.brewer.pal(L1,"Blues")
date.cols <- setNames(object=bu(L1),nm=sort(unique(meta$date)))

# There we go:

p <- ggtree(tree,layout = "fan", size = 0.5) + geom_rootpoint() 
p <- p %<+% meta + geom_tippoint(aes(fill=country),shape = 21,colour = "black", size = 4) 
p1 <- gheatmap(p, meta[, "country", drop=F], offset=.1, width=.1,colnames_angle=90, colnames_offset_y = 0) + scale_fill_manual(values=country.cols)
p2 <- gheatmap(p1, meta[, "date", drop=F], offset=5, width=.1,colnames_angle=90, colnames_offset_y = 0) + scale_fill_manual(values=c(country.cols,date.cols))
p2
```

=> As a figure I only get one single external  circle colored.... 
[metadata.txt](https://github.com/GuangchuangYu/ggtree/files/2502020/metadata.txt)
[Xf_tree.txt](https://github.com/GuangchuangYu/ggtree/files/2502023/Xf_tree.txt)

**Comment by brj1** [comment]
`ggheatmap` positions the heat map based on the phylogenetic tree. In your code it is plotting both heat maps, but the second is covering the first. Try setting the offset to a really high number; `offset=200` workedfor me to display both heat maps.

**Comment by Adri1CIRAD** [comment]
Indeed, thanks. (One) problem solved !
