### ISSUE TITLE
inset not working properly in R 3.5.1

### ISSUE THREAD

**Issue by fionarhuang** [GuangchuangYu/ggtree#206]
### Prerequisites

+ [x] Have you read [Feedback](https://guangchuangyu.github.io/ggtree/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [x] make sure your are using the latest release version
	* [x] read the [documents](https://guangchuangyu.github.io/ggtree/documentation/)
	* [x] google your quesion/issue

### Describe you issue
Hi Guangchuang, 
The example given in the [Annotate a phylogenetic tree with insets](https://guangchuangyu.github.io/2016/01/annotate-a-phylogenetic-tree-with-insets/)
doesn't work now. When I run the code, there is no error message but the bar chart doesn't really show up in the tree. Would it be possible for you to kindly help me out on this issue. Thanks!

Ruizhu

set.seed(2015-12-31)
tr <- rtree(15)
p <- ggtree(tr)

a <- runif(14, 0, 0.33)
b <- runif(14, 0, 0.33)
c <- runif(14, 0, 0.33)
d <- 1 - a - b - c
dat <- data.frame(a=a, b=b, c=c, d=d)
dat$node <- 15+1:14

bars <- nodebar(dat, cols=1:4)
inset(p, bars, width=.03, height=.06)

The issue: The figure in the original website can't be reproduced and no error or warning messages are thrown out. The bar charts are not shown in the tree.

**Comment by GuangchuangYu** [comment]
![2018-10-23-090052_1280x800_scrot](https://user-images.githubusercontent.com/626539/47328084-30687c00-d6a2-11e8-8cd2-c4fe261639f5.png)

thanks for your report. Due to some internal changes, you need to increase the width and height values.

**Comment by GuangchuangYu** [comment]
pls refer to the latest document of `inset`, <https://guangchuangyu.github.io/software/ggtree/vignettes/ggtree-inset.html>.
