### ISSUE TITLE
reroot function error

### ISSUE THREAD

**Issue by jsoghigian** [GuangchuangYu/ggtree#207]
Hello Guangchuang,

I am having trouble with getting the reroot function to behave properly.

> Error in (function (classes, fdef, mtable)  : 
>   unable to find an inherited method for function ‘reroot’ for signature ‘"treedata"’

This has occurred with my own tree imported with read.iqtree, but also occurs with other trees, e.g. below:

```
> beast_file <- system.file("examples/MCC_FluA_H3.tree", package="ggtree")
> beast_tree <- read.beast(beast_file)
> reroot(beast_tree,node=5)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘reroot’ for signature ‘"treedata"’
```

**Comment by brj1** [comment]
The `reroot` function is only implemented for the `phylo` class. You can simply run `reroot` on the `phylo` object of a `treedata` object to reroot the tree.

```r
library(ggtree)
beast_file <- system.file("examples/MCC_FluA_H3.tree", package="ggtree")
beast_tree <- read.beast(beast_file)
# reroot beast tree
reroot(beast_tree@phylo,node=5)
# save rerooted tree
beast_tree@phylo <- reroot(beast_tree@phylo,node=5)
```

**Comment by jsoghigian** [comment]
Great, thanks @brj1 !  the help documentation for reroot stats it takes a treedata object so I had just been re-rooting by other means before, but am trying to move more towards ggtree for visualization entirely.  Appreciate the heads-up.
