### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Godrigos** [GuangchuangYu/ggtree#216]
Hi there, I'm having a very odd issue with ggtree. I was using it without any problems till a couple of days ago. Now when I try to load it to use, or update it (I'm using 3.5 and there is already a 3.8 version).
I get this error:

Erro: package or namespace load failed for ‘ggtree’:
 objet ‘as_data_frame’ was not exportaded by 'namespace:tidytree'

I can load tidytree correctly...

I'm on a Ubuntu 18.04 (4.15.0-39, x64) using R 3.5.1. The only thing I remember doing between the moment it was working and the moment it stopped was to install IQTree (sudo apt install iqtree), but this is probably unrelated.

Any one has any ideas on how to solve this?

**Comment by GuangchuangYu** [comment]
This is due to the change of `tibble`.

just wait 2-3 days for bioconductor to update ggtree tarball and then you can upgrade your installation.

**Comment by Godrigos** [comment]
Thank you very much.
