### ISSUE TITLE
facet_plot Error in scale_index[[i]] : subscript out of bounds

### ISSUE THREAD

**Issue by schultzm** [GuangchuangYu/ggtree#220]
Hi, 

The error `Error in scale_index[[i]] : subscript out of bounds` is produced by the following code.  Any ideas why?  
Thanks

```
library(ggplot2)
library(ggstance)
library(ggtree)
tr <- rtree(30)
d1 <- data.frame(id=tr$tip.label, val=rnorm(30, sd=3))
p <- ggtree(tr)
p2 <- facet_plot(p, panel="dot", data=d1, geom=geom_point, aes(x=val), color='firebrick')
d2 <- data.frame(id=tr$tip.label, value = abs(rnorm(30, mean=100, sd=50)))
p3 <- facet_plot(p2, panel='bar', data=d2, geom=geom_segment, aes(x=0, xend=value, y=y, yend=y), size=3, color='steelblue') + theme_tree2()
p3
```

**Comment by NingxiaoMo** [comment]
I have the same problem with you ,and I solve it，and  hope it'll help you.
I found that my version of ggplot2 is wrong.
It shows version 3.1.0.9000
So I re-downloaded the ggplot2 version 3.1.0
and important thing ，remember to restart  R
and library() again.

**Comment by schultzm** [comment]
@NingxiaoMo you are a wonderful human being.  Thank you for solving this.  Your solution fixed my problem.
```
remove.packages(ggplot2) #clear workspace, restart R
install.packages("ggplot2")
```
