### ISSUE TITLE
groupOTU 

### ISSUE THREAD

**Issue by yuntwang** [GuangchuangYu/ggtree#223]
Hi,
In personal computer, my ggtree version is 1.4.20 and when I use the function groupOTU:
groupOTU(object, focus, group_name = "group")
In another computer, my ggtree version is 1.14.6 and when  I use the function groupOTU:
groupOTU(.data,.node,group_name="group")
why?
when I use the version 1.14.6 and I found a question,
my image like this:

![qq](https://user-images.githubusercontent.com/27258713/52042244-a325a500-2577-11e9-9305-e188feb3347f.png)

my group is JP SD SK.
Why is there an extra NA?

**Comment by GuangchuangYu** [comment]
If you check the figure, you should figure it out that those assigned to NA are not selected in any of your groups.

**Comment by yuntwang** [comment]
@GuangchuangYu 

I think may be a bug. My samples are grouped.
Below is my code:
library(ggtree)
setwd("/home/ubuntu/桌面/")
phylo <- read.tree(file = "Brapa_k2p.motif.nwk")
info <- read.delim("info_gene_flow.txt", header = T,sep = '\t',check.names = F,stringsAsFactors = F)
groupInfo <- split(x = info[,2],f = info[,4])
phylo <- groupOTU(object = phylo,focus = groupInfo)
phylo
p <- ggtree(tr = phylo,layout = "circular",branch.length = "none",
            mapping = aes(color = group))
p
info_gene_flow.txt is my group file.
Brapa_k2p.motif.txt is my tree(newick) file.

You can try running it again!
Thanks.

[info_gene_flow.txt](https://github.com/GuangchuangYu/ggtree/files/2913158/info_gene_flow.txt)
[Brapa_k2p.motif.txt](https://github.com/GuangchuangYu/ggtree/files/2913160/Brapa_k2p.motif.txt)

**Comment by GuangchuangYu** [comment]
groupOTU grouping tip labels and expecting the input to be in character.

the following code should works:

```
groupInfo <- split(x = as.character(info[,2]),f = info[,4])
groupInfo
phylo <- groupOTU(phylo, groupInfo)
phylo
p <- ggtree(tr = phylo,layout = "circular",branch.length = "none",
            mapping = aes(color = group))
```

![image](https://user-images.githubusercontent.com/626539/57825989-d52fdf80-77d3-11e9-88f8-0866a17cb240.png)

**Comment by yuntwang** [comment]
ok,thanks.
