### ISSUE TITLE
gheatmap and facet_widths

### ISSUE THREAD

**Issue by michitobler** [GuangchuangYu/ggtree#224]
Hi Guangchuang
Using the new facet_widths function with the example outlined here (https://yulab-smu.github.io/treedata-book/chapter9.html) works perfectly. Is there a way to get this function to work with gheatmap instead of facet_plot (I want to decrease the tree width and give more space to the heat map). Running the "facet_widths(p2, widths = c(1, 2))" line does not alter the facet sized when p2 is a gheatmap.
Best wishes, Michi

**Comment by GuangchuangYu** [comment]
did you read `?gheatmap`? there is a `width` parameter for adjusting relative widths.
