### ISSUE TITLE
Problem with *long* labels?

### ISSUE THREAD

**Issue by santiagosnchez** [GuangchuangYu/ggtree#226]
I may be missing something here, but aren't *long* labels (i.e. > 10 char.) supposed to show up adjusted to the tree? This is happening when plotting ultrametric trees with all tips in the present. Here is a testing example:

```
library(phytools)
library(ggtree)
tre = pbtree(n=50)
tre$tip.label = paste(tre$tip.label, LETTERS[1:10], sep="_____") # increase the length of the labels
ggtree(tre) + geom_tiplab()
```

You can compare it to:

`plot(tre)`

Thanks for any help.

**Comment by brj1** [comment]
This is a known issue with ggplot2. See https://github.com/GuangchuangYu/ggtree/issues/34
