### ISSUE TITLE
Problems with the instalation

### ISSUE THREAD

**Issue by PabloSanMar** [GuangchuangYu/ggtree#227]
Hi,

I have some problems installin ggtree. I'm running the following code to install it:

>source("http://bioconductor.org/biocLite.R")
>biocLite("ggtree")
>library(ggtree)

#Error: package or namespace load failed for ‘ggtree’:
#object ‘as_data_frame’ is not exported by 'namespace:tidytree'

Maybe the problem is related to a previous attempt to install it using the following code:

>install.packages("ggtree", repos = "http://www.bioconductor.org/packages/devel/bioc", type  = >"source")

Thanks a lot in advance,

Pablo

**Comment by jfy133** [comment]
Try installing both ggtree and tidytree with BiocManager (a new replacement of biocLite).

I had the same issue, and this did the trick:

```
install.packages("BiocManager")
BiocManager::install("tidytree")
BiocManager::install("ggtree")
```

The versions that then installed and worked were:
R: 3.5.3
BiocManager: 3.8
tidytree: 0.2.4
ggtree: 1.14.6

**Comment by PabloSanMar** [comment]
That worked, Thank you very much!
