### ISSUE TITLE
problem with geom_hilight

### ISSUE THREAD

**Issue by thaloranamika** [GuangchuangYu/ggtree#229]
### Prerequisites

+ [x] Have you read [Feedback](https://guangchuangyu.github.io/ggtree/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [ ] make sure your are using the latest release version
	* [ ] read the [documents](https://guangchuangyu.github.io/ggtree/documentation/)
	* [ ] google your quesion/issue

### Describe you issue

* [x] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [x] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [x] for bugs or feature requests, post here (github issue)
* [ ] for questions, please post to [google group](https://groups.google.com/forum/#!forum/bioc-ggtree)

**Comment by thaloranamika** [comment]
Hi @GuangchuangYu 
i am using your ggtree for phylogeny tree visualisation, but i am getting error while using its geom_hilight function.
 I am using the following command:
ggtree(tree, layout = "circular", branch.length = "none", color="blue") + geom_nodepoint(position = "identity", alpha = 0.5, color = "red", size=3) + geom_tippoint(pch = 23, col=c("black"), bg = 'black') + geom_tiplab2(size = 3.5, hjust=-0.1) + xlim(-4, 14) + geom_hilight(node = 52, fill = "steelblue", alpha = 0.5)

and my error while using this command is:
Error in FUN(X[[i]], ...) : object 'branch.length' not found

I tried to resolve the issue but couldn't. Kindly help me to resolve this issue. I am new in this area.

**Comment by GuangchuangYu** [comment]
duplicated, https://groups.google.com/d/msg/bioc-ggtree/zhVoqyMW6D0/loCOmBDqDQAJ
