### ISSUE TITLE
ggtree ignores attached node annotations

### ISSUE THREAD

**Issue by grayfall** [GuangchuangYu/ggtree#230]
Given a tree and a data frame, mapping node labels to floating point values, I want to plot the tree with coloured circles on top of nodes, where colour encodes absolute values. Unfortunately, `ggtree` seems to ignore the annotations altogether. Here is an MCVE

```
> library(ggplot2)
> library(ggtree)
> library(phytools)
>
> tree.nwk <- '((seq140:0.13041945852,seq87:0.3002143527299996)n6:0.04491171,(seq163:0.21652831800000003,(seq28:0.0535884,seq34:0.060002925)n5:0.10335070999999998)n7:0.0963524)n8:0.11015875999999998;'
> tree <- read.newick(text=tree.nwk)
> tree

Phylogenetic tree with 5 tips and 4 internal nodes.

Tip labels:
[1] "seq140" "seq87"  "seq163" "seq28"  "seq34" 
Node labels:
[1] "n8" "n6" "n7" "n5"
Rooted; includes branch lengths.
> tree.annotations <- data.frame(node=tree$node.label, value=rnorm(4))
> tree.annotations
    node       value
1   n8  2.15050556
2   n6 -0.04815265
3   n7  0.41109264
4   n5  0.42167331
> ggtree(tree) %<+% tree.annotations +
+     geom_nodepoint(aes(size=5, color=abs(value))) +
+     theme(legend.position="right")
```

<img width="744" alt="Screenshot 2019-05-04 at 21 38 27" src="https://user-images.githubusercontent.com/6906110/57183359-92593800-6eb4-11e9-9f9e-350cb2898a5a.png">

As you can see, there is no colour at all. I'm using the latest release from Bioconductor.

**Comment by grayfall** [comment]
Seems like, ggtree doesn't like when the first column is called `node`

```
> tree.annotations <- data.frame(name=tree$node.label, value=rnorm(4))
> ggtree(tree) %<+% tree.annotations + 
+     geom_nodepoint(aes(size=5, color=value)) + 
+     theme(legend.position="right")
```
<img width="745" alt="Screenshot 2019-05-04 at 21 42 40" src="https://user-images.githubusercontent.com/6906110/57183395-20cdb980-6eb5-11e9-83e0-3c576081849a.png">

**Comment by GuangchuangYu** [comment]
if the first column is 'node', `ggtree` will match the data with internal node number of the tree, otherwise it will try to match the data with node labels.
