### ISSUE TITLE
facet_plot panel.grid only in panel ?

### ISSUE THREAD

**Issue by picousse** [GuangchuangYu/ggtree#231]
Hi,
I really like the facet_plot's.
e.g.: https://yulab-smu.github.io/treedata-book/chapter7.html#plot-tree-with-associated-data

However I sometimes have troubles linking the panel data to the tree. Horizontal lines (y grid) could really improve readability, IMO.

I'm able to add panel.grid.major.y to the plot, but this is then plotted over the complete plot. I would just like to add it to the data facet, not across the tree. Is this possible?

```

library(tidyverse)
library(ggtree)
tr <- rtree(30)

d1 <- data.frame(id=tr$tip.label, val=rnorm(30, sd=3))

p <- ggtree(tr) + geom_tiplab( align=TRUE, linesize=.5) 

p2 <- facet_plot(p, panel="dot", data=d1, geom=geom_point, aes(x=val)) + 
  theme(panel.grid.major.y = element_line( size=.2, color="grey" ) ) +
  scale_y_continuous( breaks = seq(0, 30, 1))

p2
```

![image](https://user-images.githubusercontent.com/5084152/57246577-dc215a00-703d-11e9-8fbe-3e722feebc0d.png)

**Comment by GuangchuangYu** [comment]
you can add line segments to the `dot` panel, see example in <https://github.com/GuangchuangYu/plotting_tree_with_data>.
