### ISSUE TITLE
no applicable method for 'MRCA' applied to an object of class "phylo"

### ISSUE THREAD

**Issue by EmmaFinlay** [GuangchuangYu/ggtree#232]
MRCA commands which did work for me yesterday don't today.
I created a small example, visualising the tree shows t1 and t7 share a MRCA at node 12 but the MRCA command doesn't work

`> set.seed(1234) 
> tree <- rtree(n=10)
> ggtree(tree)+geom_tiplab()+geom_text(aes(label =node))
> MRCA(tree, tip=c(t7,t1))
Error in UseMethod("MRCA") : 
  no applicable method for 'MRCA' applied to an object of class "phylo"`

**Comment by GuangchuangYu** [comment]
```
> library(tidytree)
> library(ggtree)
>
> set.seed(1234)
> tree <- rtree(n=10)
> MRCA(tree, 't1', 't7')
[1] 11
```
