### ISSUE TITLE
local installation

### ISSUE THREAD

**Issue by alantsangmb** [GuangchuangYu/ggtree#233]
Hi, I am using R version 3.6.0 and BiocManager 1.30.4 in a ubuntu 14.04 system.
I got 'SSL connect error' when I attempt to install ggtree using the command:
BiocManager::install("ggtree").

I might somehow cannot access the repository due to the network settings.
Is there any way I can install ggtree locally?

**Comment by brj1** [comment]
You can install directly from GitHub with devtools:

```r
install.packages("devtools")
devtools::install_github("GuangchuangYu/ggtree")
```
or download the repository with git and install via the command line.

```
git clone https://github.com/GuangchuangYu/ggtree.git
R CMD INSTALL ggtree
```

However, I believe that the GitHub version may be less stable than the BioConductor version.

**Comment by alantsangmb** [comment]
Thank you!
The github installation work for me.
