### ISSUE TITLE
Can the boxplot match the space between species? 

### ISSUE THREAD

**Issue by xl0418** [GuangchuangYu/ggtree#238]
Hi, I am working on computing the phylogenetic independence contrasts (pics) between species. I would like to plot a tree with the distribution of the pics mapping to the space between species. Using ggtree, it is easy to map to the tips like this plot 

![test](https://user-images.githubusercontent.com/17046269/60891373-79c32080-a25d-11e9-9942-d7912bc275be.png)

But as the boxes are the pics that should map to the interspace of species. The boxes are supposed to move up a bit to match between species. Is that possible?  Like this figure

![test2](https://user-images.githubusercontent.com/17046269/60892336-4c777200-a25f-11e9-9b4c-a212b06d537b.png)

**Comment by GuangchuangYu** [comment]
I think you can use `export` package to edit your figure, see <https://yulab-smu.github.io/treedata-book/faq.html#export-edit>.
