### ISSUE TITLE
How do you combine a stacked bar chart on a ggtree that has a heatmap?

### ISSUE THREAD

**Issue by Siacm** [GuangchuangYu/ggtree#241]
Hi! I hope you can help because I have spent a few hours trying to figure this out:

What I have done:
Task (a): I have created tree(p) with data1(d1) tip colors and combined with data2(d2) heatmap with gheatmap and can turn t

Task (b): I have created a data3(d3) stacked barchart and combined with tree(p) with facet_plot

**What I am stuck with** - I would like to combine ggtree, heatmap and stacked barchart.
Option (a): Is there a way to combine stacked bar chart to circular heatmap?
Option (b): Is there a way to make the heatmap a separate facet that comes _after_ stackedbarchart facet?

library(ggstance)
library(ggtree)

#tree
tr <- rtree(30)
p <- ggtree(tr)
p_circ<-ggtree(tr,layout="circular)

##data 1 to put on color tips
d1 <- data.frame(id=tr$tip.label, location=sample(c("GZ", "HK", "CZ"), 30, replace=TRUE))

##data2 to make heatmap
d2 <- data.frame(id=tr$tip.label, val=rnorm(30, sd=3))
rownames(d2) <- d2[,1]
d2[,1] <- NULL

##data3 for stacked barchart
d3 <- data.frame(id = rep(tr$tip.label, each=2),
                 value = 1,
                 category = rep(LETTERS[1:2], 15),stringsAsFactors = T)

#plot tip label colors with p1 and p1_circ
p1 <- p %<+% d1 + geom_tippoint(aes(color=location))
p1_circ <- p_circ %<+% d1 + geom_tippoint(aes(color=location))

#plot heatmap data2 with tree p1
p2<-gheatmap(p1_circ, d2, offset=0, width=0.6, color=NA, colnames=FALSE)

#plot p1 with a stacked barplot 
p3 <- facet_plot(p1, panel = 'Stacked Barplot', data = d3, 
                 geom = geom_barh, 
                 mapping = aes(x =value, fill = category), 
                 stat='identity')

I hope you can help- I've been stuck on this for hours.

**Comment by GuangchuangYu** [comment]
option a is currently not supported. 

option b is supported, see the attachment file of <https://academic.oup.com/mbe/article/35/12/3041/5142656>.

**Comment by Siacm** [comment]
Thanks :)
