### ISSUE TITLE
annotation_clade2 no longer accepts hjust parameter

### ISSUE THREAD

**Issue by ajwnewkirk** [GuangchuangYu/ggtree#25]
I upgraded my installation of ggtree today from the bioconductor version to the current github version because I had a special request for the ggtree(ladderize = TRUE) feature, but the upgrade had the unexpected side effect of removing the hjust parameter for annotation_clade2() function.

Eg. I get the error message "Error: Unknown parameters: hjust" under the github version but not the bioconductor version for the following.
ttree <- read.tree(file = "example.tree.txt")
ttree <- midpoint(ttree)
gtree <- ggtree(ttree, ladderize = FALSE)
mytree <- gtree + geom_text(aes(label =label), hjust = -0.03)
annotation_clade2(mytree, tip1 = "C", tip2 = "D", label = "test", angle = 0, hjust = 0)

I still see the error if ladderize = TRUE on the github version.

[example.tree.txt](https://github.com/GuangchuangYu/ggtree/files/33379/example.tree.txt)

**Comment by GuangchuangYu** [comment]
you should pass `reorder(ttree)` to `ggtree`. Pls refer to [https://github.com/GuangchuangYu/ggtree/issues/15](https://github.com/GuangchuangYu/ggtree/issues/15).

**Comment by ajwnewkirk** [comment]
Calling reorder on ttree before ggtree() does not resolve the error on my system. It does not seem to be related to the phangorn::midpoint() call since I get the same error with

ttree <- read.tree(file = "example.tree.txt")
gtree <- ggtree(ttree, ladderize = FALSE)  # Same error with ladderize = TRUE
mytree <- gtree + geom_text(aes(label =label), hjust = -0.03)
annotation_clade2(mytree, tip1 = "C", tip2 = "D", label = "test", angle = 0, hjust = 0)

**Comment by GuangchuangYu** [comment]
I can't reproduce your issue.

**Comment by GuangchuangYu** [comment]
```r
gtree <- ggtree(ttree, ladderize = FALSE) # Same error with ladderize = TRUE
```
I thought your issue is this line. 

You are asking the `hjust` parameter, right?

Use `offset`:

```r
annotation_clade2(mytree, tip1 = "C", tip2 = "D", label = "test", angle = 0, offset=.005, offset.text=.003)
```
![screenshot 2015-11-17 19 45 51](https://cloud.githubusercontent.com/assets/626539/11210545/d609fe44-8d63-11e5-83b5-8b5d722fbedb.png)

**Comment by ajwnewkirk** [comment]
Sorry for the delay in responding. The offset and offset.text functions are helpful, but they do not seem to behave exactly the same ways as ggplot's hjust. For example, when I used hjust = 0 previously I was able to create two lines of text that were both left justified in annotation_clade2() using a text string that included a "\n" character.
