### ISSUE TITLE
Could you add some new options?

### ISSUE THREAD

**Issue by ConstantinV** [GuangchuangYu/ggtree#26]
Hello, thank you for your useful package! It really helps me in visualization of my complex data sets associated with tree!
I often use the visualization tree with associated matrix functionality. But I have some ordinary issues.
I wonder if it is possible to:
1. "Change angle of labels" (column names) in associated matrix. It will be great if you can add this to gheatmap function as a new option.
2. Add option "Show only vertical separating lines"  which divide columns in  associated matrix. It will be very useful to read complex data (associated matrix) by column manner.
3. Assign a different color scheme for a particular column.

I will be very greatful for this new features!

**Comment by GuangchuangYu** [comment]
Thanks for your suggestion.

I will consider to implement point 1.

For point 2, it's more complicated for I need to modify the source code of `ggplot2::geom_tile`.

For point 3, I don't think it's a good idea, since different color scheme for different column will make it hard to compare among columns.

**Comment by ConstantinV** [comment]
Hi! Thanks a lot! Could you let me know when it will be done?

**Comment by dmneedha** [comment]
Thanks for making ggtree, it's great! I agree with the request for "Changing angle of labels above". In the interim is there a way to ggplot2 to rotate them manually? I'm new to ggplot2, unfortunately. Thanks!

**Comment by GuangchuangYu** [comment]
I agree with @dmneedha that using `geom_text` to do it manually is more flexible. 

I have updated `ggtree` with a function, `get_heatmap_column_position`, which will output a data.frame that contains position information of where the column names should be placed. Then we can use `geom_text` to label the column name manually.

```r
beast_file <- system.file("examples/MCC_FluA_H3.tree", package="ggtree")
beast_tree <- read.beast(beast_file)
p <- ggtree(beast_tree, mrsd="2013-01-01")
p2 <- gheatmap(p, genotype, offset = 2, width=0.5, colnames=F) 
df = get_heatmap_column_position(p2, by="bottom")
p2 + geom_text(data=df, aes(x, y, label=label), nudge_y=-1, angle=45)
```

![screenshot 2015-11-25 18 03 52](https://cloud.githubusercontent.com/assets/626539/11394287/0dd8ac12-939f-11e5-80f1-a080f54c4cee.png)

**Comment by ConstantinV** [comment]
Great! Thanks!
