### ISSUE TITLE
read nhx tree files

### ISSUE THREAD

**Issue by sellisd** [GuangchuangYu/ggtree#27]
Could you add support for reading NHX formatted files? It is an extended version of the standard newick format where comments with node or branch properties are allowed, eg:
`((A[&&NHX:index=1]:1,B[&&NHX:S=2:index=2]:1):1,C[&&NHX:property=35:index=2]:1);`
The comment string is included within a `[&&NHX:` and a `]` and has a 'tag=value' format separated by semicolon in the case of multiple tags.

**Comment by GuangchuangYu** [comment]
I packed the following tree:
![screenshot 2015-11-17 15 42 54](https://cloud.githubusercontent.com/assets/626539/11205499/33d48736-8d43-11e5-8370-fc590db4a69e.png)

from [http://home.cc.umanitoba.ca/~psgendb/doc/atv/NHX.pdf](http://home.cc.umanitoba.ca/~psgendb/doc/atv/NHX.pdf) into `ggtree`.

And have updated `ggtree` to support NHX tree format.

```r
nhxfile = system.file("extdata", "ADH.nhx", package="ggtree")
x <- read.nhx(nhxfile)
ggtree(x, ladderize=F) + geom_tiplab() + geom_point(aes(color=S)) + 
    theme(legend.position="right") + geom_text(aes(label=branch.length, x=branch), vjust=-.5) + 
      xlim(NA, 0.3)
```

![screenshot 2015-11-17 14 44 33](https://cloud.githubusercontent.com/assets/626539/11205524/66f26fde-8d43-11e5-9d58-18298772275c.png)

Cheers,
