### ISSUE TITLE
Error parsing singleton nodes in rm.singleton.newick

### ISSUE THREAD

**Issue by pclangat** [GuangchuangYu/ggtree#32]
Hi, thanks for the excellent phylogenetic tree annotator. 

I am trying to read in BEAST MCC tree files (I have tested several) as newick files, however I first get the error:
Error in read.tree(nwk) : 
  The tree has apparently singleton node(s): cannot read tree file.
  Reading Newick file aborted at tree no. 1

Then applying ggtree:::rm.singleton.newick(nwk,outfile=NULL) results in another error:
Error in ggtree:::rm.singleton.newick(nwk, outfile = NULL) : 
  can't parse singleton node...

(Note that when I just call rm.singleton.newick, I get the error:
Error: could not find function "rm.singleton.newick")

Any help would be greatly appreciated. Happy to provide further information.

Pinky

**Comment by GuangchuangYu** [comment]
pls give an example that can reproduce your issue.

**Comment by pclangat** [comment]
As I re-checked the tree files that I was about to upload, I noticed the issue arises when there are '(' and ')' characters in the taxa names that are parsed as weird singletons. My apologies, all sorted now.
