### ISSUE TITLE
Hide terminal node labels.

### ISSUE THREAD

**Issue by wheelern** [GuangchuangYu/ggtree#33]
Hello,

Thank you for your ggtree package. I have a Bayesian tree with posterior probabilities used for node labels, with the outgroups collapsed to the root. 

    p <- ggtree(mbtree, layout = "circular", ndigits = 2) %>% collapse(node = 629)  +
        geom_tiplab(aes(label = label, angle=angle), size = 1, color = "steelblue", hjust = -0.1) +
        geom_text(aes(x = branch, label = prob, angle = angle), size = 1, color = "black", vjust = -1.6)

My problem is that this code labels every terminal node with 1. When annotating/labelling, is there a way to differentiate between inner nodes and terminal nodes, or to hide all terminal node annotation?

Attached is an image of what I'm dealing with.

Best,
Nic

[Rplot.pdf](https://github.com/GuangchuangYu/ggtree/files/57326/Rplot.pdf)

**Comment by GuangchuangYu** [comment]
sorry for late reply, please refer to <http://guangchuangyu.github.io/2015/09/subsetting-data-in-ggtree/>
