### ISSUE TITLE
tip labels being cut off

### ISSUE THREAD

**Issue by mav1234** [GuangchuangYu/ggtree#34]
When viewing trees with ggtree (but not with default tree viewing functionality), my tip labels appear to run off the image.  Resizing the image once it is generated doesn't fix this.  Is there any way to extend the area on which the tree is plotted such that the labels will fit?

**Comment by GuangchuangYu** [comment]
see <https://support.bioconductor.org/p/72398/>

**Comment by mav1234** [comment]
Thanks!  I got it working.  I really appreciate this addon, it has been a
great tool for tree visualization.


~John

**Comment by ChangxuFan** [comment]
A slightly more "automated" way is to add `coord_cartesian(clip="off")`, which basically prevents labels from being clipped off. source: https://stackoverflow.com/questions/17241182/how-to-make-geom-text-plot-within-the-canvass-bounds
