### ISSUE TITLE
geom_tree2 won't work with aes(color=CategoricalVAR)

### ISSUE THREAD

**Issue by GuangchuangYu** [GuangchuangYu/ggtree#36]
```r
library(ggtree)
set.seed(123)
tree=rtree(30)
tree=groupClade(tree, 34)
df=fortify(tree)
ggplot(df, aes(color=x)) + geom_tree2()
```
Mapping color to continuous variable is OK.

![screenshot 2016-01-21 19 28 34](https://cloud.githubusercontent.com/assets/626539/12479413/d4ef8728-c075-11e5-8dbb-4ace253143e1.png)

But if I try mapping to categorical variable, it won't work.

```r
ggplot(df, aes(color=group)) + geom_tree2()
```
![screenshot 2016-01-21 19 30 34](https://cloud.githubusercontent.com/assets/626539/12479451/0ce27190-c076-11e5-8531-2ff1cf1274a2.png)

The data has no problem.
```
> head(df)
  node parent branch.length        x y label isTip   branch angle group
1    1     35     0.7989248 2.410756 4   t10  TRUE 2.011294    42     1
2    2     35     0.1218993 1.733731 5   t28  TRUE 1.672781    30     1
3    3     34     0.5609480 1.730580 3   t25  TRUE 1.450106    60     1
4    4     37     0.7533079 2.211171 7   t19  TRUE 1.834517     6     0
5    5     38     0.3744628 2.727372 8   t17  TRUE 2.540140    -6     0
6    6     38     0.6651152 3.018024 9   t29  TRUE 2.685466   -18     0
```

and it works with original implementation, `geom_tree()`.
```r
ggplot(df, aes(color=group)) + geom_tree()
```
![screenshot 2016-01-21 19 30 41](https://cloud.githubusercontent.com/assets/626539/12479457/15eabcde-c076-11e5-9ab3-9a47f451bc21.png)

source code: <https://github.com/GuangchuangYu/ggtree/blob/master/R/geom_tree.R>

**Comment by hadley** [comment]
Are you sure you should be using `compute_group()` and not `compute_panel()`?

**Comment by GuangchuangYu** [comment]
@hadley  it works by using `compute_panel()`. Thank you!

**Comment by GuangchuangYu** [comment]
@hadley Sorry to bother you. I have another issue.

```r
require(ape)
require(ggtree)
x=rmtree(3, 10)
df=fortify(x)
```


```r
> head(df)
          node parent branch.length         x y label isTip    branch angle
Tree #1.1    1     13    0.03709821 0.6850552 2    t8  TRUE 0.6665061    18
Tree #1.2    2     13    0.65754318 1.3055002 3    t1  TRUE 0.9767286   -18
Tree #1.3    3     12    0.88514687 1.1904847 1   t10  TRUE 0.7479112    54
Tree #1.4    4     16    0.27829065 1.3919800 5    t3  TRUE 1.2528347   -90
Tree #1.5    5     16    0.37527841 1.4889678 6    t5  TRUE 1.3013286  -126
Tree #1.6    6     15    0.01499930 0.9624178 4    t6  TRUE 0.9549182   -36
              .id
Tree #1.1 Tree #1
Tree #1.2 Tree #1
Tree #1.3 Tree #1
Tree #1.4 Tree #1
Tree #1.5 Tree #1
Tree #1.6 Tree #1
```

`geom_tree2()` now works fine with `phylo` object, but not `multiPhylo` (a list of `phylo`). If the object is `multiPhylo`, after `fortify()` the `df` will have an additional column, `.id`.

What I expected is:
```r
ggplot(df) + geom_tree() + facet_wrap(~.id)
```
![screenshot 2016-01-22 10 57 21](https://cloud.githubusercontent.com/assets/626539/12501383/5687571c-c0f7-11e5-96ad-5fd7700ced06.png)

But `geom_tree2` only output the first panel.

```r
ggplot(df) + geom_tree2() + facet_wrap(~.id)
```
![screenshot 2016-01-22 10 57 15](https://cloud.githubusercontent.com/assets/626539/12501387/5de245b2-c0f7-11e5-9843-a87cb8ceed49.png)

The data has no problem, as I can scale the color based on `.id`.
```r
ggplot(df) + geom_tree2() + aes(color=.id)
```
![screenshot 2016-01-22 11 05 21](https://cloud.githubusercontent.com/assets/626539/12501445/1ed7dd7c-c0f8-11e5-9a11-710000656121.png)


It seems that I should write a `compute_layer()` function. I read some source code of `ggplot2`, but it is too complicated for me. Can you give me some hints?

**Comment by hadley** [comment]
`compute_panel` should take care of this for you - have you checked to verify that it's called three times?

**Comment by GuangchuangYu** [comment]
```r
geom_tree <- function(layout="rectangular", ...) {
    x <- y <- parent <- NULL
    lineend  = "round"
    if (layout == "rectangular" || layout == "fan" || layout == "circular") {
        list(
            geom_segment(aes(x    = x[parent],
                             xend = x,
                             y    = y,
                             yend = y),
                         lineend  = lineend, ...),
            
            geom_segment(aes(x    = x[parent],
                             xend = x[parent],
                             y    = y[parent],
                             yend = y),
                         lineend  = lineend, ...)
            )
    } else if (layout == "slanted" || layout == "radial" || layout == "unrooted") {
        geom_segment(aes(x    = x[parent],
                         xend = x,
                         y    = y[parent],
                         yend = y),
                     lineend  = lineend, ...)
    }
}
```
To allow subsetting (i.e. `x[parent]`) properly, I change the `parent` node number in `fortify.multiPhylo()`.

```r
fortify.multiPhylo <-  function(model, data, layout="rectangular", 
                                ladderize=TRUE, right=FALSE, mrsd=NULL, ...) {

    df.list <- lapply(model, function(x) fortify(x, layout=layout, ladderize=ladderize, right=right, mrsd=mrsd, ...))
    if (is.null(names(model))) {
        names(df.list) <- paste0("Tree ", "#", seq_along(model))
    } else {
        names(df.list) <- names(model)
    }
    df <- do.call("rbind", df.list)
    df$.id <- rep(names(df.list), times=sapply(df.list, nrow))
    df$.id <- factor(df$.id, levels=names(df.list))
    
    nNode <- sapply(df.list, nrow)
    nNode2 <- cumsum(c(0, nNode[-length(nNode)])) 
    df$parent <- df$parent + rep(nNode2, times=nNode)
    return(df)
}
```

It works fine. So it seems ggplot use the whole data frame in each panel when using `facet_wrap()`.


But for `geom_tree2`, <https://github.com/GuangchuangYu/ggtree/blob/master/R/geom_tree.R#L1-L144>, only the first panel was plotted correctly and I am sure the `compute_panel` was called three times.

I test it without modify the parent node number, and it works with `facet_warp()`

```r
fortify.multiPhylo2 <-  function(model, data, layout="rectangular", 
                                ladderize=TRUE, right=FALSE, mrsd=NULL, ...) {

    df.list <- lapply(model, function(x) fortify(x, layout=layout, ladderize=ladderize, right=right, mrsd=mrsd, ...))
    if (is.null(names(model))) {
        names(df.list) <- paste0("Tree ", "#", seq_along(model))
    } else {
        names(df.list) <- names(model)
    }
    df <- do.call("rbind", df.list)
    df$.id <- rep(names(df.list), times=sapply(df.list, nrow))
    df$.id <- factor(df$.id, levels=names(df.list))
    
    ## nNode <- sapply(df.list, nrow)
    ## nNode2 <- cumsum(c(0, nNode[-length(nNode)])) 
    ## df$parent <- df$parent + rep(nNode2, times=nNode)
    return(df)
}
```

![screenshot from 2016-01-25 00 06 32](https://cloud.githubusercontent.com/assets/626539/12537337/929ffd1a-c2f7-11e5-8bd3-dc8efa2e3efa.png)

### Q1
Why `facet_warp()` behave different with `geom_tree` (use whole data in each panel) and `geom_tree2` (use data subset in each panel)?

### Q2
Is there any way to group the data, so that ggplot()+geom_tree2() can plot the trees correctly without changing the parent node number?

**Comment by GuangchuangYu** [comment]
Q2 was solved by keeping the original parent node number un-changed with updated [`Stat`](https://github.com/GuangchuangYu/ggtree/blob/master/R/geom_tree.R#L80-L104).


Q1 is still an open question. Why the calculation procedure of `facet_wrap()` is different in `geom_tree` and `geom_tree2`?
