### ISSUE TITLE
get.offspring.tip() returns null for all nodes

### ISSUE THREAD

**Issue by ajwnewkirk** [GuangchuangYu/ggtree#37]
Very useful function in concept, but I couldn't get it to work. Looking at the source code, I have to wonder if it's not because it's basically a wrapper around ape's extract.clade(), which accepts a phylo object, while get.offspring.tip() accepts a ggtree object.

For now I'll probably run get.offspring.df() and filter out the internal nodes.

**Comment by GuangchuangYu** [comment]
example of why the function is not working?

**Comment by ajwnewkirk** [comment]
```
p <- ggtree(rtree(10)) + xlim(0, 5) + ylim(0, 11)
for(x in 1:length(p$data$node)) {
  print(get.offspring.tip(p, p$data$node[x]))
}
```

**Comment by GuangchuangYu** [comment]
the input is `phylo` object but not `ggplot` object.

```r
tree = rtree(10)
p <- ggtree(tree) + xlim(0, 5) + ylim(0, 11)
for(x in 1:length(p$data$node)) {
  print(get.offspring.tip(tree, p$data$node[x]))
}
```

**Comment by ajwnewkirk** [comment]
Thanks for your reply. I guess then that the problem really lies in the documentation - it would be helpful to emphasize that unlike most of the rest of the functions in ggtree that this function only works on phylo objects.
