### ISSUE TITLE
Add data ring(s) for circular trees

### ISSUE THREAD

**Issue by andersgs** [GuangchuangYu/ggtree#39]
It would be great to have a geom_ring to go with circular trees where at least at first binary data could be plotted (a point if data 1, and blank if 0 or empty). I assume it would use much the similar code used to calculate were to plot tip labels (perhaps something like this: https://medicine.tcd.ie/clinical_microbiology/research/murphy.php).

Ideally, we would be able to add multiple geom_rings to a single ggtree, each offset by a bit.

Or, even more ambitious would be to have a circular ggheatmap function.

Thank you.

Anders.

**Comment by GuangchuangYu** [comment]
`gheatmap` can be in circular form by `+coord_polar(theta='y')`.

Similar to circular form of `msaplot`, see http://guangchuangyu.github.io/ggtree/advanceTreeAnnotation.html

**Comment by andersgs** [comment]
Thank you. I had not seen the updated vignette. Excellent stuff!!
