### ISSUE TITLE
color tree

### ISSUE THREAD

**Issue by XinpengQi** [GuangchuangYu/ggtree#41]
cls <- list(c1=c("A", "B", "C", "D", "E"),
            c2=c("F", "G", "H"),
            c3=c("L", "K", "I", "J"),
            c4="M")

tree <- groupOTU(tree, cls)
library("colorspace")
ggtree(tree, aes(color=group, linetype=group)) + geom_text(aes(label=label),  hjust=-.25) +
     scale_color_manual(values=c("black", rainbow_hcl(4))) + theme(legend.position="right")

works well. However, I wanna to design the color for each group, how shall I designate color for each group?
eg: i wanna all the blue color in following group goes to gray. 
![image](https://cloud.githubusercontent.com/assets/15131363/12829064/1a348fa0-cb56-11e5-8a52-cf44c0eb3ec4.png)

**Comment by XinpengQi** [comment]
actually I was using group OTUs and I define a cls contains three different c (c1,c2 and c3). 
I am asking how to color different c using specific color, for example, I wanna c1 red, c2 blue, and c3 gray. 

thanks a lot

**Comment by GuangchuangYu** [comment]
use `scale_color_manual` to specify the color.

```r
require(ggtree)
nwk <- system.file("extdata", "sample.nwk", package="ggtree")
tree <- read.tree(nwk)
cls <- list(c1=c("A", "B", "C", "D", "E"),
            c2=c("F", "G", "H"),
            c3=c("L", "K", "I", "J"),
            c4="M")

tree <- groupOTU(tree, cls)
ggtree(tree, aes(color=group)) + scale_color_manual(values=c('black', 'red', 'blue', 'green', 'purple'))
```

**Comment by XinpengQi** [comment]
thank you very much for your help!
happy chinese spring festival!

2016-02-06 5:24 GMT-05:00 Guangchuang Yu <notifications@github.com>:

> use scale_color_manual to specify the color.
>
> require(ggtree)nwk <- system.file("extdata", "sample.nwk", package="ggtree")tree <- read.tree(nwk)cls <- list(c1=c("A", "B", "C", "D", "E"),
>             c2=c("F", "G", "H"),
>             c3=c("L", "K", "I", "J"),
>             c4="M")
> tree <- groupOTU(tree, cls)
> ggtree(tree, aes(color=group)) + scale_color_manual(values=c('black', 'red', 'blue', 'green', 'purple'))
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GuangchuangYu/ggtree/issues/41#issuecomment-180731909>
> .
>



-- 
Xinpeng QI
