### ISSUE TITLE
msaplot with sequence letters?

### ISSUE THREAD

**Issue by SLeviyang** [GuangchuangYu/ggtree#42]
Not sure if the following can be done currently with ggtree:

I want to annotate a tree with the tip sequences, but I want to see the letters of the sequences rather than just the colors.  Right now I do

p <- ggtree(t) + geom_tiplab(size=tip_size) + geom_tippoint(size=3) + geom_treescale()
msaplot(p, "tmp.fasta")

where tmp.fasta is the fasta file.  But these lines just show colors and I want the letters.  I have short sequences of 30 letters, so visually this would be meaningful.

**Comment by GuangchuangYu** [comment]
this feature is currently not supported.

**Comment by SLeviyang** [comment]
is there any way I could code this myself?  If I could extract the x and y position of the tips, then I could add a geom_text layer to my plot with the sequence letters, but I don't know how to access the plot locations of the tips.

**Comment by yangjr** [comment]
maybe take a look at p$data ?

**Comment by GuangchuangYu** [comment]
yes, use `p$data` to access the position.

**Comment by SLeviyang** [comment]
Thanks for the pointer to p$data.  I found a quick fix by listing
haplotypes through the legend, but perhaps at some point I'll use p$data to
list the sequences through a layer on the plot.  Thanks for ggtree, it's
very helpful!

Best,
Sivan

**Comment by ProustIdee** [comment]
Just adding that I think this would be a useful feature.
