### ISSUE TITLE
Add functionality for ape plot options for "fan" shaped plot - open.angle and rotate.tree

### ISSUE THREAD

**Issue by PeteCowman** [GuangchuangYu/ggtree#43]
Hi!
It would be great if ggtree would allow you to rotate and open up a fan/circular tree layout like in ape
here is some rough code to plot some examples

##################################
library(ape)
library(geiger) # to access whales data
data("whales")
tr = whales$phy # select whales tree
old.par <- par(mfrow=c(1, 3)) # grid plots
plot(tr, show.tip.label = FALSE, type = "f")
title(main = "Orignal")
plot(tr, show.tip.label = FALSE, type = "f", open.angle = 20, rotate.tree = 10) 
axisPhylo()
title(main = "Rotate & Open for axis")
plot(tr, show.tip.label = FALSE, type = "f", open.angle = 180) 
title(main = "Open to 180 degrees")
par(old.par)
###################################

the first plot is the original, the second is where open.angle and rotate.tree are used so axis.phylo() can be used. the third plot is where open.angle is used to plot the tree as a semicircle.

Thank you for your help and for developing/maintaining/expanding this great package!

**Comment by GuangchuangYu** [comment]
## `fan` layout & `open_tree` function

`fan` layout was supported.
```r
require(ggtree)
set.seed(123)
tr = rtree(50)

for (angle in seq(0, 270, 10)) {
	print(ggtree(tr, layout='fan', open.angle=angle) + geom_tiplab2() + ggtitle(paste("open angle:", angle)))
}
```

![fan_layout](https://cloud.githubusercontent.com/assets/626539/15211247/cede38c6-186c-11e6-86fd-6a7288046e0c.gif)

You can make the `fan` tree after the tree was generated by `ggtree` by `open_tree` function.
```r
open_tree(ggtree(tr), 60)
```

## `rotate_tree` function


Tree can be rotated by specifying an angle.

```r
p <- ggtree(tr) + geom_tiplab2()
for (angle in seq(0, 270, 10)) {
	print(rotate_tree(p, angle) + ggtitle(paste("rotate angle:", angle)))
}
```

![rotate_tree](https://cloud.githubusercontent.com/assets/626539/15211248/d0ea9d08-186c-11e6-9628-977fd47edc06.gif)
