### ISSUE TITLE
Tip did not display properly

### ISSUE THREAD

**Issue by maolun** [GuangchuangYu/ggtree#44]
Hi Guangchuang,

Thanks for introducing such a nice R package.  

I was importing a codeml file. Everything works fine except the tips did not display properly, as the screen shot shows, the tip names were chopped. Am I missing something?

ggtree(mlc, branch.length="none") + geom_text2(aes(subset=!isTip, label=node), hjust=-.3) + geom_tiplab()

![2016-02-16 10 59 55 pm](https://cloud.githubusercontent.com/assets/5767686/13099538/23a52518-d501-11e5-92bc-bfcb42ca6a0c.png)

Best,
Mao-Lun

**Comment by GuangchuangYu** [comment]
see <https://github.com/GuangchuangYu/ggtree/wiki/FAQ#tip-label-truncated>

**Comment by maolun** [comment]
Guangchuang, Thanks

**Comment by mcrillo** [comment]
Hello! I could not find the answer to this - I am having the same problem.
Thank you!

**Comment by timosong** [comment]
There is no answer to this, the solution to the page is broken

**Comment by brj1** [comment]
https://guangchuangyu.github.io/ggtree/faq/
