### ISSUE TITLE
Tip did not display properly

### ISSUE THREAD

**Issue by maolun** [GuangchuangYu/ggtree#45]
Hi Guangchuang,

Thanks for providing this awesome R package. 

I was trying to display a tree output from PAML, but the tip did not display properly. Below is my code. Am I missing something? 

tr2<-ggtree(mlc, branch.length="none") + geom_tiplab()

![2016-02-16 10 59 55 pm](https://cloud.githubusercontent.com/assets/5767686/13116112/a789ccd2-d568-11e5-86b9-3091b20420ad.png)

Thanks,
Mao-Lun

**Comment by GuangchuangYu** [comment]
duplicate, see <https://github.com/GuangchuangYu/ggtree/issues/44>
