### ISSUE TITLE
Feature request: annotate_image() geom

### ISSUE THREAD

**Issue by ajwnewkirk** [GuangchuangYu/ggtree#46]
Annotate_image() works well for adding custom icons to tree tips, but I would like to be able to create a ggplot legend for icons that I map to tree tips based on some column in the tree$data data frame. For example, if I create a tree of bacterial isolates, I might map isolate subtype to the tip label color and the source of the isolate to a set of custom icons. I have examined the source code for annotate_image() and geom_tiplab(), but I do not know enough about custom geoms and rasterGrob manipulation to see how to create this hybrid myself. 

You might also consider changing annotate_image() so that the offset parameter has an effect when align = FALSE. Setting `xmin <- x - width/2 + offset` made my trial tree plots look much nicer than having the center of the icon at the end of the branch.

Your work on this package is much appreciated - it's completely changed for the better how I plot trees in R.

**Comment by GuangchuangYu** [comment]
>I might map isolate subtype to the tip label color and the source of the isolate to a set of custom icons.

do it separately.

>xmin <- x - width/2 + offset

this was fixed.
