### ISSUE TITLE
feature request: phylo4d compatibility

### ISSUE THREAD

**Issue by ashenkin** [GuangchuangYu/ggtree#47]
Hi there,

Really liking ggtree - thanks so much for a great tool.  One question - have you considered supporting phylo4d objects?  Seems like it would be a natural fit for ggtree.  As it stands, I seem to have to use data outside of aes() clauses for things like geom_tippoint, as it looks for an object with rows = # of nodes (not just number of tips).  Additionally, I have to be wary of the ordering of data matching that of the ordering of the tips of the original tree, etc.

phylo4d, i think, was created to solve these issues.  Perhaps there are other ways of going about this that solve these issues without phylo4d...  Any thoughts much appreciated.  Thanks!

**Comment by GuangchuangYu** [comment]
```r
require(phylobase)
set.seed(123)
tr = rtree(30)
g1 = as(tr, 'phylo4')
d = data.frame(color=sample(c('red', 'blue', 'green'), 30, replace=T))
rownames(d) = tr$tip.label
g2 = phylo4d(g1, d)

require(ggtree)
ggtree(g2) + geom_tippoint(aes(color=I(color)))
```

![screenshot 2016-05-10 17 13 14](https://cloud.githubusercontent.com/assets/626539/15141415/80c9963a-16d2-11e6-961d-616f3ac152b8.png)

it was supported in ggtree >= 1.5.2

**Comment by ashenkin** [comment]
This is great!  Thanks so much.  It seems to largely work.  I'm just coming across an issue of passing colors to node points.  I can add variable size node points, but they disappear when I try to color them.  Any thoughts?

```require(phylobase)
require(ggtree)

set.seed(123)
tr = rtree(30)
g1 = as(tr, 'phylo4')
d = data.frame(color=sample(c('red', 'blue', 'green'), 30, replace=T))
rownames(d) = tr$tip.label
g2 = phylo4d(g1, d)

ggtree(g2) + geom_tippoint(aes(color=I(color)))

rNodeData <- data.frame(randomTrait = rnorm(nNodes(g1)),
                        color = rainbow(n = nNodes(g1)),
                        row.names = nodeId(g1, "internal"))

nodeData(g2) <- rNodeData

ggtree(g2) + geom_tippoint(aes(color=I(color))) + geom_nodepoint(aes(size = randomTrait, color = I(color)))```

![rplot](https://cloud.githubusercontent.com/assets/1608945/15210975/c6931f06-1830-11e6-927e-66136ce3077d.png)

**Comment by GuangchuangYu** [comment]
thanks for your feedback 👍

**Comment by GuangchuangYu** [comment]
it can be done using `%<+%` operator to attach user's data.
```r
require(ggtree)

set.seed(123)
tr = rtree(30)
g1 = as(tr, 'phylo4')
d = data.frame(lab=tr$tip.label, color=sample(c('red', 'blue', 'green'), 30, replace=T))

p <- ggtree(g1) %<+% d + geom_tippoint(aes(color=I(color)))

rNodeData <- data.frame(node = nodeId(g1, "internal"), 
						randomTrait = rnorm(nNodes(g1)),
                        color2 = sample(c('purple', 'yellow', 'black'), nNodes(g1), replace=T)
                        )


p %<+% rNodeData  + geom_nodepoint(aes(size = randomTrait, color = I(color2)))
```

![screenshot 2016-05-12 18 59 31](https://cloud.githubusercontent.com/assets/626539/15212523/c977779c-1873-11e6-83a5-fbe29e59ea20.png)


This `phylo4d` solution is a very good alternative.

In `ggtree`, we also provide another solution, that is to merge the newick tree text with user's data to a single jplace file and then parse the file in `ggtree` and visualize it with user's data.
