### ISSUE TITLE
gheatmap issues

### ISSUE THREAD

**Issue by maziz2** [GuangchuangYu/ggtree#48]
Hi 

I am trying to use gheatmap and create a heatmap with just one variable. Its crashing. can you please let me know if it works for you.
Also i am using this code and the error. Can you please tell me what the error means so that i can fix the inputs 
> genotype1 <- read.table("hh_heatmap.txt", sep="\t", stringsAsFactor=F,  header = TRUE)
> gheatmap(p, genotype1)
Error in if (any(dd$value == "")) { : 
  missing value where TRUE/FALSE needed

**Comment by maziz2** [comment]
So about the error i was seeing below.. 
I had two nodes that were incorrectly spelled in my heatmap file. since i have one column/variable only it was crashing so i could not decipher the error. when i introduced a second dummy column 'check'  which had all values populated and said 'test' it started giving the error above in my earlier post (TRUE/FALSE one). then when i just removed a few of the values in the test column i started getting the heatmap. 
there is a bug somewhere.. hope my explanation helps. 

thanks

**Comment by GuangchuangYu** [comment]
pls send me a sample data with R script to reproduce your issue.
