### ISSUE TITLE
ggtree Error: argument "form" is missing with no default

### ISSUE THREAD

**Issue by christianbentz** [GuangchuangYu/ggtree#49]
Hi Guangchuang,

I installed the ggtree package via biocLite("ggtree") on Ubuntu 14.04 with R 3.2.3. When I use your example in the vignette for ggtree():

require(ape)
tr <- rtree(10)
ggtree(tr)

I get an error saying:

"Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
Error in ggtree(tr) : argument "form" is missing, with no default"

I have no clue why this occurs, especially since "form" is not an argument in the ggtree() function.

Thanks for your efforts so far, any help would be greatly appreciated.

Cheers,
Chris

**Comment by christianbentz** [comment]
Update: I see in the function code that it is actually an argument, though not listed in the vignette. However, if I choose form="ladder", then I get an error:

Error in phytheme_() : could not find function "opts"

Cheers,
Chris

**Comment by GuangchuangYu** [comment]
there is indeed no `form` argument, see <https://github.com/GuangchuangYu/ggtree/search?utf8=%E2%9C%93&q=form>

**Comment by christianbentz** [comment]
Thanks for your quick reply. I realized that I had loaded an older ggtree function from 2011, which did not get overwritten when I installed the newer version. "form" was still an argument there. 
Thanks again, great package!
