### ISSUE TITLE
factor handling in geom_tree

### ISSUE THREAD

**Issue by vbonhomme** [GuangchuangYu/ggtree#5]
hi there,

thanks for your amazing package!
I think that if you turn this line (and possibly for other aes) in `geom_tree` : 
`color <- c(color, color)` into `color <- rep(color, 2)` we could directly pass factors to geom_tree (as their column names on the data.frame (or the data.frame resulting from the as.data.frame on the phylo objects). `c` function converts factors into numeric while `rep` retains the class.

all the best,
v

**Comment by GuangchuangYu** [comment]
updated. Thanks for your suggestion.

**Comment by GuangchuangYu** [comment]
FYI:

thanks to the new implementation of `geom_tree`, color parameter was removed from `geom_tree`.
