### ISSUE TITLE
Trying to add a SINGLE circular ring to a tree

### ISSUE THREAD

**Issue by jsilve24** [GuangchuangYu/ggtree#52]
First off, thank you for creating this wonderful package!

I am trying to add a color strip ([in the style of iTOL](http://itol.embl.de/help.cgi#strip)) to my circular tree. I currently just want to define a single variable "phylum" as the coloring for that ring/heatmap. 
(1) this gives an error as I think gheatmap only expects to get a dataframe with more than 1 column. (The rownames of my dataframe line up with tip labels of the tree). 
(2) I agree with andersgs (#39), I think this may deserve its own function (e.g., geom_ring or geom_strip). I find the current method awkward.

I think (1) is more important than (2) obviously.

So far this is the best I have been able to come up with. I have had to double one of the columns and shrink the width. I also notice the color is washed out (looks like low alpha) which I think is because there are so many taxa and the cell borders are getting in the way. 

![rplot](https://cloud.githubusercontent.com/assets/452422/14061894/10b39de2-f363-11e5-8f83-2ef7cf9e938d.png)

Again I think iTOL like functionality would be wonderful for this type of comparative genomics.

**Comment by GuangchuangYu** [comment]
how about this trick:
```r
library(ggtree)
set.seed(1234)
tr=rtree(50)
ggtree(tr) + geom_strip(58, color='red') + geom_strip(84, color='green') + geom_strip(52, color='blue')
```

**Comment by GuangchuangYu** [comment]
![screenshot from 2016-04-07 00 01 24](https://cloud.githubusercontent.com/assets/626539/14323656/ef35ac1a-fc53-11e5-98f0-4c7b5ede89d9.png)

**Comment by jsilve24** [comment]
This sort of addresses the problem. However I am still not sure how to deal with this as my data relates tip labels to phyla. Thus I first have to find the MRCA of a given phyla however often its not mono-phyletic. Therefore the results are incorrect. 

It would be easier if I could use the %<+%  opperator to associate the phyla names to the tips and then just call a geom_strip function.

**Comment by jsilve24** [comment]
So I found a workaround - a package called [MonoPhy](https://peerj.com/articles/cs-56.pdf) that will estimate the MRCA despite non monophyletic clades. So I can use that...  Its a pretty big work around though, it would be much easier if you could just associate a color with the tips as a bar.

**Comment by GuangchuangYu** [comment]
![2016-05-09-235143_1280x800_scrot](https://cloud.githubusercontent.com/assets/626539/15118950/163c387c-1641-11e6-891c-9f2a6fc07e34.png)

it's supported in ggtree >= 1.5.1

it's similar to geom_cladelabel, except that"
+ the input is not internal node number but taxa1 and taxa2. 
+ label is optional.

**Comment by GuangchuangYu** [comment]
wow, just realize you request a pull. Thanks, I will review your code tomorrow.

**Comment by jsilve24** [comment]
I think I like your solution with geom_strip much better for my research! That said the pull request may be helpful as it fixes what i would consider a small bug with gheatmap function. 


Thank you again for the wonderful work you are doing!
- Justin

**Comment by GuangchuangYu** [comment]
merged & thanks
