### ISSUE TITLE
geom_hilight does not highlight tips

### ISSUE THREAD

**Issue by jsilve24** [GuangchuangYu/ggtree#53]
It would be nice if the default behavior of geom_hilight when given a tip acctually highlighted the tip (up until the parent node). 

As far as I can tell there is no way to get that hilight 'box' around a tip. 

If you don't want to add this as the default behavior could you comment on how I could get the geom_hilight 'like' box around a tip (up till where it meets the parent node)?

Thanks!

**Comment by GuangchuangYu** [comment]
it was supported in ggtree >= 1.5.2
