### ISSUE TITLE
read.nhx hangs

### ISSUE THREAD

**Issue by caseywdunn** [GuangchuangYu/ggtree#54]
`read.nhx()` hangs when reading a file with the following content (produced by notung 2.8):

    ((((Marrus_claudanielis@2022357:0.060965505130934[&&NHX:S=Marrus_claudanielis:Nset=<Marrus_claudanielis>:H=N],(Agalma_elegans@84409:0.15171099773811814[&&NHX:S=Agalma_elegans:Nset=<Agalma_elegans>:H=N],(((Frillagalma_vityazi@645147:0.43750026535442[&&NHX:S=Frillagalma_vityazi:Nset=<Frillagalma_vityazi>:H=N],Resomia_ornicephala@2736260:0.09000493261712034[&&NHX:S=Resomia_ornicephala:Nset=<Resomia_ornicephala>:H=N])n1838392[&&NHX:S=n48:Nset=<Resomia_ornicephala@Frillagalma_vityazi>:H=N:D=N],Frillagalma_vityazi@594863:0.17862992275841028[&&NHX:S=Frillagalma_vityazi:Nset=<Frillagalma_vityazi>:H=N])n1838394[&&NHX:S=n48:Nset=<Resomia_ornicephala@Frillagalma_vityazi>:H=N:D=Y],Cordagalma_sp_@1167998:0.3604880577978687[&&NHX:S=Cordagalma_sp_:Nset=<Cordagalma_sp_>:H=N])n1838396[&&NHX:S=n49:Nset=<n45@n48>:H=N:D=N])n1838421[&&NHX:S=n49:Nset=<n48@n45>:H=N:D=Y])n1838419[&&NHX:S=n57:Nset=<n56@n49>:H=N:D=N],(((Bargmannia_amoena@3412598:0.008122408482557327[&&NHX:S=Bargmannia_amoena:Nset=<Bargmannia_amoena>:H=N],Bargmannia_elongata@506610:0.01601277799970084[&&NHX:S=Bargmannia_elongata:Nset=<Bargmannia_elongata>:H=N])n1838399[&&NHX:S=n19:Nset=<Bargmannia_elongata@Bargmannia_amoena>:H=N:D=N],Bargmannia_lata@3713667:0.03227893766833111[&&NHX:S=Bargmannia_lata:Nset=<Bargmannia_lata>:H=N])n1838401[&&NHX:S=n21:Nset=<n19@Bargmannia_lata>:H=N:D=N],Apolemia_lanosa@3488217:0.5234036022810353[&&NHX:S=Apolemia_lanosa:Nset=<Apolemia_lanosa>:H=N])n1838403[&&NHX:S=n60:Nset=<n16@n59>:H=N:D=N])n1838417[&&NHX:S=n60:Nset=<n16@n59>:H=N:D=Y],(((((Kephyes_ovata@1963335:0.016383558542684848[&&NHX:S=Kephyes_ovata:Nset=<Kephyes_ovata>:H=N],Chuniphyes_multidentata@881201:0.017869278977945918[&&NHX:S=Chuniphyes_multidentata:Nset=<Chuniphyes_multidentata>:H=N])n1838406[&&NHX:S=n24:Nset=<Kephyes_ovata@Chuniphyes_multidentata>:H=N:D=N],Prayidae_D27D2@2851258:0.05834725045938479[&&NHX:S=Prayidae_D27D2:Nset=<Prayidae_D27D2>:H=N])n1838408[&&NHX:S=n36:Nset=<n35@n30>:H=N:D=N],Prayidae_D27SS7@2209288:0.056684129487865116[&&NHX:S=Prayidae_D27SS7:Nset=<Prayidae_D27SS7>:H=N])n1838410[&&NHX:S=n36:Nset=<n35@n30>:H=N:D=Y],Prayidae_D27D2@2851259:0.09653430222119663[&&NHX:S=Prayidae_D27D2:Nset=<Prayidae_D27D2>:H=N])n1838412[&&NHX:S=n36:Nset=<n35@n30>:H=N:D=Y],Hippopodius_hippopus@1009705:0.2788572385390526[&&NHX:S=Hippopodius_hippopus:Nset=<Hippopodius_hippopus>:H=N])n1838414[&&NHX:S=n36:Nset=<n35@n30>:H=N:D=Y])n1838416:0.929129623712816[&&NHX:S=n60:Nset=<n16@n59>:H=N:D=Y],Hydractinia_symbiolongicarpus@1714529:0.929129623712816[&&NHX:S=Hydractinia_symbiolongicarpus:Nset=<Hydractinia_symbiolongicarpus>:H=N])n1839683[&&NHX:S=n62:Nset=<n61@n8>:H=N:D=N];

**Comment by GuangchuangYu** [comment]
`read.nhx()` hangs when reading your nhx tree due to it contains missing values of edge length.

I have update the source to tackle this situation.

```r
> x='((((Marrus_claudanielis@2022357:0.060965505130934[&&NHX:S=Marrus_claudanielis:Nset=<Marrus_claudanielis>:H=N],(Agalma_elegans@84409:0.15171099773811814[&&NHX:S=Agalma_elegans:Nset=<Agalma_elegans>:H=N],(((Frillagalma_vityazi@645147:0.43750026535442[&&NHX:S=Frillagalma_vityazi:Nset=<Frillagalma_vityazi>:H=N],Resomia_ornicephala@2736260:0.09000493261712034[&&NHX:S=Resomia_ornicephala:Nset=<Resomia_ornicephala>:H=N])n1838392[&&NHX:S=n48:Nset=<Resomia_ornicephala@Frillagalma_vityazi>:H=N:D=N],Frillagalma_vityazi@594863:0.17862992275841028[&&NHX:S=Frillagalma_vityazi:Nset=<Frillagalma_vityazi>:H=N])n1838394[&&NHX:S=n48:Nset=<Resomia_ornicephala@Frillagalma_vityazi>:H=N:D=Y],Cordagalma_sp_@1167998:0.3604880577978687[&&NHX:S=Cordagalma_sp_:Nset=<Cordagalma_sp_>:H=N])n1838396[&&NHX:S=n49:Nset=<n45@n48>:H=N:D=N])n1838421[&&NHX:S=n49:Nset=<n48@n45>:H=N:D=Y])n1838419[&&NHX:S=n57:Nset=<n56@n49>:H=N:D=N],(((Bargmannia_amoena@3412598:0.008122408482557327[&&NHX:S=Bargmannia_amoena:Nset=<Bargmannia_amoena>:H=N],Bargmannia_elongata@506610:0.01601277799970084[&&NHX:S=Bargmannia_elongata:Nset=<Bargmannia_elongata>:H=N])n1838399[&&NHX:S=n19:Nset=<Bargmannia_elongata@Bargmannia_amoena>:H=N:D=N],Bargmannia_lata@3713667:0.03227893766833111[&&NHX:S=Bargmannia_lata:Nset=<Bargmannia_lata>:H=N])n1838401[&&NHX:S=n21:Nset=<n19@Bargmannia_lata>:H=N:D=N],Apolemia_lanosa@3488217:0.5234036022810353[&&NHX:S=Apolemia_lanosa:Nset=<Apolemia_lanosa>:H=N])n1838403[&&NHX:S=n60:Nset=<n16@n59>:H=N:D=N])n1838417[&&NHX:S=n60:Nset=<n16@n59>:H=N:D=Y],(((((Kephyes_ovata@1963335:0.016383558542684848[&&NHX:S=Kephyes_ovata:Nset=<Kephyes_ovata>:H=N],Chuniphyes_multidentata@881201:0.017869278977945918[&&NHX:S=Chuniphyes_multidentata:Nset=<Chuniphyes_multidentata>:H=N])n1838406[&&NHX:S=n24:Nset=<Kephyes_ovata@Chuniphyes_multidentata>:H=N:D=N],Prayidae_D27D2@2851258:0.05834725045938479[&&NHX:S=Prayidae_D27D2:Nset=<Prayidae_D27D2>:H=N])n1838408[&&NHX:S=n36:Nset=<n35@n30>:H=N:D=N],Prayidae_D27SS7@2209288:0.056684129487865116[&&NHX:S=Prayidae_D27SS7:Nset=<Prayidae_D27SS7>:H=N])n1838410[&&NHX:S=n36:Nset=<n35@n30>:H=N:D=Y],Prayidae_D27D2@2851259:0.09653430222119663[&&NHX:S=Prayidae_D27D2:Nset=<Prayidae_D27D2>:H=N])n1838412[&&NHX:S=n36:Nset=<n35@n30>:H=N:D=Y],Hippopodius_hippopus@1009705:0.2788572385390526[&&NHX:S=Hippopodius_hippopus:Nset=<Hippopodius_hippopus>:H=N])n1838414[&&NHX:S=n36:Nset=<n35@n30>:H=N:D=Y])n1838416:0.929129623712816[&&NHX:S=n60:Nset=<n16@n59>:H=N:D=Y],Hydractinia_symbiolongicarpus@1714529:0.929129623712816[&&NHX:S=Hydractinia_symbiolongicarpus:Nset=<Hydractinia_symbiolongicarpus>:H=N])n1839683[&&NHX:S=n62:Nset=<n61@n8>:H=N:D=N];'
> file=tempfile()
> writeLines(x, file)
> y=read.nhx(file)
Warning message:
In as.data.frame.phylo_(x, layout, ...) :
  'edge.length' contains NA values...
 ## setting 'edge.length' to NULL automatically when plotting the tree...
> y@phylo$edge.length
 [1] 0.929129624          NA          NA 0.060965505          NA 0.151710998
 [7]          NA          NA          NA 0.437500265 0.090004933 0.178629923
[13] 0.360488058          NA          NA          NA 0.008122408 0.016012778
[19] 0.032278938 0.523403602          NA          NA          NA          NA
[25]          NA 0.016383559 0.017869279 0.058347250 0.056684129 0.096534302
[31] 0.278857239 0.929129624
```

The edge length will stored in the object as it is, but if you want to visualize the tree, the edge length will be dropped and only tree topology will be shown.

**Comment by caseywdunn** [comment]
That's great - thanks for your quick response to this.
