### ISSUE TITLE
feature request: gheatmap extension for other types of ggplots

### ISSUE THREAD

**Issue by ONeillMB1** [GuangchuangYu/ggtree#59]
Thank you so much for developing ggtree! I would like to pair a geom_segment() plot with a tree in a similar manner as to what you have developed with gheatmap. Thus, rather than the underlying function being geom_tile() it would be a geom_segment() plot with a discrete y scale consisting of the sample names. Is this possible?

**Comment by GuangchuangYu** [comment]
yes, it's possible.

You can use the `geom_segment2`.

**Comment by GuangchuangYu** [comment]
BTW: if you want to do something not presented in the vignette, you would better draw a figure to display what you want, take a photo and then upload it here. Since I am not sure what you want to achieve

**Comment by ONeillMB1** [comment]
@GuangchuangYu - Here is what I would like to achieve. Essentially it would be what you have in the vignette for combining a heatmap with a tree:
![image](https://cloud.githubusercontent.com/assets/5341397/15251842/e010b752-18f0-11e6-9b2a-4a488871e1e1.png)

But instead of a heatmap I want to use a ggplot where the y-axis is discrete and corresponds the the tip.labels of my tree:
my ggplot:
![image](https://cloud.githubusercontent.com/assets/5341397/15251872/0b91c0c4-18f1-11e6-9097-151bf1459f7d.png)
tree:
![image](https://cloud.githubusercontent.com/assets/5341397/15251898/25e88d40-18f1-11e6-9749-ab25982cb149.png)

In the vignette this is achieved with `r gheatmap(p, genotype, offset = 2, width=0.5)`.

**Comment by ONeillMB1** [comment]
@GuangchuangYu - I was more or less able to achieve the desired plot following the 'Align tree with other plots on a page' portion of your 'Advanced Tree Annotation' vignette:
![image](https://cloud.githubusercontent.com/assets/5341397/15254226/60a106c4-18fb-11e6-9d3b-85130bbc6637.png)

Now I've just got to fiddle with it a bit to add the blue lines (geom_rect) back to the plot on the right!

**Comment by GuangchuangYu** [comment]
@ONeillMB1 that's really awesome.
