### ISSUE TITLE
'cophyloplot' equivalent function

### ISSUE THREAD

**Issue by Puriney** [GuangchuangYu/ggtree#594]
### Prerequisites

+ [x] Have you read [Feedback](https://guangchuangyu.github.io/ggtree/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [ ] make sure your are using the latest release version
	* [ ] read the [documents](https://yulab-smu.github.io/treedata-book/)
	* [ ] google your question/issue

### Describe you issue

* [ ] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [ ] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [x] for bugs or feature requests, post here (github issue)
* [ ] for questions, please post to [google group](https://groups.google.com/forum/#!forum/bioc-ggtree)

---

Hello ggtree team, 
This is Yun. This is a 'feature request'. I was wondering if you could provide a function equivalent to `ape::cophyloplot`, which can compare and viz two phylo tree side-by-side. 

Many thanks.

**Comment by brj1** [comment]
Though it is not particularly neat, there is a tutorial in Yu's book on how to make cophylo plots with ggtree.

https://yulab-smu.top/treedata-book/chapter2.html#ggtree-fortify

**Comment by Puriney** [comment]
Many thanks.
