### ISSUE TITLE
non overlapping branches for layout="fan" || radial

### ISSUE THREAD

**Issue by vbonhomme** [GuangchuangYu/ggtree#6]
me again,
if you add a `scale_y_continuous` after the current line 61 in ggtree, we can have non overlapping branches for those two `coord_polar`-ized layouts

eg:

`p <- p + scale_y_continuous(limits=c(0, sum(p$data$isTip)))`

**Comment by GuangchuangYu** [comment]
thank. see https://github.com/GuangchuangYu/ggtree/commit/294e0640280fdec58f288501c6726cc77e4c0598
