### ISSUE TITLE
small clusterprofiler idea/request

### ISSUE THREAD

**Issue by abelew** [GuangchuangYu/ggtree#60]
Greetings,
  Something I am working to implement for myself that you might be able to beat me to completion:
  Given an initial gse/enrich/etc analysis with a p/q cutoff = 1.0 so that it is possible to simply see the population of categories, take the returned object and perform a subset on it using a chosen p/q value.

**Comment by GuangchuangYu** [comment]
should post to <https://github.com/GuangchuangYu/clusterProfiler/issues>.

**Comment by abelew** [comment]
Hi,
  Sorry for the trouble, I merely followed the link at the bottom of:
https://github.com/GuangchuangYu/clusterProfiler
