### ISSUE TITLE
Problems with geom_hilight for circular layout

### ISSUE THREAD

**Issue by SonjaLehtinen** [GuangchuangYu/ggtree#62]
This is a really nice plotting tool!

I'm trying to use geom_hilight to highlight clades on a circular tree. For example:

> ggtree(tree,layout='circular')+
>      geom_hilight(node=1040, fill='blue', alpha=.3)

This works well most of the time, but for some clades I get the following warning and no colour is added to the tree:
> Warning message:
> Removed 1 rows containing missing values (geom_rect).
The same command runs fine using a rectangular layout and colours the appropriate clade.

Do you know what might be going wrong? Thanks for your help!

Sonja

**Comment by GuangchuangYu** [comment]
give me the tree and source code to reproduce your issue.

**Comment by SonjaLehtinen** [comment]
```
tree = read.tree('tree')
ggtree(tree,layout='circular')+ 
geom_hilight(node=1080)
```

[tree.txt](https://github.com/GuangchuangYu/ggtree/files/316716/tree.txt)


Thanks!

**Comment by GuangchuangYu** [comment]
this is an old issue that was removed in current release of ggtree, see <https://github.com/GuangchuangYu/ggtree/issues/40>.

You need to update your ggtree to up-to-date release version, <https://www.bioconductor.org/packages/ggtree/>.
