### ISSUE TITLE
Adding a geom_balance to ggtree

### ISSUE THREAD

**Issue by jsilve24** [GuangchuangYu/ggtree#63]
I have been making extensive use of ggtree in my work (its wonderful). I are about to release an R package for microbiome data analysis as we submit for publication. In our package I currently have implemented a new geom (`geom_balance`) that I think would actually make more sense to include in ggtree rather than my R package (which will be on CRAN most likely). 

I have based `geom_balance` off of `geom_hilight`. Importantly it adds functionality that was difficult to achieve with `geom_hilight` as `geom_balance` is better set up for comparing sister clades (e.g., it naturally sets the xmax of the two highlights to be equal - see example below and error messages regarding whether something is a tip or not are more appropriate). 

On [my fork of ggtree](https://github.com/jsilve24/ggtree/tree/feature_geom_balance) I have implemented `geom_balance` as well as updating the treeAnnotation.Rmd vignette to demonstrate its use (image below). If this is something you would agree to include in ggtree I can submit a pull request in the next day or so. Currently the package builds and passes checks without errors. 

Let me know, 
Thank you again, 
Justin Silverman

![screenshot](https://cloud.githubusercontent.com/assets/452422/16243354/dbfccabe-37c4-11e6-8b40-470768d6e243.png)

**Comment by GuangchuangYu** [comment]
this seems quite useful, pls go ahead to submit a pull request.

Thanks for your contribution.

**Comment by jsilve24** [comment]
I believe the merge closed this issue.
