### ISSUE TITLE
Error in Ntip(phylo) : object "phy" is not of class "phylo"

### ISSUE THREAD

**Issue by carl-** [GuangchuangYu/ggtree#68]
I get an error when reading nhx file.
if I read this file via read.tree from ape package, such as:

 tree=read.tree("tree.nhx")
  class(tree)
  [1] "multiPhylo"

and I found that in the function read.nhx from ggtree, Ntip will test if the object is a phylo object

    if (!inherits(phy, "phylo")) 
       stop("object \"phy\" is not of class \"phylo\"")

this omitted  multiPhylo object created by read.tree.
please consider fixing it.

**Comment by GuangchuangYu** [comment]
`read.nhx` is designed for parsing a single tree, so this is not an issue to be fixed.

I may consider to **extend** the function to support parsing multiple trees from one single NHX file.

**Comment by carl-** [comment]
that is a good idea. thanks
