### ISSUE TITLE
geom_strip() labelling

### ISSUE THREAD

**Issue by CookieOwl** [GuangchuangYu/ggtree#69]
Hi G, I will show you the issue here.
(side note, ggtree 1.4.12 is corrupt.)

Main problem:
With the following code (taken from your vignette), you can plot bars similar to geom_cladelabel but across multiple groups. Say I want to call the red bar 'Science', the "label =" function does not work in geom_strip, but it does in geom_cladelabel. Can you make a fix for geom_strip??
See below:
_____________________________________________________________
```
library(ggtree)
packageVersion(ggtree)

nwk <- system.file("extdata", "sample.nwk", package="ggtree")
tree <- read.tree(nwk)
ggtree(tree) + geom_tiplab() + 
  geom_strip('E', 'G', barsize=2, color='red') + 
  geom_strip('F', 'L', barsize=2, color='blue')
```
_____________________________________________________________
```
ggtree(tree) + geom_tiplab() +
  geom_strip('E', 'G', barsize=2, color='red', label="Science") + 
  geom_strip('F', 'L', barsize=2, color='blue')

>Warning message:
>Computation failed in `stat_strip_text()`:
>input taxa is not valid... 
```
_____________________________________________________________
```
ggtree(tree) + geom_tiplab() + 
geom_cladelabel(node=23, label="Science")
```

**Comment by GuangchuangYu** [comment]
just install the new version by:

```
devtools::install_bioc("ggtree")
```

which should fix the issue.

**Comment by GuangchuangYu** [comment]
see also <https://github.com/GuangchuangYu/ggtree/commit/bceb2bc3ff97daee49f9fb49f28e4abb6449a3ad#diff-ff4e2dc4962dc25a1512353299992c8dR3>

**Comment by brisk022** [comment]
Could you please update the documentation for geom_strip to reflect this? It would also be nice if you could update the example in the Annotation vignette to show the use of labels and the nodeid function.
