### ISSUE TITLE
How to fix "package ‘ggtree’ had non-zero exit status" in Linux

### ISSUE THREAD

**Issue by santorellijr** [GuangchuangYu/ggtree#75]
Hello
I have been trying to install ggtree package and received this message: **package ‘ggtree’ had non-zero exit status**. I would like to know, how to fix it? My R version is 3.2.3.

Thanks a lot

**Comment by santorellijr** [comment]
Sorry! There is a same topic here!

**Comment by santorellijr** [comment]
Fixed! 
I only followed this links: https://github.com/GuangchuangYu/ggtree/issues/73 and https://github.com/GuangchuangYu/ggtree/wiki/ggtree-installation

Note: 
In the second link, the lib names changed for libfftx3-3 and libtiff5-dev instead fftw3 and libtiff4-dev, respectively!

thanks a lot!

**Comment by GuangchuangYu** [comment]
@santorellijr Can you help editing the page, <https://github.com/GuangchuangYu/ggtree/wiki/ggtree-installation>, with your experience. For example in which OS (Ubuntu?, version 16.04?), we need to install libfftx3-3 and libtiff5-dev (apt-get install ?).

Thank you!

BTW: ggtree is fast evolving package, I recommend you use R-3.3.1 and install the latest release version.

**Comment by santorellijr** [comment]
Hi @GuangchuangYu! 
The page was edited! I did only tiny changes!

**Comment by GuangchuangYu** [comment]
thanks :)
