### ISSUE TITLE
custom edge colouring

### ISSUE THREAD

**Issue by brj1** [GuangchuangYu/ggtree#76]
According to the vignette on bioconductor.org, ggtree supports custom annotation, and thus custom colouring, of tips/nodes via the "%<+%" operator. It would be nice to have the same capability for custom edge colouring.

Thanks.

**Comment by GuangchuangYu** [comment]
You can use [phylo4d](https://github.com/GuangchuangYu/ggtree/issues/47):

```
require(ggtree)
require(phylobase)

set.seed(123)
tr = rtree(30)
g1 = as(tr, 'phylo4')
d = data.frame(color=sample(c('red', 'blue', 'green'), 30, replace=T))
rownames(d) = tr$tip.label
g2 = phylo4d(g1, d)

rNodeData <- data.frame(randomTrait = rnorm(nNodes(g1)),
                        color = sample(c('purple', 'yellow', 'black'), nNodes(g1), replace=T),
                        row.names = nodeId(g1, "internal"))

nodeData(g2) <- rNodeData
ggtree(g2, aes(color=I(color)))
```

Using `%<+%` is also possible:

```
require(ggtree)

set.seed(123)
tr = rtree(30)

d = data.frame(node=1:59, color=sample(c('red', 'blue', 'green'), 59, replace=T))
p = ggplot(tr)
p %<+% d + geom_tree(aes(color=I(color)))
p %<+% d + geom_tree(aes(color=I(color))) + theme_tree()
```

**Comment by bmaitner** [comment]
In the examples provided, the user is directed to supply a set of values for each node, as is done with plotBranchbyTrait(tree, x, mode="nodes").  Is there a way to instead supply a vector of edge lengths directly, equivalent to plotBranchbyTrait(tree, x, mode="edges")?
