### ISSUE TITLE
geom_point2 symbol rotation

### ISSUE THREAD

**Issue by RaSieb** [GuangchuangYu/ggtree#77]
Hi, I really appreciate ggtree2, and I am mostly using it for circular trees. It works fine enough, but there is some issues with the angles, one of them in geom_point2: Angles for tip symbols (eg. a star or rhomboid) are not adjusted, making a tree hard to read when symbols aren´t rotation symmetric.
I think this would not be too hard to fix by adding something similar as in geom_tiplab2 into the function of geom_point2.

**Comment by GuangchuangYu** [comment]
did you try:

```r
p + geom_tippoint(aes(angle=angle))
```

**Comment by RaSieb** [comment]
Just tried it, but it does not solve the problem

**Comment by GuangchuangYu** [comment]
just figure out that `angle` aesthetics mapping is not supported for `ggplot2`.

This should be a feature request to [ggplot2](https://github.com/hadley/ggplot2).

**Comment by RaSieb** [comment]
ok, thanks a lot for looking into it!
