### ISSUE TITLE
Allow `read.nhx()` to read trees without NHX tags

### ISSUE THREAD

**Issue by caseywdunn** [GuangchuangYu/ggtree#79]
At the moment, passing a tree without NHX tags to `ggtree::read.nhx()` results in a series of errors. The NHX file specification , http://home.cc.umanitoba.ca/~psgendb/doc/atv/NHX.pdf , does not require that all or any nodes have NHX tags, so some compliant trees (ie, normal newick trees) will result in errors.

I propose that `ggtree::read.nhx()` is modified such that it can still parse a tree with no nhx tags, and that the resulting `@nhx_tags` data frame contains only the `node` column and row names.

This will lead to more consistent behavior.

**Comment by GuangchuangYu** [comment]
and it was supported :-)
