### ISSUE TITLE
Problem to install

### ISSUE THREAD

**Issue by paternogbc** [GuangchuangYu/ggtree#8]
Hi,

any advise why I cannot install `ggtree`?

    devtools::install_github("GuangchuangYu/ggtree")
    Downloading github repo GuangchuangYu/ggtree@master
    Installing ggtree
    Skipping 1 packages not available: Biostrings
    '/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
    '/tmp/Rtmp7plp5Y/devtools9ab788b5182/GuangchuangYu-ggtree-b82ce5a'  \
    --library='/home/paterno/R/x86_64-pc-linux-gnu-library/3.2' --install-tests 

    * installing *source* package ‘ggtree’ ...
    ** R
    ** inst
    ** tests
    ** preparing package for lazy loading
    Creating a generic function for ‘nchar’ from package ‘base’ in package ‘S4Vectors’
    Error : objeto ‘GeomPoint’ não foi exportado por 'namespace:ggplot2'
    ERROR: lazy loading failed for package ‘ggtree’
    * removing ‘/home/paterno/R/x86_64-pc-linux-gnu-library/3.2/ggtree’
    Erro: Command failed (1)

**Comment by GuangchuangYu** [comment]
This github version is consistent with the github version of `ggplot2`, which is different from the CRAN one.

If you would like to use this version, you should install it via:

```r
devtools::install_github(c("hadley/ggplot2", "GuangchuangYu/ggtree"))
```

I recommend you use Bioconductor release version, which compatible with CRAN ggplot2.
You can use the following command to install it.

```r
source("https://www.bioconductor.org/biocLite.R")
biocLite("ggtree")
```

**Comment by paternogbc** [comment]
Ok thank you very much!
