### ISSUE TITLE
using heatmap in facet_plot

### ISSUE THREAD

**Issue by awitney** [GuangchuangYu/ggtree#82]
Hi, is it possible to use a heatmap in the facet_plot? I would like to have 3 panels: tree, heatmap, boxplot, but the heatmap examples use gheatmap, can this be incorporated into the facet_plot syntax? Thanks

**Comment by GuangchuangYu** [comment]
```r
> head(dd)
                             id gene type
1 A/Swine/Binh_Duong/03_10/2010  PB2 trig
2 A/Swine/Binh_Duong/03_08/2010  PB2 trig
3          A/Swine/HK/2857/2011  PB2  pdm
4          A/Swine/HK/1071/2012  PB2  pdm
5          A/Swine/HK/2454/2012  PB2  pdm
6        A/Swine/GX_NS2783/2010  PB2  pdm
> facet_plot(p, 'heatmap', dd, geom_tile, aes(x=gene, fill=type))
Error: Discrete value supplied to continuous scale
> facet_plot(p, 'heatmap', dd, geom_tile, aes(x=as.numeric(as.factor(gene)), fill=type)) + theme_tree2(legend.position='right')
```

![2016-10-28-001601_1280x800_scrot](https://cloud.githubusercontent.com/assets/626539/19775655/b7e646e8-9ca3-11e6-94e7-03d488449ffb.png)

possible, but `ggplot2` can't support different types of value in the same axis (continuous for tree, and discrete for heatmap column), we need to convert the column name as number and modify them in illustrator.

**Comment by RajantiSubangkit** [comment]
Dear 
i have already success to perform heatmap annotation and associate the tree with barplot
but i have a problem, my heat map figure also split into to the barplot facet, the formula as below

data
MyTree <- read.tree("Nn.tre")
MyTree

p<-ggtree(MyTree,layout = "rectangular")+
  geom_tiplab(size=2,align=FALSE, linesize=0.2,geom = "text")+
  ggtitle("unrooted layout")+
  theme_tree2()
p1<-gheatmap(p,data,offset = 2, width=0.8, font.size=2, 
             colnames_angle=0, hjust=0.5,colnames_position = "top",color = "white",
             low = "white", high = "black")

d1 <- data.frame(id=MyTree$tip.label, val=rnorm(50, sd=3))

p2 <- facet_plot(p1, panel='No. Isolate', data=d1, geom=geom_segment, 
                 aes(x=0, xend=id, y=y, yend=y), size=2, color="black")
p2
would you like to help me, thanx before
[preview.pdf](https://github.com/GuangchuangYu/ggtree/files/1564138/preview.pdf)

**Comment by krisen** [comment]
I am experiencing the same problem as RajantiSubangkit but with msaplot instead of gheatmap.
