### ISSUE TITLE
Error in read.beast() with FigTree exemple

### ISSUE THREAD

**Issue by RaSieb** [GuangchuangYu/ggtree#84]
```
> require(ggplot2)
> require(ggtree)
> x <- read.beast("/Applications/FigTree/influenza.tree")
Error in 1:nnode : argument of length 0
> stats <- ggtree:::read.stats_beast(file)
Error in 1:nnode : argument of length 0
> translation <- ggtree:::read.trans_beast(file)
> treetext <- ggtree:::read.treetext_beast(file)
> stats <- ggtree:::read.stats_beast(file)
Error in 1:nnode : argument of length 0
> phylo <- read.nexus(file)
> 
```

**Comment by GuangchuangYu** [comment]
will be fixed in v1.6.2

**Comment by pclangat** [comment]
Hi there, I still get this error for the example (and my own files) using ggtree v1.6.4

> x <- read.beast("/Software_downloaded/FigTree_v1.4.2/influenza.tree")
Error in 1:nnode : argument of length 0

**Comment by GuangchuangYu** [comment]
```r
rvcheck::check_bioc("ggtree")
```

make sure you are using `1.6.4`.

**Comment by koreinhart** [comment]
Something similar with ggtree v2.4.2...

> library(ggtree)
> beast_file <- system.file("examples/MCC_FluA_H3.tree", package="ggtree")
> rst_file <- system.file("examples/rst", package="ggtree")
> mlc_file <- system.file("examples/mlc", package="ggtree")
> beast_tree <- read.beast(beast_file)
Error in read.beast(beast_file) : could not find function "read.beast"

**Comment by xiangpin** [comment]
All parser functions have been removed from `ggtree` and collected into the `treeio` package.  You can refer to the [article](https://academic.oup.com/mbe/article/37/2/599/5601621). 
So the `treeio` should also be imported if you want to use parser functions.

```
library(ggtree)
library(treeio)
beast_file <- system.file("examples/MCC_FluA_H3.tree", package="ggtree")
read.beast(beast_file)
```
