### ISSUE TITLE
time scale

### ISSUE THREAD

**Issue by zuranojp** [GuangchuangYu/ggtree#87]
Hi Guangchuan,

Can you add an option into the theme_tree2() function to show  time scale as Reverse axis in Figtree or like AxisPhylo() function.

require(ape)
tr <- rtree(10)
ggtree(tr) + theme_tree2()

I´m suggesting to show the time whether possible like

tr <- rtree(10)
plot(tr)
axisPhylo()

**Comment by GuangchuangYu** [comment]
```r
> p =ggtree(tr) + theme_tree2()
> p1 = revts(p)
> p2 = p1 + scale_x_continuous(breaks=c(-4:0), labels=abs(-4:0))
> multiplot(p, p1, p2, ncol=3)
```

`revts` function is now available in `github` version.

![screen shot 2016-11-07 at 11 00 08 am](https://cloud.githubusercontent.com/assets/626539/20045117/7acb0cc4-a4d9-11e6-9e89-d0011b68da1a.png)

**Comment by Ax3man** [comment]
For future visitors, passing `abs` as the `labels` is probably easiest in most cases:

```r
p <- ggtree(tr) + theme_tree2() + scale_x_continuous(labels = abs)
multiplot(p, revts(p), ncol = 2)
```
![Rplot](https://user-images.githubusercontent.com/15309336/59471597-4e7d1b00-8df0-11e9-8bae-8fa6c03850ea.png)

**Comment by GuangchuangYu** [comment]
@Ax3man thanks for the tip.
