### ISSUE TITLE
Reading Sumtrees output

### ISSUE THREAD

**Issue by JoseAAndres** [GuangchuangYu/ggtree#88]
Hi there, I am running a set of ML analyses and I'd like to want to use ggtree to plot the Sumtrees output(s), similar to the one pasted bellow. Is it possible to read & store all variables (e.g. length _median, length_range, etc.? 
 
    TREE bestREP2 = [&U] [!GarliScore -1540.421571][!GarliModel  M1 r  1.00000 5.49843 1.00000 1.00000 5.49843 1.00000 e 0.23443 0.22942 0.18497 0.35117 ](((Hist11:0.00473059[&support=100.0][&length_mean=0.0045080525,length_median=0.004749965,length_sd=0.0038642801238,length_hpd95={1e-08,0.01216887},length_quant_5_95={1e-08,0.00982644},length_range={1e-08,0.01726472}],His3:0.00471961[&support=100.0][&length_mean=0.0048722668,length_median=0.00472719,length_sd=0.00362693358832,length_hpd95={1e-08,0.01204823},length_quant_5_95={1e-08,0.01203543},length_range={1e-08,0.01713032}],Hist4:1e-08[&support=100.0][&length_mean=1e-08,length_median=1e-08,length_sd=0.0,length_hpd95={1e-08,1e-08},length_quant_5_95={1e-08,1e-08},length_range={1e-08,1e-08}],His2:0.00235667[&support=100.0][&length_mean=0.0022185495,length_median=0.00235677,length_sd=0.00261735285722,length_hpd95={1e-08,0.00721692},length_quant_5_95={1e-08,0.00720769},length_range={1e-08,0.01474128}])61:0.02135953[&support=61.0][&length_mean=0.0152985839344,length_median=0.01470197,length_sd=0.0108037143563,length_hpd95={6.051e-05,0.03467614},length_quant_5_95={0.00068907,0.03439018},length_range={6.051e-05,0.044339}],((Granulife:0.04177758[&support=100.0][&length_mean=0.0787735382,length_median=0.081937245,length_sd=0.0298433698427,length_hpd95={1e-08,0.11671346},length_quant_5_95={1e-08,0.1157935},length_range={1e-08,0.13514404}],(AF412437:0.006575[&support=100.0][&length_mean=0.0029003254,length_median=1e-08,length_sd=0.00639850611684,length_hpd95={1e-08,0.01933768},length_quant_5_95={1e-08,0.01931547},length_range={1e-08,0.02473377}],AF097502:0.00985361[&support=100.0][&length_mean=0.0137111333,length_median=0.014537205,length_sd=0.00842779968126,length_hpd95={1e-08,0.02520245},length_quant_5_95={1e-08,0.02505411},length_range={1e-08,0.03260542}])100:0.19490508[&support=100.0][&length_mean=0.5495704097,length_median=0.522218105,length_sd=0.204879968642,length_hpd95={0.27749973,0.98113274},length_quant_5_95={0.30591119,0.93088649},length_range={0.27749973,1.33580549}])15:0.02649458[&support=15.0][&length_mean=0.057511832,length_median=0.06937638,length_sd=0.0337685530201,length_hpd95={0.01271555,0.10839426},length_quant_5_95=None,length_range={0.01271555,0.10839426}],((EF597199:0.00473328[&support=100.0][&length_mean=0.0034627376,length_median=0.00235633,length_sd=0.00339603759714,length_hpd95={1e-08,0.00970678},length_quant_5_95={1e-08,0.00966487},length_range={1e-08,0.01480182}],EF597191:0.00235107[&support=100.0][&length_mean=0.0011327762,length_median=1e-08,length_sd=0.0017380809443,length_hpd95={1e-08,0.0047677},length_quant_5_95={1e-08,0.00476455},length_range={1e-08,0.00722076}])38:0.00411151[&support=38.0][&length_mean=0.00475296684211,length_median=0.00474354,length_sd=0.00244680107359,length_hpd95={0.00233395,0.00962908},length_quant_5_95={0.0023366,0.00955723},length_range={0.00233395,0.01113812}],(EF597200:0.00235982[&support=100.0][&length_mean=0.0026217616,length_median=0.00235025,length_sd=0.00252648682307,length_hpd95={1e-08,0.00719232},length_quant_5_95={1e-08,0.00712611},length_range={1e-08,0.01202731}],(EF597192:0.00709061[&support=100.0][&length_mean=0.0059498828,length_median=0.0047231,length_sd=0.0044856976993,length_hpd95={1e-08,0.01445903},length_quant_5_95={1e-08,0.01438891},length_range={1e-08,0.02185639}],EF597190:1e-08[&support=100.0][&length_mean=0.0003995821,length_median=1e-08,length_sd=0.00121550429938,length_hpd95={1e-08,0.00234737},length_quant_5_95={1e-08,0.00234665},length_range={1e-08,0.00720922}])70:0.00472849[&support=70.0][&length_mean=0.006054866,length_median=0.004777475,length_sd=0.00308978077141,length_hpd95={0.00234332,0.01194304},length_quant_5_95={0.00234591,0.01194304},length_range={0.00234332,0.01472354}])29:0.0006307[&support=29.0][&length_mean=0.00287592931034,length_median=0.00235832,length_sd=0.00183152980665,length_hpd95={0.00026167,0.00725608},length_quant_5_95=None,length_range={0.00026167,0.00725608}])77:0.02354806[&support=77.0][&length_mean=0.0292102488312,length_median=0.02773668,length_sd=0.00948520938681,length_hpd95={0.00939668,0.04695105},length_quant_5_95={0.01482961,0.04643451},length_range={0.00939668,0.05601087}])17:0.02311712[&support=17.0][&length_mean=0.0240219258824,length_median=0.01943547,length_sd=0.0141892410557,length_hpd95={0.00707059,0.05844703},length_quant_5_95=None,length_range={0.00707059,0.05844703}])57:0.00761738[&support=57.0][&length_mean=0.0104236338596,length_median=0.00967573,length_sd=0.00614396683617,length_hpd95={0.00075915,0.02316407},length_quant_5_95={0.00130242,0.02278284},length_range={0.00075915,0.02676995}],(((TL13:0.0023479[&support=100.0][&length_mean=0.0026879915,length_median=0.002348305,length_sd=0.00239827046488,length_hpd95={1e-08,0.00710945},length_quant_5_95={1e-08,0.00710099},length_range={1e-08,0.00953996}],(AT3_AT1:0.00234405[&support=100.0][&length_mean=0.0022158134,length_median=0.00234656,length_sd=0.00220198429916,length_hpd95={1e-08,0.00710165},length_quant_5_95={1e-08,0.00709938},length_range={1e-08,0.00956513}],L_M_AT:1e-08[&support=100.0][&length_mean=1e-08,length_median=1e-08,length_sd=0.0,length_hpd95={1e-08,1e-08},length_quant_5_95={1e-08,1e-08},length_range={1e-08,1e-08}],L3:0.00235301[&support=100.0][&length_mean=0.0023677108,length_median=0.002359255,length_sd=0.0028246644848,length_hpd95={1e-08,0.00727155},length_quant_5_95={1e-08,0.0072568},length_range={1e-08,0.01477801}])63:0.00235218[&support=63.0][&length_mean=0.00366742968254,length_median=0.00236425,length_sd=0.00184258648657,length_hpd95={0.00235221,0.00723585},length_quant_5_95={0.00235458,0.00721196},length_range={0.00235221,0.00973644}],TL_L_M_AT:1e-08[&support=100.0][&length_mean=1e-08,length_median=1e-08,length_sd=0.0,length_hpd95={1e-08,1e-08},length_quant_5_95={1e-08,1e-08},length_range={1e-08,1e-08}],L6_AT_TL:0.00234998[&support=100.0][&length_mean=0.0020290432,length_median=0.00234257,length_sd=0.00245035834247,length_hpd95={1e-08,0.00710386},length_quant_5_95={1e-08,0.00709549},length_range={1e-08,0.00955622}],M_TL:0.00234989[&support=100.0][&length_mean=0.001246493,length_median=1e-08,length_sd=0.00164008858786,length_hpd95={1e-08,0.00472289},length_quant_5_95={1e-08,0.00471708},length_range={1e-08,0.00711031}])71:0.00756053[&support=71.0][&length_mean=0.00743253056338,length_median=0.00716619,length_sd=0.00384518914543,length_hpd95={0.00217847,0.0126406},length_quant_5_95={0.00230902,0.01223673},length_range={0.00217847,0.02236861}],L4:0.01004428[&support=100.0][&length_mean=0.0083739437,length_median=0.00770439,length_sd=0.00504466127039,length_hpd95={1e-08,0.01803793},length_quant_5_95={0.00220629,0.01793364},length_range={1e-08,0.02412589}])53:0.00530672[&support=53.0][&length_mean=0.00709122603774,length_median=0.00709177,length_sd=0.00366995185581,length_hpd95={0.00215249,0.01328428},length_quant_5_95={0.00216682,0.01234814},length_range={0.00118622,0.02111141}],(PQ:1e-08[&support=100.0][&length_mean=1e-08,length_median=1e-08,length_sd=0.0,length_hpd95={1e-08,1e-08},length_quant_5_95={1e-08,1e-08},length_range={1e-08,1e-08}],(Q7:0.00235641[&support=100.0][&length_mean=0.0023843426,length_median=0.002359005,length_sd=0.00248714372923,length_hpd95={1e-08,0.00721312},length_quant_5_95={1e-08,0.00721228},length_range={1e-08,0.0097854}],MD:0.00235369[&support=100.0][&length_mean=0.0022207757,length_median=0.002345585,length_sd=0.00260967314887,length_hpd95={1e-08,0.00714445},length_quant_5_95={1e-08,0.0071286},length_range={1e-08,0.00955721}],B_PQ_Q:1e-08[&support=100.0][&length_mean=1e-08,length_median=1e-08,length_sd=0.0,length_hpd95={1e-08,1e-08},length_quant_5_95={1e-08,1e-08},length_range={1e-08,1e-08}],B7:0.00235315[&support=100.0][&length_mean=0.0023831876,length_median=0.002346595,length_sd=0.00248855160191,length_hpd95={1e-08,0.00713187},length_quant_5_95={1e-08,0.00712384},length_range={1e-08,0.00957217}],B6:0.0023537[&support=100.0][&length_mean=0.0021005836,length_median=0.00234499,length_sd=0.0025194114045,length_hpd95={1e-08,0.00712072},length_quant_5_95={1e-08,0.00711768},length_range={1e-08,0.01191107}])58:0.00235157[&support=58.0][&length_mean=0.00378116051724,length_median=0.002351145,length_sd=0.00188933962392,length_hpd95={0.00234123,0.00713186},length_quant_5_95={0.00234377,0.00711894},length_range={0.00234123,0.00951671}])86:0.00849012[&support=86.0][&length_mean=0.00940000569767,length_median=0.00944748,length_sd=0.00440212755099,length_hpd95={0.00203526,0.01678356},length_quant_5_95={0.00240755,0.01596297},length_range={0.00203526,0.01975313}])83:0.01660719[&support=83.0][&length_mean=0.0183097549398,length_median=0.01838007,length_sd=0.00667192171011,length_hpd95={0.0046377,0.03024178},length_quant_5_95={0.00759441,0.0293897},length_range={0.0046377,0.04062075}],(Lem3:0.00234514[&support=100.0][&length_mean=0.0025964384,length_median=0.00234705,length_sd=0.00254971928494,length_hpd95={1e-08,0.0071177},length_quant_5_95={1e-08,0.00711123},length_range={1e-08,0.00958783}],Lema1:1e-08[&support=100.0][&length_mean=1e-08,length_median=1e-08,length_sd=0.0,length_hpd95={1e-08,1e-08},length_quant_5_95={1e-08,1e-08},length_range={1e-08,1e-08}],Lema2:0.0023513[&support=100.0][&length_mean=0.002312584,length_median=0.00235933,length_sd=0.00238183460628,length_hpd95={1e-08,0.00721175},length_quant_5_95={1e-08,0.00720248},length_range={1e-08,0.0098039}])93:0.00998522[&support=93.0][&length_mean=0.00998431043011,length_median=0.00931288,length_sd=0.00577769019745,length_hpd95={0.00142368,0.01991021},length_quant_5_95={0.0020911,0.01931802},length_range={0.00142368,0.03212515}])100[&support=100.0][&length_mean=0.0,length_median=0,length_sd=0.0,length_hpd95={0,0},length_quant_5_95={0,0},length_range={0,0}];

**Comment by GuangchuangYu** [comment]
this seems not the full file, but an excerpt of the `TREE` block in a `NEXUS` file.
