### ISSUE TITLE
Error in namespaceExport(ns, exports)

### ISSUE THREAD

**Issue by Leifor** [GuangchuangYu/ggtree#9]
Hi,
Thanks for the nice package. 
I think the package installed correctly, but when I require it appears the following message:
Error in namespaceExport(ns, exports) : undefined exports: score, score<-
Could you help me?
Leifor

**Comment by GuangchuangYu** [comment]
please make sure you are using the latest `R` (currently 3.2.2).

And use the following command to install `ggtree`.

```r
## try http if https is not available
source("https://bioconductor.org/biocLite.R")
biocLite("ggtree")
```

**Comment by Leifor** [comment]
Yes. I used it.

> source("http://bioconductor.org/biocLite.R")
Bioconductor version 3.1 (BiocInstaller 1.18.4), ?biocLite for help

> biocLite("ggtree")
BioC_mirror: http://bioconductor.org
Using Bioconductor version 3.1 (BiocInstaller 1.18.4), R version 3.2.2.
Installing package(s) ‘ggtree’
trying URL '
http://bioconductor.org/packages/3.1/bioc/bin/windows/contrib/3.2/ggtree_1.0.19.zip
'
Content type 'application/zip' length 4826969 bytes (4.6 MB)
downloaded 4.6 MB

package ‘ggtree’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\AppData\Local\Temp\RtmpAR0gFl\downloaded_packages

> library("ggtree")
Creating a generic function for ‘nchar’ from package ‘base’ in package
‘S4Vectors’
Error in namespaceExport(ns, exports) : undefined exports: score, score<-
Error: package or namespace load failed for ‘ggtree’

> require("ggtree")
Carregando pacotes exigidos: ggtree
Error in namespaceExport(ns, exports) : undefined exports: score, score<-


2015-09-08 22:36 GMT-03:00 Guangchuang Yu <notifications@github.com>:

**Comment by GuangchuangYu** [comment]
What's the output if you do `library("BiocGenerics")`?

**Comment by Leifor** [comment]
> library("BiocGenerics")
Carregando pacotes exigidos: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ, clusterExport,
    clusterMap, parApply, parCapply, parLapply, parLapplyLB, parRapply,
parSapply,
    parSapplyLB

The following object is masked from ‘package:stats’:

    xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, as.vector, cbind, colnames,
do.call,
    duplicated, eval, evalq, Filter, Find, get, intersect, is.unsorted,
lapply,
    Map, mapply, match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rep.int, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unlist, unsplit

>

2015-09-09 22:24 GMT-03:00 Guangchuang Yu <notifications@github.com>:

**Comment by GuangchuangYu** [comment]
What's the output of `library(Biostrings)`?

**Comment by Leifor** [comment]
Thanks for helping me.
I had a problem with the package ‘IRanges’, but it's all right now.

2015-09-09 23:20 GMT-03:00 Guangchuang Yu <notifications@github.com>:
