### ISSUE TITLE
Error with newest ggplot2 version (2.2)

### ISSUE THREAD

**Issue by ddiez** [GuangchuangYu/ggtree#91]
I get an error when trying to plot a tree using the newest version of ggplot2 (2.2):

```
> library(ggtree)
> library(ape)
> tr <- rtree(10)
> ggtree(tr)
Error: StatTreeHorizontal was built with an incompatible version of ggproto.
Please reinstall the package that provides this extension.
```

**Comment by ddiez** [comment]
Installing ggtree from source seems to fix the problem.

**Comment by jrash** [comment]
Thanks, I was having the same issue and the fix worked for me too.

**Comment by danfulop** [comment]
@ddiez and @jrash which source? The stable source in bioconductor (v 1.0.21), the development source in bioconductor (v 1.7.3), or the source on GitHub in the master branch?  Thanks!!

**Comment by ddiez** [comment]
*source* means installing from source rather than the built binaries:

`biocLite("ggtree", type = "source")`

This will rebuild the package using the latest *ggproto* spec in *ggplot2* and solve the problem.

**Comment by GuangchuangYu** [comment]
@danfulop The stable release version in bioconductor is `1.6.3`. 

For release version, pls always refer to <https://bioconductor.org/packages/ggtree/>.

Actually, if you visit old version (e.g. 1.0.21), the page will show your the following message:

```
This package is for version 3.1 of Bioconductor; for the stable, up-to-date release version, see ggtree.
```

**Comment by GuangchuangYu** [comment]
@ddiez I bump up the version to force BioC to re-build the tarball, see <https://github.com/Bioconductor-mirror/ggtree/commit/68bfcfc37ca9b89a0ee1adf70f7ad2bc39964344>.

**Comment by danfulop** [comment]
@ddiez Thanks for clarifying which source.  ...and @GuangchuangYu thanks for pointing me to the proper bioconductor page; I didn't notice I was on an outdated BioC page.

**Comment by nick-youngblut** [comment]
I'm getting this same error when installing `ggtree` from with conda via `conda install -c bioconda bioconductor-ggtree`. Is the `bioconda` channel just not up-to-date? 

My installed `ggplot2` version is `bioconda --> 2.2.0-r3.3.1_0 r`

**Comment by GuangchuangYu** [comment]
don't use bioconda for r packages. most of them are out-dated.
