### ISSUE TITLE
ggtree error with ggplot2::ggproto

### ISSUE THREAD

**Issue by nilmot13** [GuangchuangYu/ggtree#92]
Hi,

When I'm trying to draw phylogenetic tree using ggtree rather than base function from R. I've encountered this problem. I've ensured "physeq" is a phylo-class and ggplot2 is of latest version.

Help would be much appreciated

Thank you

>class(physeq)
[1] "phyloseq"
attr(,"package")
[1] "phyloseq"

>ggtree(physeq)
Error: StatTreeHorizontal was built with an incompatible version of ggproto.
Please reinstall the package that provides this extension.

**Comment by GuangchuangYu** [comment]
<https://github.com/GuangchuangYu/ggtree/issues/91>
