### ISSUE TITLE
facet_plot支持对圆形树添加注释了吗

### ISSUE THREAD

**Issue by 861934367** [GuangchuangYu/ggtree#93]
![image](https://cloud.githubusercontent.com/assets/22164318/20309409/d670d0cc-ab82-11e6-8c60-6fe501170c11.png)
请问这张图的外圈的注释应该怎么画出来呢，内部的圆形的树是按照OTUs分类添加的颜色及边的颜色，外圈是对这些OTUs的注释，不知道现在facet_plot这个函数支持不支持这种圆形的注释。
非常感谢！

**Comment by GuangchuangYu** [comment]
`facet_plot`是拿来右对齐的，circular form必须是不行的。但这种图也不是不行，你看`gheatmap`就可以转成circular form，主要是我得另外写一个类似的但画的是bar的函数才行。目前是不可以的。

**Comment by GuangchuangYu** [comment]
BTW:你可以关注公众号biobabble，观注ggtree的更新。

**Comment by 861934367** [comment]
非常感谢您的回答，公众号已关注。
另外还有个问题，就是下图的2节点为什么和13节点之间会有缝隙，并且节点的背景色要想对齐的话需要根据branch.length去调整extend的大小，代码如下：ggtree(tree,layout="circular", open.angle = 0) + geom_hilight(node=list(2), fill=list("green"), alpha=.5,extend = 8) + geom_hilight(node=list(8), fill=list("green"), alpha=.5,extend = 18) + geom_hilight(node=list(12), fill=list("red"), alpha=.5,extend = 22)+geom_hilight(node=list(13), fill=list("blue"), alpha=.5)+geom_text2(aes(subset=isTip, label=node), hjust=-.3)
非常感谢！
![image](https://cloud.githubusercontent.com/assets/22164318/20335079/51f7de76-abfa-11e6-8c20-209fedea5db5.png)

**Comment by GuangchuangYu** [comment]
缝隙是必须的，总不能让它们重叠。

但你这个缝隙比正常要大，这是必然是因为你用了老版本，新版本早就修正了。

问问题之前，follow一下<https://guangchuangyu.github.io/ggtree/#feedback>.

**Comment by GuangchuangYu** [comment]
另外，github issue主要用于bug report或feature request。

问问题的话，如果google group上不去，可以到biostars上问。
