### ISSUE TITLE
Ggtree fails to display boxplots with high values

### ISSUE THREAD

**Issue by seth-1** [GuangchuangYu/ggtree#96]
Hi! Thanks for creating this great package!

I tried to combine a boxplot and a tree using facet_plot. Unfortunately, when displaying boxplots with high values, the plot seems to adjust ylim automatically so the plot 'disappears'.

```R
tr <- rtree(30)
p <- ggtree(tr)
d4 = data.frame(id=rep(tr$tip.label, each=20), val=as.vector(sapply(1:30, function(i) rnorm(20, mean=i))) )
# Works fine
facet_plot(p, panel="Boxplot", data=d4, geom_boxploth, mapping = aes(x=val, group = label))

d5 <- d4
d5$val <- d5$val*100
# Disappears to the bottom of the device
facet_plot(p, panel="Boxplot", data=d5, geom_boxploth, mapping = aes(x=val, group = label)) 
```
#### Correct plot
![correctplot](https://cloud.githubusercontent.com/assets/10029760/20347144/10c90744-ac00-11e6-982b-731d746f9eda.png)

#### Compressed plot
![highvalues](https://cloud.githubusercontent.com/assets/10029760/20347145/15672bb4-ac00-11e6-91f4-d60ef06cd1d4.png)

**Comment by GuangchuangYu** [comment]
```r
> p <- ggtree:::add_panel(p, 'Boxplot')
> df = p %+>% d5
> head(df)
  label branch.length y isTip  .panel      val
1    t1     0.1369876 4  TRUE Boxplot 2722.792
2    t1     0.1369876 4  TRUE Boxplot 2606.299
3    t1     0.1369876 4  TRUE Boxplot 2707.818
4    t1     0.1369876 4  TRUE Boxplot 2769.059
5    t1     0.1369876 4  TRUE Boxplot 2623.170
6    t1     0.1369876 4  TRUE Boxplot 2845.702
> ggplot(df) + geom_boxploth(aes(x=val, y=label, group=label)) -> p1
> ggplot(df) + geom_boxploth(aes(x=val, y=y, group=label)) -> p2
> multiplot(p1, p2, ncol=2)
```

![screen shot 2016-11-16 at 9 21 32 pm](https://cloud.githubusercontent.com/assets/626539/20348870/b2b0979c-ac42-11e6-800c-bc514db9084c.png)

This seems to be an issue of `ggstance`. Maybe @lionel- can help.

**Comment by lionel-** [comment]
It seems to work fine with latest ggstance/ggplot2.

**Comment by wcornwell** [comment]
I am also having this issue with these versions:

```
ggtree_1.7.4
ggplot2_2.2.0.9000
ggstance_0.3
```

not sure what's going on but I'm getting the same behaviour as @seth-1 describes.

**Comment by andzandz11** [comment]
I get the same error. Therefore I divide all my data in the right panel by 1000 to circumvent that.

**Comment by lionel-** [comment]
could you post your R version please? ggstance fails CRAN's checks with old versions of R, this may be related.

**Comment by andzandz11** [comment]
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ggstance_0.3        ggtree_1.6.5        ggplot2_2.2.0       Biostrings_2.42.1   XVector_0.14.0     
 [6] IRanges_2.8.1       S4Vectors_0.12.1    BiocGenerics_0.20.0 rentrez_1.0.4       taxize_0.8.0       
[11] magrittr_1.5        ips_0.0-7           XML_3.98-1.5        colorspace_1.3-2    ape_4.0

**Comment by lionel-** [comment]
Hi all. Could you confirm that with the latest ggstance version (the one on github as it has not yet been sent to CRAN), the issue is fixed?

**Comment by wcornwell** [comment]
The scaling issue looks like resolved, at least for me.  Thanks!  

By the way, is there any way to get an axis on the horizontal boxplot atm?

**Comment by lionel-** [comment]
I'm not sure what you mean? But anything that is possible with vertical boxplots should be possible with horizontal ones, otherwise it's presumably a bug.

**Comment by GuangchuangYu** [comment]
@lionel- here is another example, <https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/bioc-ggtree/RgI8M4DDBT8/7Kp-hyNqAQAJ>.

![screen shot 2017-03-09 at 12 03 50 pm](https://cloud.githubusercontent.com/assets/626539/23735434/816c2f08-04c0-11e7-852e-6ad0f36f4d45.png)


Although `y` is correct, as shown in `layer_data(p, 5)$y %>% range`, without `ylim` the figure can't render properly.

**Comment by lionel-** [comment]
Can you open an issue with a small reprex at the ggstance repo please.

**Comment by GuangchuangYu** [comment]
[good news](https://github.com/lionel-/ggstance/issues/14#issuecomment-406365712 from @lionel-  that the issue has been fixed.
