### ISSUE TITLE
ggtree incorrectly applies yscale in phylo4d 

### ISSUE THREAD

**Issue by brj1** [GuangchuangYu/ggtree#98]
While trying to make custom scale values for ggtree to create 2d plots, I noticed, upon debugging ggtree, that the fortify function ignores phylo4d's data when applying yscale. I edited ggtree's code to overcome this problem, redefining fortify.phylo4d thusly:
```
fortify.phylo4d <- function(model, data, layout="rectangular", yscale="none",
                            ladderize=TRUE, right=FALSE, mrsd=NULL, ...) {
    res <- fortify.phylo4(model, data, layout, "none", ladderize, right, mrsd, ...)
    tdata <- model@data[match(res$node, rownames(model@data)), , drop=FALSE]
    scaleY(as.phylo.phylo4(model), cbind(res, tdata), yscale, layout, ...)
}
```
I like ggtree, but I find the lack of support for nonstandard data annoying.

**Comment by GuangchuangYu** [comment]
thanks for your feedback. It was incorporated.
