### ISSUE TITLE
read codeml

### ISSUE THREAD

**Issue by antoine4ucsd** [GuangchuangYu/ggtree#99]
Hi,
I am having trouble reading codeml files into ggtree. 
My goal is mostly to track specific AA mutations along the branches of my tree with ggtree as you nicely described in the tutorial...

The error message I get is below:

![screen shot 2016-11-30 at 7 53 13 am](https://cloud.githubusercontent.com/assets/18502631/20759780/c6c2ebe6-b6d2-11e6-8c5b-485d696962a7.png)

I am not sure if this is a matter of codeML parameters in the first place (my guess) or if it is related to ggtree itself.
I am uploading codon aligned sequence in phylip format along with a newick subst tree and I tried to run CodeML (GUI) with the following parameters:

<img width="1234" alt="screen shot 2016-11-30 at 7 52 36 am" src="https://cloud.githubusercontent.com/assets/18502631/20759743/a5e20e0c-b6d2-11e6-8153-2b144bdc2fba.png">

the output indicates:

<img width="827" alt="screen shot 2016-11-30 at 7 52 29 am" src="https://cloud.githubusercontent.com/assets/18502631/20759750/af64abc4-b6d2-11e6-8122-b37bd5ae045f.png">

Would you have any advices? Thoughts? Let me know if you want me to send any other files (input or output)

many thanks for your help and congrats again for this amazing package.

antoine

**Comment by antoine4ucsd** [comment]
sorry to comment my own post
I used a different tree input. While it seems to overcome the previous error,  I get another message:

![screen shot 2016-11-30 at 10 22 34 am](https://cloud.githubusercontent.com/assets/18502631/20765402/f9d8ea44-b6e6-11e6-984d-1439eacf5fce.png)

the codeml parameters were:


<img width="1236" alt="screen shot 2016-11-30 at 8 59 47 am" src="https://cloud.githubusercontent.com/assets/18502631/20765367/dd60e984-b6e6-11e6-816b-664812a2863d.png">

**Comment by GuangchuangYu** [comment]
If you want help, send a sample rst and mlc file for me to have a look on it.

**Comment by antoine4ucsd** [comment]
thanks for your quick response!
I think I fixed it but I have an additional question… for the sites to display on a tree. I don’t get how the position are calculated…
For example in the tree below, V15I is on position 59 of my alignemnt (codon alignment attached) - thoughts?

congrats again for this amazing job!!!
a
